define([], function () {
  return {
    PropertyPaneDescription: "Configure the HyperSearch federated search web part.",
    // Page 1 — Search Configuration
    SearchConfigGroupName: "Search Configuration",
    TitleFieldLabel: "Title",
    PlaceholderTextLabel: "Placeholder Text",
    ShowScopeSelectorLabel: "Show Scope Selector",
    DefaultScopeLabel: "Default Scope",
    DefaultSortByLabel: "Default Sort By",
    ResultsPerPageLabel: "Results Per Page",
    EnableTypeAheadLabel: "Enable Type-Ahead Suggestions",
    TypeAheadDebounceLabel: "Type-Ahead Debounce (ms)",
    // Page 2 — Refiners & Display
    RefinersGroupName: "Refiners & Display",
    EnableRefinersLabel: "Enable Refinement Panel",
    RefinerFieldsLabel: "Refiner Fields (JSON array)",
    ShowResultIconLabel: "Show Result Type Icon",
    ShowResultPathLabel: "Show Result Path",
    EnableResultPreviewsLabel: "Enable Document Preview",
    RefinersPageDescription: "Configure refinement panel and result display options.",
    // Page 3 — Advanced Features
    AdvancedGroupName: "Advanced Features",
    EnableSearchHistoryLabel: "Enable Search History",
    EnableAnalyticsLabel: "Enable Search Analytics",
    PromotedResultsLabel: "Promoted Results (JSON)",
    ValidateJsonLabel: "Validate JSON",
    JsonValidLabel: "JSON is valid",
    JsonInvalidLabel: "Invalid JSON format",
    AdvancedPageDescription: "Configure search history, analytics, and promoted results.",
    // Scope options
    ScopeEverything: "Everything",
    ScopeSharePoint: "SharePoint",
    ScopeOneDrive: "OneDrive",
    ScopeTeams: "Teams",
    ScopeExchange: "Exchange",
    ScopeCurrentSite: "Current Site",
    // Sort options
    SortRelevance: "Relevance",
    SortDateModified: "Date Modified",
    SortAuthor: "Author",
    // UI strings
    SearchAriaLabel: "Search",
    ClearSearchLabel: "Clear search",
    SuggestionsLabel: "Search suggestions",
    NoResultsTitle: "No results found",
    NoResultsDescription: "Try different keywords or adjust your search scope.",
    ResultCountSingular: "result",
    ResultCountPlural: "results",
    LoadingResults: "Searching...",
    PageLabel: "Page",
    OfLabel: "of",
    PreviousPageLabel: "Previous page",
    NextPageLabel: "Next page",
    // V2 — Template & Layout
    V2TemplateGroupName: "Template & Layout",
    SelectedTemplateLabel: "Search Template",
    ResultLayoutLabel: "Result Layout",
    SearchBarStyleLabel: "Search Bar Style",
    // V2 — Features
    V2FeaturesPageDescription: "Configure search features, filters, and display options.",
    V2FeaturesGroupName: "Search Features",
    EnableInstantSearchLabel: "Instant Search (results as-you-type)",
    EnableSearchVerticalsLabel: "Search Verticals (scope tabs)",
    ShowScopeTabsLabel: "Show Scope Tabs",
    EnableZeroQueryLabel: "Zero-Query Experience (trending/recent)",
    EnableQuickActionsLabel: "Quick Actions (Email, Chat, Copy)",
    EnableHitHighlightLabel: "Hit Highlighting",
    EnableResultGroupingLabel: "Result Grouping (by site/type/date)",
    EnableThumbnailPreviewsLabel: "Thumbnail Previews",
    EnableSavedSearchesLabel: "Saved Searches",
    EnablePeopleCardsLabel: "People Cards on Hover",
    EnableSpellingCorrectionLabel: "Spelling Correction",
    // V2 — Appearance
    V2AppearancePageDescription: "Customize appearance, demo mode, and advanced settings.",
    V2AppearanceGroupName: "Appearance",
    AccentColorLabel: "Accent Color",
    BorderRadiusLabel: "Border Radius (px)",
    EnableDemoModeLabel: "Enable Demo Mode (sample data)",
    ShowWizardOnInitLabel: "Show Setup Wizard on First Edit"
  };
});
