import type { IHyperTabPanel } from "../models";

/**
 * Rich, realistic sample data for HyperTabs V2.
 * 6 intranet tabs matching the mockup — works out of the box.
 */
export var SAMPLE_PANELS: IHyperTabPanel[] = [
  {
    id: "sample-getting-started",
    title: "Getting Started",
    icon: { type: "emoji", value: "\uD83D\uDE80" },
    contentType: "simple",
    content: [
      "<h3 style=\"margin-bottom:16px;font-size:20px;\">\uD83D\uDE80 Welcome to Contoso!</h3>",
      "<p style=\"margin-bottom:16px;font-size:15px;line-height:1.7;\">",
      "Welcome aboard! Whether you're a new hire or a longtime Contoso team member, this page has everything you need. ",
      "Explore the tabs above to find company policies, IT resources, benefits information, office locations, and quick links to essential tools.</p>",
      "<div style=\"display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:20px;\">",
      "<div style=\"background:linear-gradient(135deg,#deecf9,#c7dff0);padding:20px;border-radius:12px;text-align:center;\">",
      "<div style=\"font-size:32px;margin-bottom:8px;\">\uD83D\uDC65</div>",
      "<div style=\"font-weight:700;font-size:15px;margin-bottom:4px;\">Meet Your Team</div>",
      "<div style=\"font-size:13px;color:#605e5c;\">View the org chart and connect with colleagues across departments</div></div>",
      "<div style=\"background:linear-gradient(135deg,#dff6dd,#c3e6c0);padding:20px;border-radius:12px;text-align:center;\">",
      "<div style=\"font-size:32px;margin-bottom:8px;\">\uD83D\uDCDA</div>",
      "<div style=\"font-weight:700;font-size:15px;margin-bottom:4px;\">Learning Portal</div>",
      "<div style=\"font-size:13px;color:#605e5c;\">Required compliance training plus optional professional development courses</div></div>",
      "<div style=\"background:linear-gradient(135deg,#fff4ce,#ffe8a3);padding:20px;border-radius:12px;text-align:center;\">",
      "<div style=\"font-size:32px;margin-bottom:8px;\">\uD83D\uDEE0\uFE0F</div>",
      "<div style=\"font-weight:700;font-size:15px;margin-bottom:4px;\">IT Setup Guide</div>",
      "<div style=\"font-size:13px;color:#605e5c;\">Laptop configuration, email setup, VPN access, and software requests</div></div>",
      "</div>",
      "<div style=\"padding:16px;background:#faf9f8;border-radius:8px;border-left:4px solid #0078d4;\">",
      "<strong>\uD83D\uDCA1 Tip:</strong> Bookmark this page! It's your one-stop hub for all Contoso resources. Updated weekly by the Communications team.",
      "</div>",
    ].join(""),
    audienceTarget: { enabled: false, groups: [], matchAll: false },
    sortOrder: 0,
    enabled: true,
  },
  {
    id: "sample-company-policies",
    title: "Company Policies",
    icon: { type: "emoji", value: "\uD83D\uDCDC" },
    badge: { type: "count", value: "3", color: "#0078d4" },
    contentType: "simple",
    content: [
      "<h3 style=\"margin-bottom:16px;\">\uD83D\uDCDC Company Policies</h3>",
      "<p style=\"margin-bottom:16px;\">All company policies are maintained in the SharePoint Policy Center. Key policies include:</p>",
      "<div style=\"display:flex;flex-direction:column;gap:12px;margin-bottom:20px;\">",
      "<div style=\"display:flex;align-items:center;gap:12px;padding:12px 16px;background:#faf9f8;border-radius:8px;border-left:3px solid #0078d4;\">",
      "<span style=\"font-size:20px;\">\uD83D\uDCCB</span>",
      "<div><strong>Code of Conduct</strong><div style=\"font-size:13px;color:#605e5c;\">Updated Jan 2026 \u2022 Applies to all employees</div></div></div>",
      "<div style=\"display:flex;align-items:center;gap:12px;padding:12px 16px;background:#faf9f8;border-radius:8px;border-left:3px solid #107c10;\">",
      "<span style=\"font-size:20px;\">\uD83C\uDFE0</span>",
      "<div><strong>Remote Work Policy</strong><div style=\"font-size:13px;color:#605e5c;\">Updated Dec 2025 \u2022 Hybrid & remote guidelines</div></div></div>",
      "<div style=\"display:flex;align-items:center;gap:12px;padding:12px 16px;background:#faf9f8;border-radius:8px;border-left:3px solid #ff8c00;\">",
      "<span style=\"font-size:20px;\">\u2708\uFE0F</span>",
      "<div><strong>Travel & Expense Policy</strong><div style=\"font-size:13px;color:#605e5c;\">Updated Nov 2025 \u2022 Per diem rates & reimbursement</div></div></div>",
      "<div style=\"display:flex;align-items:center;gap:12px;padding:12px 16px;background:#faf9f8;border-radius:8px;border-left:3px solid #a80000;\">",
      "<span style=\"font-size:20px;\">\uD83D\uDD12</span>",
      "<div><strong>Information Security Policy</strong><div style=\"font-size:13px;color:#605e5c;\">Updated Feb 2026 \u2022 Data classification & handling</div></div></div>",
      "<div style=\"display:flex;align-items:center;gap:12px;padding:12px 16px;background:#faf9f8;border-radius:8px;border-left:3px solid #8764b8;\">",
      "<span style=\"font-size:20px;\">\uD83D\uDEE1\uFE0F</span>",
      "<div><strong>Data Privacy Policy</strong><div style=\"font-size:13px;color:#605e5c;\">Updated Jan 2026 \u2022 GDPR & CCPA compliance</div></div></div>",
      "</div>",
      "<p style=\"font-size:13px;color:#605e5c;\"><strong>Last updated:</strong> February 2026 &nbsp; <strong>Owner:</strong> Legal & Compliance</p>",
    ].join(""),
    audienceTarget: { enabled: false, groups: [], matchAll: false },
    sortOrder: 1,
    enabled: true,
  },
  {
    id: "sample-it-resources",
    title: "IT Resources",
    icon: { type: "emoji", value: "\uD83D\uDCBB" },
    contentType: "simple",
    content: [
      "<h3 style=\"margin-bottom:16px;\">\uD83D\uDCBB IT Resources & Support</h3>",
      "<div style=\"display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:20px;\">",
      "<div style=\"padding:16px;background:#deecf9;border-radius:8px;\">",
      "<div style=\"font-weight:700;margin-bottom:8px;\">\uD83D\uDD11 VPN Access</div>",
      "<p style=\"font-size:13px;margin:0;\">Download GlobalProtect from the IT portal. Use your AD credentials. Contact IT if 2FA is not working.</p></div>",
      "<div style=\"padding:16px;background:#dff6dd;border-radius:8px;\">",
      "<div style=\"font-weight:700;margin-bottom:8px;\">\uD83D\uDCE7 Email Setup</div>",
      "<p style=\"font-size:13px;margin:0;\">Outlook is pre-configured on company laptops. For mobile, use the Outlook app with your @contoso.com credentials.</p></div>",
      "<div style=\"padding:16px;background:#fff4ce;border-radius:8px;\">",
      "<div style=\"font-weight:700;margin-bottom:8px;\">\uD83D\uDCE6 Software Requests</div>",
      "<p style=\"font-size:13px;margin:0;\">Submit requests via the IT Service Portal. Most approved software is installed within 24 hours.</p></div>",
      "<div style=\"padding:16px;background:#fde7e9;border-radius:8px;\">",
      "<div style=\"font-weight:700;margin-bottom:8px;\">\uD83C\uDD98 IT Help Desk</div>",
      "<p style=\"font-size:13px;margin:0;\">Call x4357 or email helpdesk@contoso.com. Average response time: 2 hours (business hours).</p></div>",
      "</div>",
      "<div style=\"padding:16px;background:#faf9f8;border-radius:8px;border-left:4px solid #ff8c00;\">",
      "<strong>\u26A0\uFE0F Reminder:</strong> Never share your password. IT will never ask for it. Report phishing emails to security@contoso.com.",
      "</div>",
    ].join(""),
    audienceTarget: { enabled: false, groups: [], matchAll: false },
    sortOrder: 2,
    enabled: true,
  },
  {
    id: "sample-hr-benefits",
    title: "HR Benefits",
    icon: { type: "emoji", value: "\u2764\uFE0F" },
    badge: { type: "dot", value: "", color: "#ff8c00" },
    contentType: "simple",
    content: [
      "<h3 style=\"margin-bottom:16px;\">\u2764\uFE0F Benefits & Perks</h3>",
      "<p style=\"margin-bottom:16px;\">Contoso offers a comprehensive benefits package. Open enrollment is in November each year.</p>",
      "<table style=\"width:100%;border-collapse:collapse;margin-bottom:20px;\">",
      "<thead><tr style=\"background:#0a1628;color:#fff;\">",
      "<th style=\"padding:10px 16px;text-align:left;font-size:13px;\">Benefit</th>",
      "<th style=\"padding:10px 16px;text-align:left;font-size:13px;\">Coverage</th>",
      "<th style=\"padding:10px 16px;text-align:left;font-size:13px;\">Company Match</th></tr></thead>",
      "<tbody>",
      "<tr style=\"border-bottom:1px solid #edebe9;\"><td style=\"padding:10px 16px;font-size:13px;\">Health Insurance</td><td style=\"padding:10px 16px;font-size:13px;\">PPO & HMO plans</td><td style=\"padding:10px 16px;font-size:13px;\">80% premium</td></tr>",
      "<tr style=\"border-bottom:1px solid #edebe9;background:#faf9f8;\"><td style=\"padding:10px 16px;font-size:13px;\">Dental</td><td style=\"padding:10px 16px;font-size:13px;\">Preventive + Major</td><td style=\"padding:10px 16px;font-size:13px;\">100% preventive</td></tr>",
      "<tr style=\"border-bottom:1px solid #edebe9;\"><td style=\"padding:10px 16px;font-size:13px;\">Vision</td><td style=\"padding:10px 16px;font-size:13px;\">Annual exam + frames</td><td style=\"padding:10px 16px;font-size:13px;\">$200 allowance</td></tr>",
      "<tr style=\"border-bottom:1px solid #edebe9;background:#faf9f8;\"><td style=\"padding:10px 16px;font-size:13px;\">401(k)</td><td style=\"padding:10px 16px;font-size:13px;\">Immediate vesting</td><td style=\"padding:10px 16px;font-size:13px;\">6% match</td></tr>",
      "<tr><td style=\"padding:10px 16px;font-size:13px;\">PTO</td><td style=\"padding:10px 16px;font-size:13px;\">Unlimited</td><td style=\"padding:10px 16px;font-size:13px;\">Minimum 15 days/year</td></tr>",
      "</tbody></table>",
      "<p style=\"font-size:13px;color:#605e5c;\"><strong>Questions?</strong> Email benefits@contoso.com or visit the HR portal.</p>",
    ].join(""),
    audienceTarget: { enabled: false, groups: [], matchAll: false },
    sortOrder: 3,
    enabled: true,
  },
  {
    id: "sample-office-locations",
    title: "Office Locations",
    icon: { type: "emoji", value: "\uD83C\uDFE2" },
    contentType: "simple",
    content: [
      "<h3 style=\"margin-bottom:16px;\">\uD83C\uDFE2 Office Locations</h3>",
      "<div style=\"display:grid;grid-template-columns:1fr 1fr 1fr;gap:16px;margin-bottom:20px;\">",
      "<div style=\"padding:20px;background:linear-gradient(135deg,#0a1628,#1a3a6a);color:#fff;border-radius:12px;\">",
      "<div style=\"font-weight:700;font-size:16px;margin-bottom:8px;\">\uD83C\uDDFA\uD83C\uDDF8 Headquarters</div>",
      "<div style=\"font-size:14px;opacity:.9;margin-bottom:4px;\">1 Microsoft Way</div>",
      "<div style=\"font-size:13px;opacity:.7;\">Redmond, WA 98052</div>",
      "<div style=\"font-size:13px;opacity:.7;margin-top:8px;\">2,500 employees</div></div>",
      "<div style=\"padding:20px;background:linear-gradient(135deg,#1a3a6a,#0078d4);color:#fff;border-radius:12px;\">",
      "<div style=\"font-weight:700;font-size:16px;margin-bottom:8px;\">\uD83C\uDDEC\uD83C\uDDE7 London Office</div>",
      "<div style=\"font-size:14px;opacity:.9;margin-bottom:4px;\">2 Kingdom Street</div>",
      "<div style=\"font-size:13px;opacity:.7;\">London W2 6BD, UK</div>",
      "<div style=\"font-size:13px;opacity:.7;margin-top:8px;\">800 employees</div></div>",
      "<div style=\"padding:20px;background:linear-gradient(135deg,#0078d4,#00b7c3);color:#fff;border-radius:12px;\">",
      "<div style=\"font-weight:700;font-size:16px;margin-bottom:8px;\">\uD83C\uDDEF\uD83C\uDDF5 Tokyo Office</div>",
      "<div style=\"font-size:14px;opacity:.9;margin-bottom:4px;\">Shinagawa Grand Central Tower</div>",
      "<div style=\"font-size:13px;opacity:.7;\">Minato-ku, Tokyo 108-0075</div>",
      "<div style=\"font-size:13px;opacity:.7;margin-top:8px;\">450 employees</div></div>",
      "</div>",
      "<p style=\"font-size:13px;color:#605e5c;\">For visitor badges, parking, and room reservations, contact the local facilities team.</p>",
    ].join(""),
    audienceTarget: { enabled: false, groups: [], matchAll: false },
    sortOrder: 4,
    enabled: true,
  },
  {
    id: "sample-quick-links",
    title: "Quick Links",
    icon: { type: "emoji", value: "\uD83D\uDD17" },
    contentType: "simple",
    content: [
      "<h3 style=\"margin-bottom:16px;\">\uD83D\uDD17 Quick Links</h3>",
      "<div style=\"display:grid;grid-template-columns:1fr 1fr;gap:12px;\">",
      "<a style=\"display:flex;align-items:center;gap:12px;padding:12px 16px;background:#faf9f8;border-radius:8px;text-decoration:none;color:#323130;border:1px solid #edebe9;\">",
      "<span style=\"font-size:24px;\">\uD83D\uDCCA</span>",
      "<div><strong>Power BI Dashboard</strong><div style=\"font-size:12px;color:#605e5c;\">Business intelligence & reports</div></div></a>",
      "<a style=\"display:flex;align-items:center;gap:12px;padding:12px 16px;background:#faf9f8;border-radius:8px;text-decoration:none;color:#323130;border:1px solid #edebe9;\">",
      "<span style=\"font-size:24px;\">\uD83D\uDDD3\uFE0F</span>",
      "<div><strong>Room Reservations</strong><div style=\"font-size:12px;color:#605e5c;\">Book meeting rooms & hot desks</div></div></a>",
      "<a style=\"display:flex;align-items:center;gap:12px;padding:12px 16px;background:#faf9f8;border-radius:8px;text-decoration:none;color:#323130;border:1px solid #edebe9;\">",
      "<span style=\"font-size:24px;\">\uD83C\uDF93</span>",
      "<div><strong>Learning Management</strong><div style=\"font-size:12px;color:#605e5c;\">Viva Learning courses & certifications</div></div></a>",
      "<a style=\"display:flex;align-items:center;gap:12px;padding:12px 16px;background:#faf9f8;border-radius:8px;text-decoration:none;color:#323130;border:1px solid #edebe9;\">",
      "<span style=\"font-size:24px;\">\uD83D\uDCDD</span>",
      "<div><strong>Expense Reports</strong><div style=\"font-size:12px;color:#605e5c;\">Submit & track reimbursements</div></div></a>",
      "<a style=\"display:flex;align-items:center;gap:12px;padding:12px 16px;background:#faf9f8;border-radius:8px;text-decoration:none;color:#323130;border:1px solid #edebe9;\">",
      "<span style=\"font-size:24px;\">\uD83D\uDC65</span>",
      "<div><strong>Employee Directory</strong><div style=\"font-size:12px;color:#605e5c;\">Find anyone at Contoso</div></div></a>",
      "<a style=\"display:flex;align-items:center;gap:12px;padding:12px 16px;background:#faf9f8;border-radius:8px;text-decoration:none;color:#323130;border:1px solid #edebe9;\">",
      "<span style=\"font-size:24px;\">\uD83D\uDCE2</span>",
      "<div><strong>Yammer Communities</strong><div style=\"font-size:12px;color:#605e5c;\">Join discussions & company news</div></div></a>",
      "</div>",
    ].join(""),
    audienceTarget: { enabled: false, groups: [], matchAll: false },
    sortOrder: 5,
    enabled: true,
  },
];
