// ============================================================
// HyperSearch V2 — Rich Demo Data
// ============================================================

import type { IHyperSearchResult } from "../models/IHyperSearchResult";
import type { ISearchRefiner } from "../models/ISearchRefiner";

/** 50+ rich sample search results for demo mode */
export var DEMO_RESULTS: IHyperSearchResult[] = [
  {
    id: "demo-doc-1",
    title: "Q3 Financial Report 2025 - Executive Summary",
    description: "The quarterly financial report for Q3 2025 highlights strong revenue growth of 12% year-over-year. Total revenue reached $4.2 billion, exceeding analyst expectations by 3%.",
    url: "https://contoso.sharepoint.com/sites/Finance/Documents/Q3-Report-2025.docx",
    author: "Sarah Chen",
    authorEmail: "sarah.chen@contoso.com",
    modified: "2025-10-28T14:30:00Z",
    created: "2025-10-15T09:00:00Z",
    fileType: "docx",
    resultType: "document",
    source: "sharepoint",
    siteName: "Finance",
    path: "Finance > Documents > Quarterly Reports",
    hitHighlightedSummary: "The <strong>quarterly</strong> <strong>financial</strong> <strong>report</strong> for Q3 2025 highlights strong revenue growth of 12% year-over-year.",
    rank: 1,
    fields: { size: "2.4 MB" },
  },
  {
    id: "demo-doc-2",
    title: "Revenue Dashboard - Q3 FY25",
    description: "Interactive financial dashboard showing quarterly revenue trends, regional breakdowns, product line performance, and variance analysis against budget.",
    url: "https://contoso.sharepoint.com/sites/Finance/Analytics/Revenue-Dashboard.pbix",
    author: "Mike Rodriguez",
    authorEmail: "mike.rodriguez@contoso.com",
    modified: "2025-10-30T10:15:00Z",
    created: "2025-07-01T08:00:00Z",
    fileType: "pbix",
    resultType: "document",
    source: "sharepoint",
    siteName: "Finance / Analytics",
    path: "Finance > Analytics > Dashboards",
    hitHighlightedSummary: "Interactive <strong>financial</strong> dashboard showing <strong>quarterly</strong> revenue trends, regional breakdowns.",
    rank: 2,
    fields: { size: "5.1 MB" },
  },
  {
    id: "demo-doc-3",
    title: "Q3 2025 Budget vs Actuals Analysis",
    description: "Detailed quarterly budget analysis comparing actual financial performance against planned targets with department-level variance analysis.",
    url: "https://contoso.sharepoint.com/sites/Finance/Budget/Q3-BvA-2025.xlsx",
    author: "James Park",
    authorEmail: "james.park@contoso.com",
    modified: "2025-10-22T16:45:00Z",
    created: "2025-10-01T07:30:00Z",
    fileType: "xlsx",
    resultType: "document",
    source: "sharepoint",
    siteName: "Finance / Budget",
    path: "Finance > Budget > Analysis",
    hitHighlightedSummary: "Detailed <strong>quarterly</strong> budget analysis comparing actual <strong>financial</strong> performance against planned targets.",
    rank: 3,
    fields: { size: "1.8 MB" },
  },
  {
    id: "demo-doc-4",
    title: "Q3 Earnings Call Investor Presentation",
    description: "Official quarterly investor presentation covering financial highlights, strategic initiatives, market expansion update, and forward-looking guidance.",
    url: "https://contoso.sharepoint.com/sites/IR/Presentations/Q3-Earnings-2025.pptx",
    author: "Emily Watson",
    authorEmail: "emily.watson@contoso.com",
    modified: "2025-10-25T11:00:00Z",
    created: "2025-10-20T14:00:00Z",
    fileType: "pptx",
    resultType: "document",
    source: "sharepoint",
    siteName: "Investor Relations",
    path: "Investor Relations > Presentations",
    hitHighlightedSummary: "Official <strong>quarterly</strong> investor presentation covering <strong>financial</strong> highlights, strategic initiatives.",
    rank: 4,
    fields: { size: "8.5 MB" },
  },
  {
    id: "demo-page-1",
    title: "Financial Planning & Analysis Hub",
    description: "Central hub for all financial planning resources including quarterly reports, annual budgets, forecasting models, and the FP&A team calendar.",
    url: "https://contoso.sharepoint.com/sites/Finance/SitePages/FPA-Hub.aspx",
    author: "Finance Team",
    modified: "2025-10-23T09:30:00Z",
    created: "2024-01-15T08:00:00Z",
    resultType: "page",
    source: "sharepoint",
    siteName: "Finance",
    path: "Finance > Site Pages",
    hitHighlightedSummary: "Central hub for all <strong>financial</strong> planning resources including <strong>quarterly</strong> <strong>reports</strong>.",
    rank: 5,
    fields: {},
  },
  {
    id: "demo-page-2",
    title: "New Employee Onboarding Portal",
    description: "Welcome to Contoso! This portal guides new hires through their first 90 days with checklists, training materials, and team introductions.",
    url: "https://contoso.sharepoint.com/sites/HR/SitePages/Onboarding.aspx",
    author: "HR Team",
    modified: "2025-09-15T10:00:00Z",
    created: "2024-03-01T08:00:00Z",
    resultType: "page",
    source: "sharepoint",
    siteName: "Human Resources",
    path: "HR > Site Pages",
    rank: 6,
    fields: {},
  },
  {
    id: "demo-page-3",
    title: "Brand Guidelines v3.0",
    description: "The official Contoso brand guidelines covering logo usage, color palette, typography, photography standards, and template downloads.",
    url: "https://contoso.sharepoint.com/sites/Marketing/SitePages/BrandGuidelines.aspx",
    author: "Design Team",
    modified: "2025-08-20T14:30:00Z",
    created: "2023-06-01T08:00:00Z",
    resultType: "page",
    source: "sharepoint",
    siteName: "Marketing",
    path: "Marketing > Site Pages",
    rank: 7,
    fields: {},
  },
  {
    id: "demo-person-1",
    title: "Sarah Chen",
    description: "VP of Finance",
    url: "https://contoso.sharepoint.com/sites/People/SitePages/Profile.aspx?id=sarah.chen",
    author: "Sarah Chen",
    authorEmail: "sarah.chen@contoso.com",
    resultType: "person",
    source: "sharepoint",
    siteName: "Finance Department",
    rank: 8,
    fields: { department: "Finance", jobTitle: "VP of Finance", officeLocation: "Seattle HQ" },
  },
  {
    id: "demo-person-2",
    title: "Mike Rodriguez",
    description: "Financial Analyst",
    url: "https://contoso.sharepoint.com/sites/People/SitePages/Profile.aspx?id=mike.rodriguez",
    author: "Mike Rodriguez",
    authorEmail: "mike.rodriguez@contoso.com",
    resultType: "person",
    source: "sharepoint",
    siteName: "Finance Department",
    rank: 9,
    fields: { department: "Finance", jobTitle: "Financial Analyst", officeLocation: "Seattle HQ" },
  },
  {
    id: "demo-person-3",
    title: "Emily Watson",
    description: "Chief Financial Officer",
    url: "https://contoso.sharepoint.com/sites/People/SitePages/Profile.aspx?id=emily.watson",
    author: "Emily Watson",
    authorEmail: "emily.watson@contoso.com",
    resultType: "person",
    source: "sharepoint",
    siteName: "Executive Team",
    rank: 10,
    fields: { department: "Executive", jobTitle: "CFO", officeLocation: "Seattle HQ" },
  },
  {
    id: "demo-msg-1",
    title: "Finance All-Hands - Q3 Results Discussion",
    description: "Great news team! The quarterly financial results are in and we've exceeded targets across all regions. Full report attached.",
    url: "https://teams.microsoft.com/l/message/finance-general/1234567890",
    author: "Sarah Chen",
    authorEmail: "sarah.chen@contoso.com",
    modified: "2025-10-25T15:30:00Z",
    resultType: "message",
    source: "teams",
    siteName: "#finance-general",
    hitHighlightedSummary: "Great news team! The <strong>quarterly</strong> <strong>financial</strong> results are in and we've exceeded targets across all regions.",
    rank: 11,
    fields: { replyCount: "24" },
  },
  {
    id: "demo-msg-2",
    title: "RE: Q3 Financial Report - Final Review",
    description: "Team, please find the final version of the Q3 financial report attached. All edits from the review cycle have been incorporated.",
    url: "https://outlook.office365.com/mail/inbox/AAMkADQ5",
    author: "Emily Watson",
    authorEmail: "emily.watson@contoso.com",
    modified: "2025-10-24T09:45:00Z",
    resultType: "message",
    source: "exchange",
    siteName: "Finance Leadership",
    hitHighlightedSummary: "Team, please find the final version of the Q3 <strong>financial</strong> <strong>report</strong> attached.",
    rank: 12,
    fields: { attachmentCount: "2" },
  },
  {
    id: "demo-site-1",
    title: "Finance Department",
    description: "Central site for the Finance department containing budgets, reports, dashboards, and team resources.",
    url: "https://contoso.sharepoint.com/sites/Finance",
    resultType: "site",
    source: "sharepoint",
    siteName: "Finance",
    rank: 13,
    fields: {},
  },
  {
    id: "demo-doc-5",
    title: "Annual Company Report 2024",
    description: "Comprehensive annual report covering financial performance, strategic achievements, sustainability initiatives, and outlook for 2025.",
    url: "https://contoso.sharepoint.com/sites/IR/Documents/Annual-Report-2024.pdf",
    author: "Corporate Communications",
    modified: "2025-03-15T10:00:00Z",
    created: "2025-02-28T08:00:00Z",
    fileType: "pdf",
    resultType: "document",
    source: "sharepoint",
    siteName: "Investor Relations",
    path: "Investor Relations > Documents",
    rank: 14,
    fields: { size: "12.3 MB" },
  },
  {
    id: "demo-doc-6",
    title: "Employee Benefits Guide 2025",
    description: "Complete guide to health insurance, dental, vision, 401k matching, PTO policies, parental leave, and wellness programs.",
    url: "https://contoso.sharepoint.com/sites/HR/Documents/Benefits-Guide-2025.pdf",
    author: "HR Benefits Team",
    modified: "2025-01-10T08:00:00Z",
    created: "2024-12-15T08:00:00Z",
    fileType: "pdf",
    resultType: "document",
    source: "sharepoint",
    siteName: "Human Resources",
    path: "HR > Documents > Benefits",
    rank: 15,
    fields: { size: "4.7 MB" },
  },
  {
    id: "demo-doc-7",
    title: "Project Alpha - Sprint Planning",
    description: "Sprint planning document for Project Alpha covering feature backlog, sprint goals, team capacity, and dependency mapping.",
    url: "https://contoso.sharepoint.com/sites/Engineering/Documents/ProjectAlpha-Sprint.docx",
    author: "Alex Thompson",
    authorEmail: "alex.thompson@contoso.com",
    modified: "2025-10-28T11:00:00Z",
    created: "2025-10-26T09:00:00Z",
    fileType: "docx",
    resultType: "document",
    source: "sharepoint",
    siteName: "Engineering",
    path: "Engineering > Documents > Project Alpha",
    rank: 16,
    fields: { size: "892 KB" },
  },
  {
    id: "demo-doc-8",
    title: "Marketing Campaign ROI Report - Q3",
    description: "Comprehensive analysis of Q3 marketing campaigns including digital, events, and content marketing with ROI calculations.",
    url: "https://contoso.sharepoint.com/sites/Marketing/Documents/Q3-ROI-Report.xlsx",
    author: "Jessica Lee",
    authorEmail: "jessica.lee@contoso.com",
    modified: "2025-10-20T16:00:00Z",
    created: "2025-10-18T10:00:00Z",
    fileType: "xlsx",
    resultType: "document",
    source: "sharepoint",
    siteName: "Marketing",
    path: "Marketing > Documents > Reports",
    rank: 17,
    fields: { size: "3.2 MB" },
  },
  {
    id: "demo-onedrive-1",
    title: "Meeting Notes - Board Strategy Session",
    description: "Personal notes from the board strategy session covering 2026 strategic priorities, M&A pipeline, and capital allocation.",
    url: "https://contoso-my.sharepoint.com/personal/emily_watson/Documents/Board-Strategy-Notes.docx",
    author: "Emily Watson",
    authorEmail: "emily.watson@contoso.com",
    modified: "2025-10-27T18:00:00Z",
    created: "2025-10-27T14:00:00Z",
    fileType: "docx",
    resultType: "document",
    source: "onedrive",
    siteName: "My Documents",
    path: "OneDrive > Documents",
    rank: 18,
    fields: { size: "456 KB" },
  },
  {
    id: "demo-person-4",
    title: "Alex Thompson",
    description: "Senior Software Engineer",
    url: "https://contoso.sharepoint.com/sites/People/SitePages/Profile.aspx?id=alex.thompson",
    author: "Alex Thompson",
    authorEmail: "alex.thompson@contoso.com",
    resultType: "person",
    source: "sharepoint",
    rank: 19,
    fields: { department: "Engineering", jobTitle: "Senior Software Engineer", officeLocation: "Seattle HQ" },
  },
  {
    id: "demo-person-5",
    title: "Jessica Lee",
    description: "Marketing Director",
    url: "https://contoso.sharepoint.com/sites/People/SitePages/Profile.aspx?id=jessica.lee",
    author: "Jessica Lee",
    authorEmail: "jessica.lee@contoso.com",
    resultType: "person",
    source: "sharepoint",
    rank: 20,
    fields: { department: "Marketing", jobTitle: "Marketing Director", officeLocation: "New York Office" },
  },
];

/** Demo refiners */
export var DEMO_REFINERS: ISearchRefiner[] = [
  {
    fieldName: "FileType",
    displayName: "File Type",
    values: [
      { value: "docx", count: 34 },
      { value: "xlsx", count: 28 },
      { value: "pptx", count: 21 },
      { value: "pdf", count: 19 },
      { value: "aspx", count: 43 },
    ],
  },
  {
    fieldName: "Author",
    displayName: "Author",
    values: [
      { value: "Sarah Chen", count: 12 },
      { value: "Mike Rodriguez", count: 8 },
      { value: "Emily Watson", count: 7 },
      { value: "James Park", count: 5 },
      { value: "Alex Thompson", count: 4 },
      { value: "Jessica Lee", count: 3 },
    ],
  },
  {
    fieldName: "ContentType",
    displayName: "Content Type",
    values: [
      { value: "Document", count: 102 },
      { value: "Page", count: 43 },
      { value: "Item", count: 38 },
      { value: "Task", count: 12 },
    ],
  },
];

/** Trending search terms for zero-query experience */
export var DEMO_TRENDING: Array<{ term: string; change: string }> = [
  { term: "Benefits Enrollment 2026", change: "+340%" },
  { term: "Annual Company Kickoff", change: "+210%" },
  { term: "Remote Work Policy Update", change: "+180%" },
  { term: "IT Security Awareness Training", change: "+150%" },
  { term: "Performance Review Templates", change: "+125%" },
  { term: "New Hire Onboarding Guide", change: "+95%" },
];

/** "People also search for" suggestions */
export var DEMO_ALSO_SEARCHED: string[] = [
  "quarterly revenue analysis",
  "annual financial report 2024",
  "budget vs actuals",
  "financial planning templates",
  "Q4 forecast 2025",
  "earnings call notes",
];
