// ============================================================
// HyperSearch V2 — Template Definitions
// ============================================================

import type { ISearchTemplate } from "../models/IHyperSearchV2";

export var SEARCH_TEMPLATES: ISearchTemplate[] = [
  {
    id: "modern-clean",
    name: "Modern Clean",
    icon: "\u2728",
    color: "#0078d4",
    category: "modern",
    description: "Minimal, elegant search with rounded corners and subtle shadows",
    configuration: {
      resultLayout: "listRich",
      searchBarStyle: "rounded",
      accentColor: "#0078d4",
      borderRadius: 8,
      showScopeTabs: true,
      features: {
        instantSearch: true,
        smartAutocomplete: true,
        searchVerticals: true,
        zeroQuery: true,
        spellingCorrection: true,
        nlpParsing: false,
        savedSearches: true,
        commandPalette: false,
        inlinePreview: true,
        peopleCards: true,
        quickActions: true,
        hitHighlight: true,
        resultGrouping: false,
        thumbnailPreviews: true,
      },
    },
  },
  {
    id: "corporate-pro",
    name: "Corporate Pro",
    icon: "\uD83C\uDFE2",
    color: "#106ebe",
    category: "classic",
    description: "Professional enterprise search with structured layout",
    configuration: {
      resultLayout: "listRich",
      searchBarStyle: "square",
      accentColor: "#106ebe",
      borderRadius: 4,
      showScopeTabs: true,
    },
  },
  {
    id: "google-style",
    name: "Google-Style",
    icon: "\uD83D\uDD0D",
    color: "#4285f4",
    category: "modern",
    description: "Familiar centered search bar with clean result cards",
    configuration: {
      resultLayout: "listRich",
      searchBarStyle: "pill",
      accentColor: "#4285f4",
      borderRadius: 24,
      showScopeTabs: true,
    },
  },
  {
    id: "command-palette",
    name: "Command Palette",
    icon: "\u2328\uFE0F",
    color: "#6b21a8",
    category: "modern",
    description: "Cmd+K style floating search overlay like Spotlight",
    configuration: {
      resultLayout: "listCompact",
      searchBarStyle: "rounded",
      accentColor: "#6b21a8",
      borderRadius: 12,
      features: {
        instantSearch: true,
        smartAutocomplete: true,
        searchVerticals: false,
        zeroQuery: true,
        spellingCorrection: true,
        nlpParsing: false,
        savedSearches: false,
        commandPalette: true,
        inlinePreview: false,
        peopleCards: true,
        quickActions: false,
        hitHighlight: true,
        resultGrouping: false,
        thumbnailPreviews: false,
      },
    },
  },
  {
    id: "magazine",
    name: "Magazine Layout",
    icon: "\uD83D\uDCF0",
    color: "#d83b01",
    category: "creative",
    description: "Rich visual grid with thumbnails and featured results",
    configuration: {
      resultLayout: "magazine",
      searchBarStyle: "rounded",
      accentColor: "#d83b01",
      borderRadius: 8,
      showScopeTabs: true,
      features: {
        instantSearch: true,
        smartAutocomplete: true,
        searchVerticals: true,
        zeroQuery: true,
        spellingCorrection: true,
        nlpParsing: false,
        savedSearches: true,
        commandPalette: false,
        inlinePreview: true,
        peopleCards: true,
        quickActions: true,
        hitHighlight: true,
        resultGrouping: true,
        thumbnailPreviews: true,
      },
    },
  },
  {
    id: "dark-mode",
    name: "Dark Mode",
    icon: "\uD83C\uDF19",
    color: "#1a1a2e",
    category: "creative",
    description: "Sleek dark theme for modern intranets",
    configuration: {
      resultLayout: "cardGrid",
      searchBarStyle: "rounded",
      accentColor: "#4fc3f7",
      borderRadius: 8,
      showScopeTabs: true,
    },
  },
  {
    id: "compact-list",
    name: "Compact List",
    icon: "\uD83D\uDCCB",
    color: "#107c10",
    category: "classic",
    description: "Dense information-rich list, maximum results per page",
    configuration: {
      resultLayout: "listCompact",
      searchBarStyle: "square",
      accentColor: "#107c10",
      borderRadius: 4,
      resultsPerPage: 25,
      showScopeTabs: true,
    },
  },
  {
    id: "sharepoint-native",
    name: "SharePoint Native",
    icon: "\uD83D\uDFE6",
    color: "#0078d4",
    category: "classic",
    description: "Mimics native SharePoint search with enhanced features",
    configuration: {
      resultLayout: "listRich",
      searchBarStyle: "square",
      accentColor: "#0078d4",
      borderRadius: 2,
      showScopeTabs: true,
    },
  },
  {
    id: "card-gallery",
    name: "Card Gallery",
    icon: "\uD83D\uDDBC\uFE0F",
    color: "#0097a7",
    category: "creative",
    description: "Pinterest-style masonry cards with large thumbnails",
    configuration: {
      resultLayout: "cardGrid",
      searchBarStyle: "rounded",
      accentColor: "#0097a7",
      borderRadius: 12,
      showScopeTabs: true,
    },
  },
  {
    id: "teams-style",
    name: "Teams Style",
    icon: "\uD83D\uDCAC",
    color: "#6264a7",
    category: "modern",
    description: "Matches Microsoft Teams aesthetic for unified experience",
    configuration: {
      resultLayout: "listRich",
      searchBarStyle: "rounded",
      accentColor: "#6264a7",
      borderRadius: 4,
      showScopeTabs: true,
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    icon: "\u25EF",
    color: "#605e5c",
    category: "classic",
    description: "Ultra-clean with zero distractions, pure content focus",
    configuration: {
      resultLayout: "listCompact",
      searchBarStyle: "underline",
      accentColor: "#605e5c",
      borderRadius: 0,
      showScopeTabs: false,
      features: {
        instantSearch: true,
        smartAutocomplete: false,
        searchVerticals: false,
        zeroQuery: false,
        spellingCorrection: true,
        nlpParsing: false,
        savedSearches: false,
        commandPalette: false,
        inlinePreview: false,
        peopleCards: false,
        quickActions: false,
        hitHighlight: true,
        resultGrouping: false,
        thumbnailPreviews: false,
      },
    },
  },
  {
    id: "ai-assistant",
    name: "AI Assistant",
    icon: "\uD83E\uDD16",
    color: "#7c3aed",
    category: "modern",
    description: "Conversational search with AI summaries and suggestions",
    configuration: {
      resultLayout: "listRich",
      searchBarStyle: "pill",
      accentColor: "#7c3aed",
      borderRadius: 16,
      showScopeTabs: true,
      features: {
        instantSearch: true,
        smartAutocomplete: true,
        searchVerticals: true,
        zeroQuery: true,
        spellingCorrection: true,
        nlpParsing: true,
        savedSearches: true,
        commandPalette: true,
        inlinePreview: true,
        peopleCards: true,
        quickActions: true,
        hitHighlight: true,
        resultGrouping: true,
        thumbnailPreviews: true,
      },
    },
  },
];

/** Find a template by ID */
export function getSearchTemplateById(id: string): ISearchTemplate | undefined {
  var result: ISearchTemplate | undefined;
  SEARCH_TEMPLATES.forEach(function (t) {
    if (t.id === id) result = t;
  });
  return result;
}
