import type { IHyperSpotlightEmployee } from "../models";
import { SpotlightCategory } from "../models";

/**
 * 8 sample employees for preview/demo mode.
 * Covers all 7 categories, multiple departments, personal fields, and varied data.
 * Used when `useSampleData` is enabled in the property pane.
 */
export function generateMockEmployees(): IHyperSpotlightEmployee[] {
  return [
    {
      id: "mock-001",
      userPrincipalName: "alex.johnson@contoso.com",
      displayName: "Alex Johnson",
      givenName: "Alex",
      surname: "Johnson",
      mail: "alex.johnson@contoso.com",
      jobTitle: "Senior Software Engineer",
      department: "Engineering",
      officeLocation: "Building A, Floor 3",
      hireDate: "2019-03-15",
      nickname: "AJ",
      personalQuote: "Code is poetry, and I'm writing an epic.",
      hobbies: ["Coding", "Rock Climbing", "Photography"],
      skillset: ["TypeScript", "React", "Azure", "Node.js"],
      favoriteWebsites: [
        { url: "https://github.com", title: "GitHub" },
        { url: "https://stackoverflow.com", title: "Stack Overflow" },
      ],
      assignedCategory: SpotlightCategory.Achievement,
      yearsOfService: 6,
      photoUrl: undefined,
    },
    {
      id: "mock-002",
      userPrincipalName: "maria.garcia@contoso.com",
      displayName: "Maria Garcia",
      givenName: "Maria",
      surname: "Garcia",
      mail: "maria.garcia@contoso.com",
      jobTitle: "Product Manager",
      department: "Product",
      officeLocation: "Building B, Floor 2",
      hireDate: "2021-06-01",
      nickname: "MG",
      personalQuote: "The best products are built by listening, not just coding.",
      hobbies: ["Travel", "Yoga", "Cooking"],
      skillset: ["Product Strategy", "Agile", "User Research", "Data Analysis"],
      favoriteWebsites: [
        { url: "https://www.producthunt.com", title: "Product Hunt" },
      ],
      assignedCategory: SpotlightCategory.WorkAnniversary,
      yearsOfService: 4,
      photoUrl: undefined,
    },
    {
      id: "mock-003",
      userPrincipalName: "james.wilson@contoso.com",
      displayName: "James Wilson",
      givenName: "James",
      surname: "Wilson",
      mail: "james.wilson@contoso.com",
      jobTitle: "UX Designer",
      department: "Design",
      officeLocation: "Building A, Floor 1",
      hireDate: "2023-01-10",
      personalQuote: "Good design is invisible.",
      hobbies: ["Painting", "Music", "Gaming"],
      skillset: ["Figma", "User Research", "Prototyping", "Design Systems"],
      favoriteWebsites: [
        { url: "https://dribbble.com", title: "Dribbble" },
        { url: "https://www.behance.net", title: "Behance" },
      ],
      assignedCategory: SpotlightCategory.Birthday,
      yearsOfService: 2,
      photoUrl: undefined,
    },
    {
      id: "mock-004",
      userPrincipalName: "sarah.chen@contoso.com",
      displayName: "Sarah Chen",
      givenName: "Sarah",
      surname: "Chen",
      mail: "sarah.chen@contoso.com",
      jobTitle: "Data Scientist",
      department: "Analytics",
      officeLocation: "Building C, Floor 4",
      hireDate: "2020-09-20",
      nickname: "SC",
      personalQuote: "In data we trust, but always verify.",
      hobbies: ["Reading", "Hiking", "Board Games"],
      skillset: ["Python", "Machine Learning", "SQL", "Tableau"],
      favoriteWebsites: [
        { url: "https://kaggle.com", title: "Kaggle" },
      ],
      assignedCategory: SpotlightCategory.Graduation,
      yearsOfService: 5,
      photoUrl: undefined,
    },
    {
      id: "mock-005",
      userPrincipalName: "david.brown@contoso.com",
      displayName: "David Brown",
      givenName: "David",
      surname: "Brown",
      mail: "david.brown@contoso.com",
      jobTitle: "HR Business Partner",
      department: "Human Resources",
      officeLocation: "Building B, Floor 1",
      hireDate: "2017-11-05",
      personalQuote: "People are our greatest asset.",
      hobbies: ["Gardening", "Running", "Travel"],
      skillset: ["Talent Acquisition", "Employee Relations", "Coaching"],
      assignedCategory: SpotlightCategory.Wedding,
      yearsOfService: 8,
      photoUrl: undefined,
    },
    {
      id: "mock-006",
      userPrincipalName: "emma.taylor@contoso.com",
      displayName: "Emma Taylor",
      givenName: "Emma",
      surname: "Taylor",
      mail: "emma.taylor@contoso.com",
      jobTitle: "Marketing Director",
      department: "Marketing",
      officeLocation: "Building A, Floor 5",
      hireDate: "2018-04-22",
      nickname: "ET",
      personalQuote: "Great marketing tells a story people want to share.",
      hobbies: ["Writing", "Fitness", "Film"],
      skillset: ["Brand Strategy", "Content Marketing", "Social Media", "SEO"],
      favoriteWebsites: [
        { url: "https://www.hubspot.com/blog", title: "HubSpot Blog" },
        { url: "https://moz.com", title: "Moz" },
      ],
      assignedCategory: SpotlightCategory.Engagement,
      yearsOfService: 7,
      photoUrl: undefined,
    },
    {
      id: "mock-007",
      userPrincipalName: "raj.patel@contoso.com",
      displayName: "Raj Patel",
      givenName: "Raj",
      surname: "Patel",
      mail: "raj.patel@contoso.com",
      jobTitle: "Cloud Architect",
      department: "Engineering",
      officeLocation: "Building C, Floor 3",
      hireDate: "2022-08-15",
      personalQuote: "The cloud is just someone else's computer... that I manage.",
      hobbies: ["Gaming", "Cooking", "Photography"],
      skillset: ["Azure", "AWS", "Terraform", "Kubernetes", "Docker"],
      favoriteWebsites: [
        { url: "https://learn.microsoft.com", title: "Microsoft Learn" },
      ],
      assignedCategory: SpotlightCategory.Anniversary,
      yearsOfService: 3,
      photoUrl: undefined,
    },
    {
      id: "mock-008",
      userPrincipalName: "lisa.nguyen@contoso.com",
      displayName: "Lisa Nguyen",
      givenName: "Lisa",
      surname: "Nguyen",
      mail: "lisa.nguyen@contoso.com",
      jobTitle: "Finance Manager",
      department: "Finance",
      officeLocation: "Building B, Floor 3",
      hireDate: "2016-02-28",
      nickname: "LN",
      personalQuote: "Numbers tell a story if you know how to read them.",
      hobbies: ["Yoga", "Reading", "Travel"],
      skillset: ["Financial Modeling", "Budgeting", "Forecasting", "Excel"],
      assignedCategory: SpotlightCategory.WorkAnniversary,
      yearsOfService: 9,
      photoUrl: undefined,
    },
  ];
}
