define([], function () {
  return {
    PropertyPaneDescription: "Configure the HyperLinks enhanced quick links web part.",
    LayoutGroupName: "Layout & Appearance",
    LinksGroupName: "Links Management",
    GroupsGroupName: "Group Management",
    FeaturesGroupName: "Features",
    TitleFieldLabel: "Title",
    LayoutModeFieldLabel: "Layout Mode",
    GridColumnsFieldLabel: "Grid Columns",
    TileSizeFieldLabel: "Tile Size",
    IconSizeFieldLabel: "Icon Size",
    ShowIconsLabel: "Show Icons",
    ShowDescriptionsLabel: "Show Descriptions",
    ShowThumbnailsLabel: "Show Thumbnails",
    HoverEffectFieldLabel: "Hover Effect",
    BorderRadiusFieldLabel: "Border Radius",
    CompactAlignmentFieldLabel: "Compact Alignment",
    EnableGroupingLabel: "Enable Link Grouping",
    EnableAudienceTargetingLabel: "Enable Audience Targeting",
    EnableAnalyticsLabel: "Enable Click Analytics",
    EnableColorCustomizationLabel: "Enable Color Customization",
    LinksPageDescription: "Manage quick links. Add, remove, and reorder links.",
    AdvancedPageDescription: "Advanced features and behavior settings.",
    LinkHeaderPrefix: "Link",
    LinkTitleLabel: "Title",
    LinkUrlLabel: "URL",
    LinkDescriptionLabel: "Description",
    LinkIconNameLabel: "Icon Name",
    LinkIconTypeLabel: "Icon Type",
    LinkThumbnailUrlLabel: "Thumbnail URL",
    LinkBackgroundColorLabel: "Background Color",
    LinkOpenInNewTabLabel: "Open in new tab",
    LinkGroupNameLabel: "Group Name",
    MoveUpLabel: "Move Up",
    MoveDownLabel: "Move Down",
    RemoveLinkLabel: "Remove",
    AddLinkLabel: "Add New Link",
    NewLinkDefaultTitle: "New Link",
    GroupsSectionLabel: "Link Groups",
    GroupNameLabel: "Group",
    RemoveGroupLabel: "Remove Group",
    AddGroupLabel: "Add Group",
    NewGroupDefaultName: "Group"
  };
});
