define([], function () {
  return {
    PropertyPaneDescription: "Configure the HyperEvents calendar and events web part.",
    LayoutGroupName: "Layout & Display",
    FeaturesGroupName: "Features",
    DataGroupName: "Data Sources & Storage",
    TitleFieldLabel: "Title",
    ViewModeFieldLabel: "Current View",
    DefaultViewFieldLabel: "Default View",
    RefreshIntervalFieldLabel: "Auto-Refresh Interval (seconds, 0 = off)",
    EnableRsvpLabel: "Enable RSVP",
    EnableRegistrationLabel: "Enable Registration Forms",
    EnableCountdownLabel: "Enable Countdown Timer",
    CountdownEventIdLabel: "Countdown Event ID",
    EnableNotificationsLabel: "Enable Notifications (Email + Teams)",
    EnableCategoryFilterLabel: "Show Category Filter Bar",
    EnableLocationLinksLabel: "Show Location/Map Links",
    EnableVirtualLinksLabel: "Show Teams Meeting Join Links",
    EnablePastArchiveLabel: "Show Past Events Archive",
    ShowCalendarOverlayLabel: "Show Multi-Source Calendar Overlay",
    RsvpListNameLabel: "RSVP List Name",
    RegistrationListNameLabel: "Registration List Name",
    CacheDurationFieldLabel: "Cache Duration (seconds)",
    FeaturesPageDescription: "Toggle event features and capabilities.",
    DataPageDescription: "Configure event data sources and storage lists.",
    ViewModeMonth: "Month",
    ViewModeWeek: "Week",
    ViewModeDay: "Day",
    ViewModeAgenda: "Agenda",
    ViewModeTimeline: "Timeline",
    ViewModeCardGrid: "Card Grid",
    // Source management
    SourcesGroupName: "Event Sources",
    SourceHeaderPrefix: "Source",
    SourceNameLabel: "Display Name",
    SourceTypeLabel: "Source Type",
    SourceColorLabel: "Color",
    SourceListNameLabel: "List Name",
    SourceSiteUrlLabel: "Site URL",
    SourceCalendarIdLabel: "Calendar ID",
    SourceGroupIdLabel: "Group ID",
    SourceEnabledLabel: "Enabled",
    AddSourceLabel: "Add Source",
    RemoveSourceLabel: "Remove",
    NewSourceDefaultName: "New Source",
    MoveUpLabel: "Move Up",
    MoveDownLabel: "Move Down",
    // Category management
    CategoriesGroupName: "Categories",
    CategoriesSectionLabel: "Event Categories",
    CategoryNameLabel: "Category",
    CategoryColorLabel: "Color",
    AddCategoryLabel: "Add Category",
    RemoveCategoryLabel: "Remove",
    NewCategoryDefaultName: "New Category",
    // Registration field management
    RegistrationFieldsGroupName: "Registration Fields",
    RegistrationFieldsSectionLabel: "Form Fields",
    FieldLabelLabel: "Field",
    FieldTypeLabel: "Type",
    FieldOptionsLabel: "Options",
    FieldRequiredLabel: "Required",
    AddFieldLabel: "Add Field",
    RemoveFieldLabel: "Remove",
    NewFieldDefaultLabel: "New Field",
    // Storage
    StorageGroupName: "Storage",
    // Wizard & Demo
    ShowWizardOnInitLabel: "Show Setup Wizard on First Add",
    UseSampleDataLabel: "Use Sample Data",
    DemoModeLabel: "Demo Mode (show demo bar)",
    SetupGroupName: "Setup & Demo"
  };
});
