// ─── Particle Effect Configuration ────────────────────────────────────────────
import type { ParticleShape, ParticleDirection } from "./IHyperSliderEnums";

/** Particle effect configuration */
export interface ISliderParticle {
  enabled: boolean;
  count: number;
  size: { min: number; max: number };
  color: string[];
  shape: ParticleShape;
  speed: { min: number; max: number };
  direction: ParticleDirection;
  opacity: { min: number; max: number };
  connectLines: boolean;
  connectDistance: number;
  lineColor: string;
  lineWidth: number;
  responsive: boolean;
}

/** Runtime particle instance (generated by useSliderParticles) */
export interface IParticleInstance {
  id: string;
  x: number;
  y: number;
  size: number;
  color: string;
  opacity: number;
  animationDelay: number;
  animationDuration: number;
}

export const DEFAULT_PARTICLE: ISliderParticle = {
  enabled: false,
  count: 50,
  size: { min: 2, max: 6 },
  color: ["#ffffff"],
  shape: "circle",
  speed: { min: 2, max: 5 },
  direction: "down",
  opacity: { min: 0.3, max: 0.8 },
  connectLines: false,
  connectDistance: 100,
  lineColor: "rgba(255,255,255,0.2)",
  lineWidth: 1,
  responsive: true,
};
