define([], function() {
  return {
    "PropertyPaneDescription": "Configure HyperStyle branding and theming engine",
    "BrandingGroupName": "Branding",
    "LayoutGroupName": "Header & Footer",
    "EffectsGroupName": "Design Effects",
    "AdvancedGroupName": "Advanced",
    "TitleFieldLabel": "Brand Title",
    "LogoFieldLabel": "Logo URL",
    "TaglineFieldLabel": "Tagline",
    "PrimaryColorLabel": "Primary Color",
    "SecondaryColorLabel": "Secondary Color",
    "AccentColorLabel": "Accent Color",
    "PrimaryFontLabel": "Primary Font",
    "SecondaryFontLabel": "Secondary Font",
    "BaseFontSizeLabel": "Base Font Size",
    "HeadingScaleLabel": "Heading Scale",
    "IconLibraryLabel": "Icon Library",
    "HeaderStyleLabel": "Header Style",
    "FooterStyleLabel": "Footer Style",
    "FooterColumnsLabel": "Footer Columns",
    "CardStyleLabel": "Card Style",
    "BorderRadiusLabel": "Border Radius",
    "ShadowPresetLabel": "Shadow Preset",
    "WpHeaderStyleLabel": "Web Part Header Style",
    "WpBorderStyleLabel": "Web Part Border Style",
    "WpShadowStyleLabel": "Web Part Shadow Style",
    "WpSpacingLabel": "Web Part Spacing",
    "RerunWizardLabel": "Re-run Setup Wizard",
    "RerunWizardDesc": "Opens the setup wizard to reconfigure all settings",
    "WizardTitle": "HyperStyle Setup Wizard",
    "WelcomeTagline": "The most powerful SharePoint UI customizer with 15 templates, glassmorphism, aurora backgrounds, dark mode, and web part styling"
  };
});
