import type { IHyperTemplate, TemplateType } from "../models";

/**
 * V2 Template Gallery — 15 predefined templates across 3 categories.
 * Full visual configs will be populated in HP3 (template components step).
 * For now, includes all metadata + default feature flags.
 */
export const TEMPLATES: IHyperTemplate[] = [
  /* ── Classic (4) ── */
  {
    id: "executive",
    name: "Executive Card",
    description: "Elegant dark navy card with gold accents, large photo, premium feel",
    icon: "\uD83C\uDFC6",
    category: "classic",
    accentColor: "#c5a55a",
    previewGradient: "linear-gradient(135deg, #0f1b2d, #1a3a5c)",
    featureBadges: ["Premium", "Dark"],
    defaults: {
      accentColor: "#c5a55a",
      headerStyle: "solid",
      photoShape: "circle",
      animation: "none",
      showSkills: false,
      showBadges: true,
      showHobbies: false,
      showSlogan: false,
      showEducation: false,
      showOrgChart: false,
      showCalendar: false,
      shadow: "strong",
    },
    configuration: {
      cardStyle: "expanded",
      photoSize: "large",
      showPresence: true,
      showStatusMessage: true,
      presencePosition: "onPhoto",
      showQuickActions: true,
      enabledActions: ["email", "teams_chat", "schedule"],
      actionsLayout: "horizontal",
      buttonSize: "large",
      showActionLabels: true,
      showCompletenessScore: false,
      visibleFields: ["displayName", "jobTitle", "department", "mail", "mobilePhone"],
      backgroundColor: "#FFFFFF",
      borderRadius: 16,
      shadow: "strong",
      useThemeColors: false,
    },
  },
  {
    id: "standard",
    name: "Team Member Standard",
    description: "Balanced professional layout with all sections, blue accent",
    icon: "\uD83D\uDC64",
    category: "classic",
    accentColor: "#0078d4",
    previewGradient: "linear-gradient(135deg, #0078d4, #106ebe)",
    featureBadges: ["Balanced", "Skills"],
    defaults: {
      accentColor: "#0078d4",
      headerStyle: "gradient",
      photoShape: "circle",
      animation: "none",
      showSkills: true,
      showBadges: true,
      showHobbies: false,
      showSlogan: false,
      showEducation: false,
      showOrgChart: false,
      showCalendar: false,
      shadow: "medium",
    },
    configuration: {
      cardStyle: "standard",
      photoSize: "medium",
      showPresence: true,
      showStatusMessage: true,
      presencePosition: "onPhoto",
      showQuickActions: true,
      enabledActions: ["email", "teams_chat", "teams_call", "schedule"],
      actionsLayout: "horizontal",
      buttonSize: "medium",
      showActionLabels: true,
      showCompletenessScore: true,
      scorePosition: "bottom",
      scoreStyle: "progressBar",
      visibleFields: [
        "displayName", "jobTitle", "department", "mail",
        "mobilePhone", "businessPhones", "officeLocation", "city",
      ],
      backgroundColor: "#F3F2F1",
      borderRadius: 8,
      shadow: "medium",
      useThemeColors: true,
    },
  },
  {
    id: "compact",
    name: "Compact Contact",
    description: "Minimal horizontal layout, essential info only",
    icon: "\uD83D\uDCCB",
    category: "classic",
    accentColor: "#0078d4",
    previewGradient: "linear-gradient(135deg, #f3f2f1, #e1dfdd)",
    featureBadges: ["Minimal", "Compact"],
    defaults: {
      accentColor: "#0078d4",
      headerStyle: "solid",
      photoShape: "circle",
      animation: "none",
      showSkills: false,
      showBadges: false,
      showHobbies: false,
      showSlogan: false,
      showEducation: false,
      showOrgChart: false,
      showCalendar: false,
      shadow: "light",
    },
    configuration: {
      cardStyle: "compact",
      photoSize: "small",
      showPresence: true,
      showStatusMessage: false,
      presencePosition: "onPhoto",
      showQuickActions: true,
      enabledActions: ["email", "teams_chat", "teams_call"],
      actionsLayout: "dropdown",
      buttonSize: "small",
      showActionLabels: false,
      showCompletenessScore: true,
      scorePosition: "top",
      scoreStyle: "percentage",
      visibleFields: ["displayName", "jobTitle", "mail", "mobilePhone"],
      backgroundColor: "#FFFFFF",
      borderRadius: 4,
      shadow: "light",
      useThemeColors: false,
    },
  },
  {
    id: "corporate",
    name: "Corporate Professional",
    description: "Traditional business card style, warm gray, formal layout",
    icon: "\uD83C\uDFE2",
    category: "classic",
    accentColor: "#323130",
    previewGradient: "linear-gradient(135deg, #edebe9, #d2d0ce)",
    featureBadges: ["Formal", "Traditional"],
    defaults: {
      accentColor: "#323130",
      headerStyle: "solid",
      photoShape: "square",
      animation: "none",
      showSkills: false,
      showBadges: false,
      showHobbies: false,
      showSlogan: false,
      showEducation: true,
      showOrgChart: false,
      showCalendar: false,
      shadow: "none",
    },
    configuration: {
      cardStyle: "standard",
      photoSize: "small",
      showPresence: false,
      showStatusMessage: false,
      presencePosition: "onPhoto",
      showQuickActions: true,
      enabledActions: ["email", "teams_call", "schedule"],
      actionsLayout: "vertical",
      buttonSize: "medium",
      showActionLabels: true,
      showCompletenessScore: false,
      visibleFields: [
        "displayName", "jobTitle", "department", "companyName",
        "mail", "businessPhones", "officeLocation",
      ],
      backgroundColor: "#EDEBE9",
      borderRadius: 0,
      shadow: "none",
      useThemeColors: true,
    },
  },

  /* ── Modern (5) ── */
  {
    id: "social",
    name: "Social Profile",
    description: "Cover photo banner, stats row, bio, tag cloud, hobbies",
    icon: "\uD83D\uDCF1",
    category: "modern",
    accentColor: "#e91e63",
    previewGradient: "linear-gradient(135deg, #e91e63, #c2185b)",
    featureBadges: ["Social", "Hobbies", "Skills"],
    defaults: {
      accentColor: "#e91e63",
      headerStyle: "image",
      photoShape: "circle",
      animation: "slideIn",
      showSkills: true,
      showBadges: true,
      showHobbies: true,
      showSlogan: true,
      showEducation: false,
      showOrgChart: false,
      showCalendar: false,
      shadow: "medium",
    },
    configuration: {
      cardStyle: "expanded",
      photoSize: "large",
      showPresence: true,
      showStatusMessage: true,
      presencePosition: "onPhoto",
      showQuickActions: true,
      enabledActions: ["email", "teams_chat", "teams_call", "schedule"],
      actionsLayout: "horizontal",
      buttonSize: "medium",
      showActionLabels: true,
      showCompletenessScore: false,
      backgroundColor: "#FFFFFF",
      borderRadius: 12,
      shadow: "medium",
      useThemeColors: false,
    },
  },
  {
    id: "bento",
    name: "Bento Grid",
    description: "Multi-panel CSS Grid layout, each section in its own card",
    icon: "\uD83D\uDDBC\uFE0F",
    category: "modern",
    accentColor: "#6366f1",
    previewGradient: "linear-gradient(135deg, #6366f1, #4f46e5)",
    featureBadges: ["Grid", "Skills", "Calendar"],
    defaults: {
      accentColor: "#6366f1",
      headerStyle: "solid",
      photoShape: "rounded",
      animation: "slideIn",
      showSkills: true,
      showBadges: true,
      showHobbies: true,
      showSlogan: false,
      showEducation: true,
      showOrgChart: true,
      showCalendar: true,
      shadow: "light",
    },
    configuration: {
      cardStyle: "expanded",
      photoSize: "large",
      showPresence: true,
      showStatusMessage: false,
      presencePosition: "onPhoto",
      showQuickActions: true,
      enabledActions: ["email", "teams_chat", "teams_call"],
      actionsLayout: "horizontal",
      buttonSize: "medium",
      showActionLabels: false,
      showCompletenessScore: false,
      backgroundColor: "#FFFFFF",
      borderRadius: 16,
      shadow: "light",
      useThemeColors: false,
    },
  },
  {
    id: "glass",
    name: "Glassmorphism",
    description: "Frosted translucent card with blur effect and glow accents",
    icon: "\uD83D\uDCA0",
    category: "modern",
    accentColor: "#06b6d4",
    previewGradient: "linear-gradient(135deg, rgba(6,182,212,0.6), rgba(139,92,246,0.4))",
    featureBadges: ["Glass", "Blur", "Glow"],
    defaults: {
      accentColor: "#06b6d4",
      headerStyle: "gradient",
      photoShape: "circle",
      animation: "glow",
      showSkills: true,
      showBadges: true,
      showHobbies: false,
      showSlogan: true,
      showEducation: false,
      showOrgChart: false,
      showCalendar: false,
      shadow: "medium",
    },
    configuration: {
      cardStyle: "expanded",
      photoSize: "medium",
      showPresence: true,
      showStatusMessage: false,
      presencePosition: "onPhoto",
      showQuickActions: true,
      enabledActions: ["email", "teams_chat"],
      actionsLayout: "horizontal",
      buttonSize: "medium",
      showActionLabels: false,
      showCompletenessScore: false,
      backgroundColor: "rgba(255,255,255,0.15)",
      borderRadius: 20,
      shadow: "medium",
      useThemeColors: false,
    },
  },
  {
    id: "hero",
    name: "Hero Banner",
    description: "Full-width cover photo, large centered avatar, gradient overlay",
    icon: "\u2B50",
    category: "modern",
    accentColor: "#8b5cf6",
    previewGradient: "linear-gradient(135deg, #8b5cf6, #6d28d9)",
    featureBadges: ["Banner", "Skills", "Bold"],
    defaults: {
      accentColor: "#8b5cf6",
      headerStyle: "image",
      photoShape: "circle",
      animation: "slideIn",
      showSkills: true,
      showBadges: true,
      showHobbies: false,
      showSlogan: true,
      showEducation: false,
      showOrgChart: false,
      showCalendar: false,
      shadow: "strong",
    },
    configuration: {
      cardStyle: "expanded",
      photoSize: "large",
      showPresence: true,
      showStatusMessage: true,
      presencePosition: "onPhoto",
      showQuickActions: true,
      enabledActions: ["email", "teams_chat", "teams_call", "schedule"],
      actionsLayout: "horizontal",
      buttonSize: "large",
      showActionLabels: true,
      showCompletenessScore: false,
      backgroundColor: "#FFFFFF",
      borderRadius: 12,
      shadow: "strong",
      useThemeColors: false,
    },
  },
  {
    id: "sidebar",
    name: "Sidebar Layout",
    description: "Two-column split: colored sidebar with photo + white content area",
    icon: "\uD83D\uDCC4",
    category: "modern",
    accentColor: "#0ea5e9",
    previewGradient: "linear-gradient(90deg, #0ea5e9, #f3f2f1)",
    featureBadges: ["2-Column", "Skills", "Org"],
    defaults: {
      accentColor: "#0ea5e9",
      headerStyle: "solid",
      photoShape: "circle",
      animation: "none",
      showSkills: true,
      showBadges: true,
      showHobbies: false,
      showSlogan: false,
      showEducation: true,
      showOrgChart: true,
      showCalendar: false,
      shadow: "medium",
    },
    configuration: {
      cardStyle: "expanded",
      photoSize: "large",
      showPresence: true,
      showStatusMessage: false,
      presencePosition: "nextToName",
      showQuickActions: true,
      enabledActions: ["email", "teams_chat", "teams_call", "schedule"],
      actionsLayout: "vertical",
      buttonSize: "medium",
      showActionLabels: true,
      showCompletenessScore: false,
      backgroundColor: "#FFFFFF",
      borderRadius: 8,
      shadow: "medium",
      useThemeColors: false,
    },
  },

  /* ── Creative (6) ── */
  {
    id: "neon",
    name: "Neon Glow",
    description: "Dark theme with neon accent glow, hexagonal avatar, cyber aesthetic",
    icon: "\uD83D\uDD2E",
    category: "creative",
    accentColor: "#22d3ee",
    previewGradient: "linear-gradient(135deg, #0a0a1a, #1a1a3e)",
    featureBadges: ["Dark", "Glow", "Skills"],
    defaults: {
      accentColor: "#22d3ee",
      headerStyle: "solid",
      photoShape: "hexagon",
      animation: "glow",
      showSkills: true,
      showBadges: true,
      showHobbies: false,
      showSlogan: true,
      showEducation: false,
      showOrgChart: false,
      showCalendar: false,
      shadow: "strong",
    },
    configuration: {
      cardStyle: "expanded",
      photoSize: "large",
      showPresence: true,
      showStatusMessage: false,
      presencePosition: "onPhoto",
      showQuickActions: true,
      enabledActions: ["email", "teams_chat", "teams_call"],
      actionsLayout: "horizontal",
      buttonSize: "medium",
      showActionLabels: false,
      showCompletenessScore: false,
      backgroundColor: "#0a0a1a",
      borderRadius: 12,
      shadow: "strong",
      useThemeColors: false,
    },
  },
  {
    id: "gradient",
    name: "Bold Gradient",
    description: "Full gradient background with white text, SaaS-style bold typography",
    icon: "\uD83C\uDF08",
    category: "creative",
    accentColor: "#f97316",
    previewGradient: "linear-gradient(135deg, #f97316, #ec4899)",
    featureBadges: ["Gradient", "Bold", "Skills"],
    defaults: {
      accentColor: "#f97316",
      headerStyle: "gradient",
      photoShape: "circle",
      animation: "slideIn",
      showSkills: true,
      showBadges: true,
      showHobbies: false,
      showSlogan: true,
      showEducation: false,
      showOrgChart: false,
      showCalendar: false,
      shadow: "strong",
    },
    configuration: {
      cardStyle: "expanded",
      photoSize: "large",
      showPresence: true,
      showStatusMessage: false,
      presencePosition: "onPhoto",
      showQuickActions: true,
      enabledActions: ["email", "teams_chat"],
      actionsLayout: "horizontal",
      buttonSize: "large",
      showActionLabels: true,
      showCompletenessScore: false,
      backgroundColor: "#FFFFFF",
      borderRadius: 20,
      shadow: "strong",
      useThemeColors: false,
    },
  },
  {
    id: "magazine",
    name: "Magazine Editorial",
    description: "60/40 split layout, editorial typography, pull-quote slogan",
    icon: "\uD83D\uDCF0",
    category: "creative",
    accentColor: "#1a1a1a",
    previewGradient: "linear-gradient(90deg, #e8e8e8, #ffffff)",
    featureBadges: ["Editorial", "Slogan", "Split"],
    defaults: {
      accentColor: "#1a1a1a",
      headerStyle: "solid",
      photoShape: "square",
      animation: "none",
      showSkills: true,
      showBadges: false,
      showHobbies: true,
      showSlogan: true,
      showEducation: true,
      showOrgChart: false,
      showCalendar: false,
      shadow: "light",
    },
    configuration: {
      cardStyle: "expanded",
      photoSize: "large",
      showPresence: false,
      showStatusMessage: false,
      presencePosition: "onPhoto",
      showQuickActions: true,
      enabledActions: ["email", "teams_chat", "schedule"],
      actionsLayout: "horizontal",
      buttonSize: "medium",
      showActionLabels: true,
      showCompletenessScore: false,
      backgroundColor: "#FFFFFF",
      borderRadius: 4,
      shadow: "light",
      useThemeColors: false,
    },
  },
  {
    id: "flipCard",
    name: "Flip Card",
    description: "3D flip animation — front: photo & name, back: details & skills",
    icon: "\uD83D\uDD04",
    category: "creative",
    accentColor: "#14b8a6",
    previewGradient: "linear-gradient(135deg, #14b8a6, #0d9488)",
    featureBadges: ["Flip", "3D", "Skills"],
    defaults: {
      accentColor: "#14b8a6",
      headerStyle: "gradient",
      photoShape: "circle",
      animation: "flip",
      showSkills: true,
      showBadges: true,
      showHobbies: true,
      showSlogan: false,
      showEducation: false,
      showOrgChart: false,
      showCalendar: false,
      shadow: "medium",
    },
    configuration: {
      cardStyle: "standard",
      photoSize: "large",
      showPresence: true,
      showStatusMessage: false,
      presencePosition: "onPhoto",
      showQuickActions: true,
      enabledActions: ["email", "teams_chat", "teams_call"],
      actionsLayout: "horizontal",
      buttonSize: "medium",
      showActionLabels: false,
      showCompletenessScore: false,
      backgroundColor: "#FFFFFF",
      borderRadius: 16,
      shadow: "medium",
      useThemeColors: false,
    },
  },
  {
    id: "minimal",
    name: "Ultra Minimal",
    description: "Maximum whitespace, clean lines, hover reveals more info",
    icon: "\u2728",
    category: "creative",
    accentColor: "#94a3b8",
    previewGradient: "linear-gradient(135deg, #f8fafc, #e2e8f0)",
    featureBadges: ["Clean", "Hover", "Minimal"],
    defaults: {
      accentColor: "#94a3b8",
      headerStyle: "solid",
      photoShape: "circle",
      animation: "none",
      showSkills: false,
      showBadges: false,
      showHobbies: false,
      showSlogan: false,
      showEducation: false,
      showOrgChart: false,
      showCalendar: false,
      shadow: "none",
    },
    configuration: {
      cardStyle: "standard",
      photoSize: "medium",
      showPresence: true,
      showStatusMessage: false,
      presencePosition: "onPhoto",
      showQuickActions: true,
      enabledActions: ["email", "teams_chat"],
      actionsLayout: "horizontal",
      buttonSize: "medium",
      showActionLabels: false,
      showCompletenessScore: false,
      visibleFields: ["displayName", "jobTitle", "mail"],
      backgroundColor: "#FFFFFF",
      borderRadius: 20,
      shadow: "none",
      useThemeColors: false,
    },
  },
  {
    id: "mosaic",
    name: "Photo Mosaic",
    description: "Photo-heavy mosaic grid with interspersed info panels",
    icon: "\uD83C\uDFB2",
    category: "creative",
    accentColor: "#f59e0b",
    previewGradient: "linear-gradient(135deg, #f59e0b, #d97706)",
    featureBadges: ["Mosaic", "Photos", "Grid"],
    defaults: {
      accentColor: "#f59e0b",
      headerStyle: "solid",
      photoShape: "rounded",
      animation: "slideIn",
      showSkills: true,
      showBadges: true,
      showHobbies: true,
      showSlogan: false,
      showEducation: false,
      showOrgChart: false,
      showCalendar: false,
      shadow: "light",
    },
    configuration: {
      cardStyle: "expanded",
      photoSize: "large",
      showPresence: true,
      showStatusMessage: false,
      presencePosition: "onPhoto",
      showQuickActions: true,
      enabledActions: ["email", "teams_chat", "teams_call"],
      actionsLayout: "horizontal",
      buttonSize: "medium",
      showActionLabels: false,
      showCompletenessScore: false,
      backgroundColor: "#FFFFFF",
      borderRadius: 12,
      shadow: "light",
      useThemeColors: false,
    },
  },
];

/** Get template by ID */
export function getTemplateById(id: string): IHyperTemplate | undefined {
  let result: IHyperTemplate | undefined;
  TEMPLATES.forEach(function (t) {
    if (t.id === id && !result) {
      result = t;
    }
  });
  return result;
}

/** Get default template */
export function getDefaultTemplate(): IHyperTemplate {
  let result: IHyperTemplate | undefined;
  TEMPLATES.forEach(function (t) {
    if (t.id === "standard" && !result) {
      result = t;
    }
  });
  return result || TEMPLATES[0];
}

/** Get templates by category */
export function getTemplatesByCategory(category: string): IHyperTemplate[] {
  const results: IHyperTemplate[] = [];
  TEMPLATES.forEach(function (t) {
    if (t.category === category) {
      results.push(t);
    }
  });
  return results;
}

/** All template IDs */
export const TEMPLATE_IDS: TemplateType[] = [];
TEMPLATES.forEach(function (t) {
  TEMPLATE_IDS.push(t.id);
});
