define([], function () {
  return {
    PropertyPaneDescription: "Configure the HyperNav navigation and quick links web part.",
    LayoutGroupName: "Layout & Display",
    LinksGroupName: "Links Management",
    GroupsGroupName: "Group Management",
    FeaturesGroupName: "Features",
    StylingGroupName: "Styling",
    TitleFieldLabel: "Title",
    LayoutModeFieldLabel: "Layout Mode",
    GridColumnsFieldLabel: "Grid Columns",
    ShowIconsLabel: "Show Icons",
    ShowDescriptionsLabel: "Show Descriptions",
    ShowSearchLabel: "Enable Search Bar",
    ShowExternalBadgeLabel: "Show External Link Badge",
    ExternalBadgeIconLabel: "External Badge Icon Name",
    EnableAudienceTargetingLabel: "Enable Audience Targeting",
    EnablePersonalizationLabel: "Enable Link Pinning",
    EnableAnalyticsLabel: "Enable Click Analytics",
    EnableLinkHealthCheckLabel: "Enable Link Health Check (Edit Mode)",
    EnableGroupingLabel: "Enable Link Grouping",
    EnableDeepLinksLabel: "Enable Deep Link Detection",
    LinksPageDescription: "Manage navigation links. Add, remove, and reorder links.",
    AdvancedPageDescription: "Advanced features and behavior settings.",
    LinkHeaderPrefix: "Link",
    LinkTitleLabel: "Title",
    LinkUrlLabel: "URL",
    LinkDescriptionLabel: "Description",
    LinkIconNameLabel: "Icon Name",
    LinkOpenInNewTabLabel: "Open in new tab",
    LinkGroupNameLabel: "Group Name",
    MoveUpLabel: "Move Up",
    MoveDownLabel: "Move Down",
    RemoveLinkLabel: "Remove",
    AddLinkLabel: "Add New Link",
    NewLinkDefaultTitle: "New Link",
    GroupsSectionLabel: "Link Groups",
    GroupNameLabel: "Group",
    RemoveGroupLabel: "Remove Group",
    AddGroupLabel: "Add Group",
    NewGroupDefaultName: "Group",
    HoverEffectLabel: "Hover Effect",
    BorderRadiusLabel: "Border Radius",
    NavThemeLabel: "Theme",
    SeparatorLabel: "Separator Style",
    EnableStickyNavLabel: "Enable Sticky Navigation",
    EnableNotificationsLabel: "Enable Notification Badges",
    EnableActiveDetectionLabel: "Enable Active Link Detection",
    EnableTooltipsLabel: "Enable Tooltips",
    EnableCommandPaletteLabel: "Enable Command Palette (Ctrl+K)",
    EnableDarkModeToggleLabel: "Enable Dark Mode Toggle",
    WizardCompletedLabel: "Setup Wizard Completed",
    UseSampleDataLabel: "Use Sample Data",
    EnableDemoModeLabel: "Enable Demo Mode",
    SampleDataBanner: "Sample data active \u2014 connect a real data source in the property pane.",
    RunWizardLabel: "Run Setup Wizard",
    DemoControlsLabel: "Demo Controls"
  };
});
