declare interface IHyperNavWebPartStrings {
  PropertyPaneDescription: string;
  LayoutGroupName: string;
  LinksGroupName: string;
  GroupsGroupName: string;
  FeaturesGroupName: string;
  StylingGroupName: string;
  TitleFieldLabel: string;
  LayoutModeFieldLabel: string;
  GridColumnsFieldLabel: string;
  ShowIconsLabel: string;
  ShowDescriptionsLabel: string;
  ShowSearchLabel: string;
  ShowExternalBadgeLabel: string;
  ExternalBadgeIconLabel: string;
  EnableAudienceTargetingLabel: string;
  EnablePersonalizationLabel: string;
  EnableAnalyticsLabel: string;
  EnableLinkHealthCheckLabel: string;
  EnableGroupingLabel: string;
  EnableDeepLinksLabel: string;
  LinksPageDescription: string;
  AdvancedPageDescription: string;
  LinkHeaderPrefix: string;
  LinkTitleLabel: string;
  LinkUrlLabel: string;
  LinkDescriptionLabel: string;
  LinkIconNameLabel: string;
  LinkOpenInNewTabLabel: string;
  LinkGroupNameLabel: string;
  MoveUpLabel: string;
  MoveDownLabel: string;
  RemoveLinkLabel: string;
  AddLinkLabel: string;
  NewLinkDefaultTitle: string;
  GroupsSectionLabel: string;
  GroupNameLabel: string;
  RemoveGroupLabel: string;
  AddGroupLabel: string;
  NewGroupDefaultName: string;
  HoverEffectLabel: string;
  BorderRadiusLabel: string;
  NavThemeLabel: string;
  SeparatorLabel: string;
  EnableStickyNavLabel: string;
  EnableNotificationsLabel: string;
  EnableActiveDetectionLabel: string;
  EnableTooltipsLabel: string;
  EnableCommandPaletteLabel: string;
  EnableDarkModeToggleLabel: string;
  WizardCompletedLabel: string;
  UseSampleDataLabel: string;
  EnableDemoModeLabel: string;
  SampleDataBanner: string;
  RunWizardLabel: string;
  DemoControlsLabel: string;
}

declare module "HyperNavWebPartStrings" {
  const strings: IHyperNavWebPartStrings;
  export = strings;
}
