import type { ISocialPost, ISocialComment, SocialReactionType } from "../models";

function offsetDate(daysFromToday: number): string {
  var d = new Date();
  d.setDate(d.getDate() + daysFromToday);
  return d.toISOString();
}

function makeReactions(like: number, love: number, celebrate: number, insightful: number): Record<SocialReactionType, number> {
  return {
    like: like,
    love: love,
    celebrate: celebrate,
    insightful: insightful,
    curious: 0,
    support: 0,
    funny: 0,
    sad: 0,
  };
}

// 12 sample posts covering:
// - Text-only, image, multi-image, video, link preview
// - Pinned post, bookmarked, edited, flagged
// - Various departments, reactions, hashtags, @mentions
// - Mix of content types: announcement, question, achievement, article share, event, poll-like

export var SAMPLE_POSTS: ISocialPost[] = [
  {
    id: "post-001",
    content: "Excited to announce that our Johannesburg office has been certified as a Top Employer for 2026! This is a testament to our incredible team and culture. Thank you to everyone who makes this possible! #TopEmployer #ProudMoment #FirstDigital",
    author: {
      id: "u-sarah-nkosi",
      displayName: "Sarah Nkosi",
      email: "sarah.nkosi@firstdigital.co.za",
      jobTitle: "Chief People Officer",
      department: "Human Resources",
      photoUrl: "",
    },
    media: [
      { type: "image", url: "", alt: "Top Employer 2026 certificate", width: 800, height: 600 },
    ],
    reactions: makeReactions(42, 18, 31, 5),
    commentCount: 8,
    hashtags: ["TopEmployer", "ProudMoment", "FirstDigital"],
    mentions: [],
    visibility: "everyone",
    isPinned: true,
    isBookmarked: false,
    flagCount: 0,
    viewCount: 312,
    created: offsetDate(-1),
    modified: offsetDate(-1),
    isEdited: false,
  },
  {
    id: "post-002",
    content: "Just wrapped up our Q4 hackathon! Team Protea built an AI-powered document summariser that blew everyone away. Congrats to @thabo.mokoena and @zanele.dlamini for taking first place! #Hackathon #Innovation",
    author: {
      id: "u-james-van-rensburg",
      displayName: "James van Rensburg",
      email: "james.vr@firstdigital.co.za",
      jobTitle: "VP of Engineering",
      department: "Technology",
      photoUrl: "",
    },
    media: [
      { type: "image", url: "", alt: "Hackathon winners celebration", width: 1200, height: 800 },
      { type: "image", url: "", alt: "Team Protea demo", width: 1200, height: 800 },
    ],
    reactions: makeReactions(28, 12, 45, 8),
    commentCount: 15,
    hashtags: ["Hackathon", "Innovation"],
    mentions: ["thabo.mokoena", "zanele.dlamini"],
    visibility: "everyone",
    isPinned: false,
    isBookmarked: true,
    flagCount: 0,
    viewCount: 256,
    created: offsetDate(-2),
    modified: offsetDate(-2),
    isEdited: false,
  },
  {
    id: "post-003",
    content: "Does anyone have recommendations for good project management tools that integrate with SharePoint? We are evaluating options for the Cape Town team. Any experience with Planner vs. Monday.com vs. Asana? #AskTheTeam #ProjectManagement",
    author: {
      id: "u-priya-patel",
      displayName: "Priya Patel",
      email: "priya.patel@firstdigital.co.za",
      jobTitle: "Programme Manager",
      department: "PMO",
      photoUrl: "",
    },
    media: [],
    reactions: makeReactions(5, 0, 0, 3),
    myReaction: "like",
    commentCount: 22,
    hashtags: ["AskTheTeam", "ProjectManagement"],
    mentions: [],
    visibility: "everyone",
    isPinned: false,
    isBookmarked: false,
    flagCount: 0,
    viewCount: 189,
    created: offsetDate(-3),
    modified: offsetDate(-2),
    isEdited: true,
  },
  {
    id: "post-004",
    content: "Reminder: Our annual wellness day is next Friday at the Sandton campus! Free health screenings, yoga sessions, and a smoothie bar. Register on the intranet by Wednesday. #WellnessDay #HealthMatters",
    author: {
      id: "u-lerato-mahlangu",
      displayName: "Lerato Mahlangu",
      email: "lerato.m@firstdigital.co.za",
      jobTitle: "Wellness Coordinator",
      department: "Human Resources",
      photoUrl: "",
    },
    media: [
      { type: "image", url: "", alt: "Wellness Day poster", width: 600, height: 900 },
    ],
    reactions: makeReactions(15, 8, 0, 0),
    commentCount: 4,
    hashtags: ["WellnessDay", "HealthMatters"],
    mentions: [],
    visibility: "everyone",
    isPinned: false,
    isBookmarked: false,
    flagCount: 0,
    viewCount: 145,
    created: offsetDate(-4),
    modified: offsetDate(-4),
    isEdited: false,
  },
  {
    id: "post-005",
    content: "Thrilled to share that we just closed our biggest deal in company history! The Transnet digital transformation project is a R250M engagement spanning 3 years. Huge thanks to the entire sales and pre-sales team. #BigWin #DigitalTransformation",
    author: {
      id: "u-michael-botha",
      displayName: "Michael Botha",
      email: "michael.botha@firstdigital.co.za",
      jobTitle: "Managing Director",
      department: "Executive",
      photoUrl: "",
    },
    media: [],
    linkPreview: {
      url: "https://www.transnet.net",
      title: "Transnet Digital Transformation Programme",
      description: "First Digital selected as strategic partner for Transnet digital modernisation initiative.",
      imageUrl: "",
      siteName: "Transnet",
    },
    reactions: makeReactions(67, 34, 52, 11),
    commentCount: 31,
    hashtags: ["BigWin", "DigitalTransformation"],
    mentions: [],
    visibility: "everyone",
    isPinned: false,
    isBookmarked: false,
    flagCount: 0,
    viewCount: 498,
    created: offsetDate(-5),
    modified: offsetDate(-5),
    isEdited: false,
  },
  {
    id: "post-006",
    content: "I completed the Azure Solutions Architect Expert certification today! It has been 3 months of intense studying but so worth it. Big thanks to @priya.patel for the study group. #Certification #Azure #NeverStopLearning",
    author: {
      id: "u-sipho-zulu",
      displayName: "Sipho Zulu",
      email: "sipho.zulu@firstdigital.co.za",
      jobTitle: "Cloud Engineer",
      department: "Infrastructure",
      photoUrl: "",
    },
    media: [
      { type: "image", url: "", alt: "Azure certification badge", width: 400, height: 400 },
    ],
    reactions: makeReactions(38, 15, 28, 2),
    commentCount: 12,
    hashtags: ["Certification", "Azure", "NeverStopLearning"],
    mentions: ["priya.patel"],
    visibility: "everyone",
    isPinned: false,
    isBookmarked: false,
    flagCount: 0,
    viewCount: 201,
    created: offsetDate(-6),
    modified: offsetDate(-6),
    isEdited: false,
  },
  {
    id: "post-007",
    content: "The new Durban office is looking fantastic! Construction is 85% complete and we are on track for the March opening. Here is a sneak peek from today's site visit. #NewOffice #Durban #Growth",
    author: {
      id: "u-nomsa-dlamini",
      displayName: "Nomsa Dlamini",
      email: "nomsa.d@firstdigital.co.za",
      jobTitle: "Facilities Director",
      department: "Operations",
      photoUrl: "",
    },
    media: [
      { type: "image", url: "", alt: "New Durban office lobby", width: 1200, height: 800 },
      { type: "image", url: "", alt: "Open plan workspace", width: 1200, height: 800 },
      { type: "image", url: "", alt: "Rooftop terrace view", width: 1200, height: 800 },
    ],
    reactions: makeReactions(55, 22, 18, 0),
    commentCount: 9,
    hashtags: ["NewOffice", "Durban", "Growth"],
    mentions: [],
    visibility: "everyone",
    isPinned: false,
    isBookmarked: false,
    flagCount: 0,
    viewCount: 334,
    created: offsetDate(-7),
    modified: offsetDate(-7),
    isEdited: false,
  },
  {
    id: "post-008",
    content: "Great article on how AI is reshaping the financial services sector in Africa. Very relevant to what we are building at First Digital. Worth a read! #AI #Fintech #Africa",
    author: {
      id: "u-anika-meyer",
      displayName: "Anika Meyer",
      email: "anika.meyer@firstdigital.co.za",
      jobTitle: "Data Science Lead",
      department: "Analytics",
      photoUrl: "",
    },
    media: [],
    linkPreview: {
      url: "https://techcrunch.com/ai-africa-fintech",
      title: "AI is Reshaping Financial Services Across Africa",
      description: "From mobile banking to fraud detection, artificial intelligence is transforming how Africans access financial services.",
      imageUrl: "",
      siteName: "TechCrunch",
    },
    reactions: makeReactions(19, 3, 0, 14),
    commentCount: 6,
    hashtags: ["AI", "Fintech", "Africa"],
    mentions: [],
    visibility: "everyone",
    isPinned: false,
    isBookmarked: true,
    flagCount: 0,
    viewCount: 167,
    created: offsetDate(-8),
    modified: offsetDate(-8),
    isEdited: false,
  },
  {
    id: "post-009",
    content: "Welcome to our 15 new graduates joining the Technology and Analytics teams this month! We are excited to have you. Remember, your onboarding buddy is your best friend for the first few weeks. #NewJoiners #GradProgramme #Welcome",
    author: {
      id: "u-sarah-nkosi",
      displayName: "Sarah Nkosi",
      email: "sarah.nkosi@firstdigital.co.za",
      jobTitle: "Chief People Officer",
      department: "Human Resources",
      photoUrl: "",
    },
    media: [
      { type: "image", url: "", alt: "Graduate intake 2026 group photo", width: 1200, height: 600 },
    ],
    reactions: makeReactions(48, 25, 33, 0),
    commentCount: 18,
    hashtags: ["NewJoiners", "GradProgramme", "Welcome"],
    mentions: [],
    visibility: "everyone",
    isPinned: false,
    isBookmarked: false,
    flagCount: 0,
    viewCount: 287,
    created: offsetDate(-10),
    modified: offsetDate(-10),
    isEdited: false,
  },
  {
    id: "post-010",
    content: "Had an amazing time volunteering at the Soweto Science Centre yesterday. We helped 200 high school students with their first coding experience using Scratch and Python. Their excitement was contagious! #CSR #CodingForAll #GivingBack",
    author: {
      id: "u-thabo-mokoena",
      displayName: "Thabo Mokoena",
      email: "thabo.mokoena@firstdigital.co.za",
      jobTitle: "Senior Developer",
      department: "Technology",
      photoUrl: "",
    },
    media: [
      { type: "image", url: "", alt: "Students learning to code", width: 1200, height: 800 },
    ],
    reactions: makeReactions(62, 41, 15, 0),
    commentCount: 7,
    hashtags: ["CSR", "CodingForAll", "GivingBack"],
    mentions: [],
    visibility: "everyone",
    isPinned: false,
    isBookmarked: false,
    flagCount: 0,
    viewCount: 245,
    created: offsetDate(-12),
    modified: offsetDate(-12),
    isEdited: false,
  },
  {
    id: "post-011",
    content: "Quick tip for anyone using our new VPN: make sure you disconnect before joining Teams meetings to avoid the double-hop latency issue. IT is working on a permanent fix for next sprint. #TechTip #VPN",
    author: {
      id: "u-david-singh",
      displayName: "David Singh",
      email: "david.singh@firstdigital.co.za",
      jobTitle: "IT Support Manager",
      department: "IT Operations",
      photoUrl: "",
    },
    media: [],
    reactions: makeReactions(23, 0, 0, 8),
    commentCount: 5,
    hashtags: ["TechTip", "VPN"],
    mentions: [],
    visibility: "everyone",
    isPinned: false,
    isBookmarked: false,
    flagCount: 0,
    viewCount: 156,
    created: offsetDate(-14),
    modified: offsetDate(-14),
    isEdited: false,
  },
  {
    id: "post-012",
    content: "Our Women in Tech mentorship programme kicks off next month. If you are interested in being a mentor or mentee, please sign up by end of February. Let us build the next generation of tech leaders together! #WomenInTech #Mentorship #Diversity",
    author: {
      id: "u-zanele-dlamini",
      displayName: "Zanele Dlamini",
      email: "zanele.dlamini@firstdigital.co.za",
      jobTitle: "Diversity & Inclusion Lead",
      department: "Human Resources",
      photoUrl: "",
    },
    media: [],
    reactions: makeReactions(35, 20, 12, 0),
    commentCount: 14,
    hashtags: ["WomenInTech", "Mentorship", "Diversity"],
    mentions: [],
    visibility: "everyone",
    isPinned: false,
    isBookmarked: false,
    flagCount: 0,
    viewCount: 203,
    created: offsetDate(-16),
    modified: offsetDate(-16),
    isEdited: false,
  },
];

export var SAMPLE_COMMENTS: ISocialComment[] = [
  {
    id: "comment-001",
    postId: "post-001",
    author: {
      id: "u-james-van-rensburg",
      displayName: "James van Rensburg",
      email: "james.vr@firstdigital.co.za",
      jobTitle: "VP of Engineering",
      department: "Technology",
      photoUrl: "",
    },
    content: "This is incredible news! Well deserved. The culture here truly is special.",
    mentions: [],
    reactions: { like: 8, love: 3, celebrate: 2, insightful: 0, curious: 0, support: 0, funny: 0, sad: 0 },
    created: offsetDate(-1),
    isEdited: false,
    replies: [
      {
        id: "comment-001a",
        postId: "post-001",
        parentCommentId: "comment-001",
        author: {
          id: "u-sarah-nkosi",
          displayName: "Sarah Nkosi",
          email: "sarah.nkosi@firstdigital.co.za",
          jobTitle: "Chief People Officer",
          department: "Human Resources",
          photoUrl: "",
        },
        content: "Thank you James! It is a team effort through and through.",
        mentions: [],
        reactions: { like: 4, love: 1, celebrate: 0, insightful: 0, curious: 0, support: 0, funny: 0, sad: 0 },
        created: offsetDate(-1),
        isEdited: false,
        replies: [],
      },
    ],
  },
  {
    id: "comment-002",
    postId: "post-003",
    author: {
      id: "u-sipho-zulu",
      displayName: "Sipho Zulu",
      email: "sipho.zulu@firstdigital.co.za",
      jobTitle: "Cloud Engineer",
      department: "Infrastructure",
      photoUrl: "",
    },
    content: "We switched from Monday.com to Planner last year and it has been great for SharePoint integration. Happy to share our experience!",
    mentions: [],
    reactions: { like: 6, love: 0, celebrate: 0, insightful: 5, curious: 0, support: 0, funny: 0, sad: 0 },
    created: offsetDate(-3),
    isEdited: false,
    replies: [],
  },
  {
    id: "comment-003",
    postId: "post-005",
    author: {
      id: "u-anika-meyer",
      displayName: "Anika Meyer",
      email: "anika.meyer@firstdigital.co.za",
      jobTitle: "Data Science Lead",
      department: "Analytics",
      photoUrl: "",
    },
    content: "Congratulations to the entire team! This is a game-changer for our analytics division too.",
    mentions: [],
    reactions: { like: 12, love: 5, celebrate: 8, insightful: 0, curious: 0, support: 0, funny: 0, sad: 0 },
    created: offsetDate(-5),
    isEdited: false,
    replies: [],
  },
];
