define([], function() {
  return {
    "PropertyPaneDescription": "Configure the HyperNews web part",
    "BasicGroupName": "Basic Settings",
    "LayoutGroupName": "Layout & Display",
    "SourcesGroupName": "News Sources",
    "FeaturesGroupName": "Features",
    "FiltersGroupName": "Filters",
    "TitleFieldLabel": "Title",
    "LayoutTypeFieldLabel": "Layout Type",
    "PageSizeFieldLabel": "Items Per Page",
    "EnableInfiniteScrollLabel": "Enable Infinite Scroll",
    "EnableQuickReadLabel": "Enable Quick Read Modal",
    "EnableReactionsLabel": "Enable Reactions",
    "EnableBookmarksLabel": "Enable Bookmarks",
    "EnableReadTrackingLabel": "Track Reading Progress",
    "EnableSchedulingLabel": "Enable Content Scheduling",
    "ShowFeaturedLabel": "Show Featured Articles",
    "MaxFeaturedLabel": "Max Featured Articles",
    "ReactionListNameLabel": "Reactions List Name",
    "BookmarkListNameLabel": "Bookmarks List Name",
    "EnableFiltersLabel": "Enable Filters",
    "DateRangeLabel": "Date Range",
    "WizardGroupName": "Setup Wizard",
    "LaunchWizardLabel": "Launch Setup Wizard",
    "LaunchWizardDesc": "Open the full-screen configuration wizard to set up content sources, layout, features, and filters.",
    "SourcesSummaryLabel": "Sources Summary",
    "DisplayGroupName": "Display Options",
    "ShowImagesLabel": "Show Images",
    "ShowDescriptionLabel": "Show Description",
    "ShowAuthorLabel": "Show Author",
    "ShowDateLabel": "Show Date",
    "ShowReadTimeLabel": "Show Read Time"
  };
});
