import type { IHyperDirectoryUser, IDirectoryPresence } from "../models";

// ============================================================
// HyperDirectory — Sample Data Generator
// ============================================================
// Provides 12 realistic sample employees so the web part looks
// populated immediately on first deploy. Toggled via useSampleData.

var SAMPLE_USERS: IHyperDirectoryUser[] = [
  {
    id: "sample-001",
    displayName: "Olivia Martinez",
    givenName: "Olivia",
    surname: "Martinez",
    userPrincipalName: "olivia.martinez@contoso.com",
    mail: "olivia.martinez@contoso.com",
    jobTitle: "VP of Engineering",
    department: "Engineering",
    officeLocation: "Building A, Floor 3",
    city: "Seattle",
    companyName: "Contoso Ltd",
    mobilePhone: "+1 (206) 555-0101",
    businessPhones: ["+1 (206) 555-0100"],
    aboutMe: "Leading the engineering org. Passionate about distributed systems and team culture.",
    employeeId: "E10001",
  },
  {
    id: "sample-002",
    displayName: "James Chen",
    givenName: "James",
    surname: "Chen",
    userPrincipalName: "james.chen@contoso.com",
    mail: "james.chen@contoso.com",
    jobTitle: "Senior Software Engineer",
    department: "Engineering",
    officeLocation: "Building A, Floor 2",
    city: "Seattle",
    companyName: "Contoso Ltd",
    mobilePhone: "+1 (206) 555-0102",
    businessPhones: ["+1 (206) 555-0100"],
    aboutMe: "Full-stack developer specializing in React and TypeScript. Open source contributor.",
    employeeId: "E10002",
    managerId: "sample-001",
    managerDisplayName: "Olivia Martinez",
  },
  {
    id: "sample-003",
    displayName: "Aisha Patel",
    givenName: "Aisha",
    surname: "Patel",
    userPrincipalName: "aisha.patel@contoso.com",
    mail: "aisha.patel@contoso.com",
    jobTitle: "UX Design Lead",
    department: "Design",
    officeLocation: "Building B, Floor 1",
    city: "San Francisco",
    companyName: "Contoso Ltd",
    mobilePhone: "+1 (415) 555-0201",
    businessPhones: ["+1 (415) 555-0200"],
    aboutMe: "Human-centered design advocate. Previously at Adobe and Figma.",
    employeeId: "E10003",
  },
  {
    id: "sample-004",
    displayName: "Marcus Johnson",
    givenName: "Marcus",
    surname: "Johnson",
    userPrincipalName: "marcus.johnson@contoso.com",
    mail: "marcus.johnson@contoso.com",
    jobTitle: "Product Manager",
    department: "Product",
    officeLocation: "Building A, Floor 4",
    city: "Seattle",
    companyName: "Contoso Ltd",
    mobilePhone: "+1 (206) 555-0301",
    businessPhones: ["+1 (206) 555-0300"],
    aboutMe: "Driving product strategy for the collaboration platform. MBA from Wharton.",
    employeeId: "E10004",
  },
  {
    id: "sample-005",
    displayName: "Sophie Andersson",
    givenName: "Sophie",
    surname: "Andersson",
    userPrincipalName: "sophie.andersson@contoso.com",
    mail: "sophie.andersson@contoso.com",
    jobTitle: "Data Scientist",
    department: "Engineering",
    officeLocation: "Building C, Floor 2",
    city: "Stockholm",
    companyName: "Contoso Europe",
    mobilePhone: "+46 70 555 0401",
    businessPhones: ["+46 8 555 0400"],
    aboutMe: "ML and NLP specialist. PhD in Computer Science from KTH. Fluent in Swedish and English.",
    employeeId: "E10005",
    managerId: "sample-001",
    managerDisplayName: "Olivia Martinez",
  },
  {
    id: "sample-006",
    displayName: "David Kim",
    givenName: "David",
    surname: "Kim",
    userPrincipalName: "david.kim@contoso.com",
    mail: "david.kim@contoso.com",
    jobTitle: "IT Administrator",
    department: "IT",
    officeLocation: "Building A, Floor 1",
    city: "Seattle",
    companyName: "Contoso Ltd",
    mobilePhone: "+1 (206) 555-0501",
    businessPhones: ["+1 (206) 555-0500"],
    aboutMe: "Managing M365 tenant, Azure AD, and security policies. CISSP certified.",
    employeeId: "E10006",
  },
  {
    id: "sample-007",
    displayName: "Emma Wilson",
    givenName: "Emma",
    surname: "Wilson",
    userPrincipalName: "emma.wilson@contoso.com",
    mail: "emma.wilson@contoso.com",
    jobTitle: "Marketing Director",
    department: "Marketing",
    officeLocation: "Building B, Floor 3",
    city: "New York",
    companyName: "Contoso Ltd",
    mobilePhone: "+1 (212) 555-0601",
    businessPhones: ["+1 (212) 555-0600"],
    aboutMe: "Building the Contoso brand globally. 15+ years in B2B SaaS marketing.",
    employeeId: "E10007",
  },
  {
    id: "sample-008",
    displayName: "Carlos Rivera",
    givenName: "Carlos",
    surname: "Rivera",
    userPrincipalName: "carlos.rivera@contoso.com",
    mail: "carlos.rivera@contoso.com",
    jobTitle: "Solutions Architect",
    department: "Engineering",
    officeLocation: "Building A, Floor 3",
    city: "Austin",
    companyName: "Contoso Ltd",
    mobilePhone: "+1 (512) 555-0701",
    businessPhones: ["+1 (512) 555-0700"],
    aboutMe: "Cloud architecture and SharePoint platform specialist. Azure Solutions Architect Expert.",
    employeeId: "E10008",
    managerId: "sample-001",
    managerDisplayName: "Olivia Martinez",
  },
  {
    id: "sample-009",
    displayName: "Priya Sharma",
    givenName: "Priya",
    surname: "Sharma",
    userPrincipalName: "priya.sharma@contoso.com",
    mail: "priya.sharma@contoso.com",
    jobTitle: "HR Business Partner",
    department: "Human Resources",
    officeLocation: "Building B, Floor 2",
    city: "Seattle",
    companyName: "Contoso Ltd",
    mobilePhone: "+1 (206) 555-0801",
    businessPhones: ["+1 (206) 555-0800"],
    aboutMe: "Fostering an inclusive workplace. SHRM-SCP certified. Passionate about employee wellbeing.",
    employeeId: "E10009",
  },
  {
    id: "sample-010",
    displayName: "Alex Thompson",
    givenName: "Alex",
    surname: "Thompson",
    userPrincipalName: "alex.thompson@contoso.com",
    mail: "alex.thompson@contoso.com",
    jobTitle: "DevOps Engineer",
    department: "Engineering",
    officeLocation: "Building C, Floor 1",
    city: "London",
    companyName: "Contoso UK",
    mobilePhone: "+44 7700 900401",
    businessPhones: ["+44 20 7946 0400"],
    aboutMe: "CI/CD pipelines, Kubernetes, and infrastructure as code. AWS and Azure certified.",
    employeeId: "E10010",
    managerId: "sample-001",
    managerDisplayName: "Olivia Martinez",
  },
  {
    id: "sample-011",
    displayName: "Rachel Green",
    givenName: "Rachel",
    surname: "Green",
    userPrincipalName: "rachel.green@contoso.com",
    mail: "rachel.green@contoso.com",
    jobTitle: "Finance Manager",
    department: "Finance",
    officeLocation: "Building A, Floor 5",
    city: "Seattle",
    companyName: "Contoso Ltd",
    mobilePhone: "+1 (206) 555-0901",
    businessPhones: ["+1 (206) 555-0900"],
    aboutMe: "FP&A and financial reporting. CPA. Streamlining budgeting processes with Power BI.",
    employeeId: "E10011",
  },
  {
    id: "sample-012",
    displayName: "Kenji Tanaka",
    givenName: "Kenji",
    surname: "Tanaka",
    userPrincipalName: "kenji.tanaka@contoso.com",
    mail: "kenji.tanaka@contoso.com",
    jobTitle: "QA Lead",
    department: "Engineering",
    officeLocation: "Building C, Floor 3",
    city: "Tokyo",
    companyName: "Contoso Japan",
    mobilePhone: "+81 90 5555 0101",
    businessPhones: ["+81 3 5555 0100"],
    aboutMe: "Test automation and quality engineering. Playwright and Cypress expert. ISTQB certified.",
    employeeId: "E10012",
    managerId: "sample-001",
    managerDisplayName: "Olivia Martinez",
  },
];

var SAMPLE_PRESENCE_STATES: Array<{ availability: string; activity: string }> = [
  { availability: "Available", activity: "Available" },
  { availability: "Busy", activity: "InACall" },
  { availability: "Available", activity: "Available" },
  { availability: "DoNotDisturb", activity: "Presenting" },
  { availability: "Away", activity: "Away" },
  { availability: "Available", activity: "Available" },
  { availability: "Busy", activity: "InAMeeting" },
  { availability: "Available", activity: "Available" },
  { availability: "BeRightBack", activity: "BeRightBack" },
  { availability: "Offline", activity: "OffWork" },
  { availability: "Available", activity: "Available" },
  { availability: "Busy", activity: "InACall" },
];

/** Return the 12 sample directory users */
export function getSampleUsers(): IHyperDirectoryUser[] {
  return SAMPLE_USERS.slice();
}

/** Return sample presence map keyed by user id */
export function getSamplePresenceMap(): Record<string, IDirectoryPresence> {
  var map: Record<string, IDirectoryPresence> = {};
  SAMPLE_USERS.forEach(function (user, index) {
    map[user.id] = SAMPLE_PRESENCE_STATES[index];
  });
  return map;
}
