define([], function () {
  return {
    // Property pane
    PropertyPaneDescription: "Configure HyperSlider settings.",

    // Page 1: General
    GeneralGroupName: "General",
    TitleFieldLabel: "Title",
    ModeFieldLabel: "Slider Mode",
    HeightModeFieldLabel: "Height Mode",
    FixedHeightFieldLabel: "Fixed Height (px)",
    AspectRatioFieldLabel: "Aspect Ratio",
    CustomRatioWidthLabel: "Custom Ratio Width",
    CustomRatioHeightLabel: "Custom Ratio Height",
    FullBleedFieldLabel: "Full Bleed",
    BorderRadiusFieldLabel: "Border Radius (px)",
    ReducedMotionFieldLabel: "Reduced Motion",

    // Page 2: Transitions & Autoplay
    TransitionsGroupName: "Transitions & Autoplay",
    TransitionTypeFieldLabel: "Transition Effect",
    TransitionDurationFieldLabel: "Transition Duration (ms)",
    TransitionEasingFieldLabel: "Transition Easing",
    AutoplayGroupName: "Autoplay",
    AutoplayEnabledLabel: "Enable Autoplay",
    AutoplayIntervalLabel: "Autoplay Interval (ms)",
    AutoplayPauseOnHoverLabel: "Pause on Hover",
    AutoplayPauseOnInteractionLabel: "Pause on Interaction",
    AutoplayDirectionLabel: "Autoplay Direction",
    AutoplayLoopLabel: "Loop",

    // Page 3: Navigation
    NavigationGroupName: "Navigation",
    ArrowsEnabledLabel: "Show Arrows",
    ArrowsStyleLabel: "Arrow Style",
    BulletsEnabledLabel: "Show Bullets",
    BulletsStyleLabel: "Bullet Style",
    BulletsPositionLabel: "Bullet Position",
    ThumbnailsEnabledLabel: "Show Thumbnails",
    ThumbnailsPositionLabel: "Thumbnail Position",
    ThumbnailsWidthLabel: "Thumbnail Width",
    ThumbnailsHeightLabel: "Thumbnail Height",
    ProgressEnabledLabel: "Show Progress Bar",
    SlideCountEnabledLabel: "Show Slide Count",
    KeyboardLabel: "Keyboard Navigation",
    SwipeEnabledLabel: "Enable Swipe",
    SwipeThresholdLabel: "Swipe Threshold (px)",

    // Page 4: Content & Effects
    ContentGroupName: "Content",
    ContentBindingEnabledLabel: "Enable Dynamic Content",
    ListNameLabel: "List Name",
    MaxItemsLabel: "Max Items",
    SlidesJsonLabel: "Slides (JSON)",
    EffectsGroupName: "Effects",
    ParticleEnabledLabel: "Enable Particles",
    ParticleCountLabel: "Particle Count",
    ParticleShapeLabel: "Particle Shape",
    TypewriterEnabledLabel: "Enable Typewriter Effect",
    SnowEnabledLabel: "Enable Snow Effect",
    PerformanceGroupName: "Performance",
    LazyLoadLabel: "Lazy Load Images",
    PreloadCountLabel: "Preload Count",

    // Component strings
    PreviousSlideLabel: "Previous slide",
    NextSlideLabel: "Next slide",
    GoToSlideLabel: "Go to slide",
    SlideNavigationLabel: "Slide navigation",
    SliderCarouselLabel: "Slider carousel",
    SlideLabel: "Slide",
    OfLabel: "of",
    PauseLabel: "Pause autoplay",
    PlayLabel: "Resume autoplay",
    BeforeLabel: "Before",
    AfterLabel: "After",
    DragToCompareLabel: "Drag to compare",
    NoSlidesTitle: "No Slides",
    NoSlidesDescription: "Add slides in the property pane to get started.",
    EditOverlayTitle: "HyperSlider",
    EditOverlayDescription: "Configure slides and layers in the property pane.",
    LoadingLabel: "Loading slider...",
  };
});
