import type { ILertAlert } from "../models/ILertAlert";
import type { IAlertRule } from "../models/IAlertRule";
import type { LertLayout, LertTemplateId, AlertGroupMode } from "../models/IHyperLertV2Enums";

// ---------------------------------------------------------------------------
// Demo Presets
// ---------------------------------------------------------------------------

/** A demo preset that configures layout + template + grouping */
export interface ILertDemoPreset {
  id: string;
  name: string;
  description: string;
  layout: LertLayout;
  templateId: LertTemplateId;
  groupMode: AlertGroupMode;
}

/** Pre-configured demo presets for quick setup */
export var DEMO_PRESETS: ILertDemoPreset[] = [
  {
    id: "preset-command-it",
    name: "IT Command Center",
    description: "Full command center layout with KPI cards, grouped by severity",
    layout: "commandCenter",
    templateId: "it-operations",
    groupMode: "severity",
  },
  {
    id: "preset-budget-cards",
    name: "Budget Dashboard",
    description: "Card grid view of budget alerts, grouped by category",
    layout: "cardGrid",
    templateId: "budget-monitor",
    groupMode: "category",
  },
  {
    id: "preset-sla-table",
    name: "SLA Compliance Table",
    description: "Sortable table of SLA metrics, grouped by source",
    layout: "table",
    templateId: "sla-tracker",
    groupMode: "source",
  },
  {
    id: "preset-security-inbox",
    name: "Security Inbox",
    description: "Email-style inbox for security alerts with preview pane",
    layout: "inbox",
    templateId: "security-watchdog",
    groupMode: "none",
  },
  {
    id: "preset-project-kanban",
    name: "Project Kanban",
    description: "Kanban board of project alerts, grouped by rule",
    layout: "kanban",
    templateId: "project-deadline",
    groupMode: "rule",
  },
];

// ---------------------------------------------------------------------------
// Sample Alerts (15 realistic scenarios)
// ---------------------------------------------------------------------------

/** 15 sample alerts across all severities and states */
export var SAMPLE_ALERTS: ILertAlert[] = [
  {
    id: "alert-001",
    ruleId: "rule-budget-01",
    ruleName: "Budget Threshold Monitor",
    title: "Budget Threshold Exceeded: Q4 Marketing spend at 92% of limit",
    description: "The Q4 Marketing budget has reached $460,000 of its $500,000 limit. At current burn rate, the budget will be exhausted by December 15th.",
    severity: "critical",
    state: "triggered",
    source: "Budget Tracker List",
    category: "Spending",
    triggeredAt: "2025-11-18T09:15:00Z",
    acknowledgedAt: "",
    acknowledgedBy: "",
    resolvedAt: "",
    resolvedBy: "",
    snoozedUntil: "",
    escalatedTo: "primary",
    escalatedAt: "",
    triggerCount: 3,
    fingerprint: "budget-q4-marketing-92",
    groupedAlertIds: [],
    tags: ["budget", "marketing", "q4"],
    triggerData: { "Department": "Marketing", "BudgetUsed": "$460,000", "BudgetLimit": "$500,000", "Percentage": "92%" },
    notes: [],
    isRead: false,
    isArchived: false,
  },
  {
    id: "alert-002",
    ruleId: "rule-sla-01",
    ruleName: "SLA Response Time Monitor",
    title: "SLA Breach Warning: 3 tickets approaching 4-hour response deadline",
    description: "Tickets #4521, #4523, and #4527 have been open for over 3 hours without a first response. SLA breach will occur in less than 60 minutes.",
    severity: "high",
    state: "escalated",
    source: "Helpdesk Tickets List",
    category: "Response Time",
    triggeredAt: "2025-11-18T10:30:00Z",
    acknowledgedAt: "",
    acknowledgedBy: "",
    resolvedAt: "",
    resolvedBy: "",
    snoozedUntil: "",
    escalatedTo: "secondary",
    escalatedAt: "2025-11-18T10:45:00Z",
    triggerCount: 1,
    fingerprint: "sla-response-3tickets",
    groupedAlertIds: [],
    tags: ["sla", "helpdesk", "response-time"],
    triggerData: { "TicketIds": "#4521, #4523, #4527", "TimeElapsed": "3h 15m", "SLALimit": "4h" },
    notes: ["Escalated to secondary support team"],
    isRead: false,
    isArchived: false,
  },
  {
    id: "alert-003",
    ruleId: "rule-security-01",
    ruleName: "Failed Login Monitor",
    title: "Failed Login Attempts: 12 failed logins for john.doe@contoso.com in 30 minutes",
    description: "Multiple failed authentication attempts detected for user john.doe@contoso.com. This may indicate a brute force attack or a locked-out user.",
    severity: "critical",
    state: "acknowledged",
    source: "Azure AD Sign-In Logs",
    category: "Authentication",
    triggeredAt: "2025-11-18T08:45:00Z",
    acknowledgedAt: "2025-11-18T08:52:00Z",
    acknowledgedBy: "admin@contoso.com",
    resolvedAt: "",
    resolvedBy: "",
    snoozedUntil: "",
    escalatedTo: "primary",
    escalatedAt: "",
    triggerCount: 1,
    fingerprint: "auth-failed-johndoe-12",
    groupedAlertIds: [],
    tags: ["security", "authentication", "brute-force"],
    triggerData: { "User": "john.doe@contoso.com", "FailedAttempts": "12", "TimeWindow": "30 minutes", "SourceIPs": "3 unique IPs" },
    notes: ["Investigating - may be password lockout issue"],
    isRead: true,
    isArchived: false,
  },
  {
    id: "alert-004",
    ruleId: "rule-content-01",
    ruleName: "Content Expiry Monitor",
    title: "Content Expiring Soon: 8 pages expiring within 7 days",
    description: "Eight published pages on the Intranet site have expiration dates within the next 7 days. Content owners should review and either extend or archive these pages.",
    severity: "medium",
    state: "triggered",
    source: "Pages Library",
    category: "Expiry",
    triggeredAt: "2025-11-18T06:00:00Z",
    acknowledgedAt: "",
    acknowledgedBy: "",
    resolvedAt: "",
    resolvedBy: "",
    snoozedUntil: "",
    escalatedTo: "primary",
    escalatedAt: "",
    triggerCount: 1,
    fingerprint: "content-expiry-8pages",
    groupedAlertIds: [],
    tags: ["content", "expiry", "governance"],
    triggerData: { "ExpiringPages": "8", "EarliestExpiry": "2025-11-20", "Site": "Intranet Home" },
    notes: [],
    isRead: false,
    isArchived: false,
  },
  {
    id: "alert-005",
    ruleId: "rule-it-01",
    ruleName: "Server CPU Monitor",
    title: "Server CPU High: Server-WEB02 CPU at 94% for 15 minutes",
    description: "Web server WEB02 has sustained CPU usage above 90% for 15 consecutive minutes. This may impact user-facing application performance.",
    severity: "high",
    state: "triggered",
    source: "Server Health List",
    category: "Performance",
    triggeredAt: "2025-11-18T11:00:00Z",
    acknowledgedAt: "",
    acknowledgedBy: "",
    resolvedAt: "",
    resolvedBy: "",
    snoozedUntil: "",
    escalatedTo: "primary",
    escalatedAt: "",
    triggerCount: 5,
    fingerprint: "cpu-web02-94pct",
    groupedAlertIds: [],
    tags: ["infrastructure", "cpu", "performance"],
    triggerData: { "Server": "WEB02", "CPUPercent": "94%", "Duration": "15 minutes", "Threshold": "90%" },
    notes: [],
    isRead: false,
    isArchived: false,
  },
  {
    id: "alert-006",
    ruleId: "rule-inventory-01",
    ruleName: "Low Stock Monitor",
    title: "Inventory Low: Widget-A stock at 15 units (reorder point: 20)",
    description: "Widget-A inventory has dropped below the reorder point of 20 units. Current stock is 15 units. Average daily consumption is 3 units.",
    severity: "medium",
    state: "snoozed",
    source: "Inventory Tracker List",
    category: "Stock",
    triggeredAt: "2025-11-17T14:00:00Z",
    acknowledgedAt: "2025-11-17T14:30:00Z",
    acknowledgedBy: "warehouse@contoso.com",
    resolvedAt: "",
    resolvedBy: "",
    snoozedUntil: "2025-11-19T09:00:00Z",
    escalatedTo: "primary",
    escalatedAt: "",
    triggerCount: 2,
    fingerprint: "inventory-widgetA-low",
    groupedAlertIds: [],
    tags: ["inventory", "stock", "reorder"],
    triggerData: { "Product": "Widget-A", "CurrentStock": "15", "ReorderPoint": "20", "DailyUsage": "3" },
    notes: ["PO submitted, snoozed until delivery expected"],
    isRead: true,
    isArchived: false,
  },
  {
    id: "alert-007",
    ruleId: "rule-project-01",
    ruleName: "Milestone Overdue Monitor",
    title: "Project Milestone Overdue: Phase 2 UAT was due 3 days ago",
    description: "The Phase 2 UAT milestone for Project Atlas was due on November 15th and has not been marked complete. 4 out of 12 test cases remain unfinished.",
    severity: "high",
    state: "triggered",
    source: "Project Milestones List",
    category: "Milestones",
    triggeredAt: "2025-11-18T07:00:00Z",
    acknowledgedAt: "",
    acknowledgedBy: "",
    resolvedAt: "",
    resolvedBy: "",
    snoozedUntil: "",
    escalatedTo: "primary",
    escalatedAt: "",
    triggerCount: 3,
    fingerprint: "project-atlas-uat-overdue",
    groupedAlertIds: [],
    tags: ["project", "milestone", "overdue"],
    triggerData: { "Project": "Atlas", "Milestone": "Phase 2 UAT", "DueDate": "2025-11-15", "DaysOverdue": "3" },
    notes: [],
    isRead: false,
    isArchived: false,
  },
  {
    id: "alert-008",
    ruleId: "rule-hr-01",
    ruleName: "Policy Acknowledgment Monitor",
    title: "New Policy Acknowledgment Required: 12 employees pending IT Security Policy",
    description: "The updated IT Security Policy v3.2 was published 14 days ago. 12 employees have not yet acknowledged it. Company policy requires acknowledgment within 15 days.",
    severity: "low",
    state: "triggered",
    source: "Policy Acknowledgments List",
    category: "Policies",
    triggeredAt: "2025-11-18T08:00:00Z",
    acknowledgedAt: "",
    acknowledgedBy: "",
    resolvedAt: "",
    resolvedBy: "",
    snoozedUntil: "",
    escalatedTo: "primary",
    escalatedAt: "",
    triggerCount: 1,
    fingerprint: "policy-itsecurity-12pending",
    groupedAlertIds: [],
    tags: ["hr", "policy", "compliance"],
    triggerData: { "Policy": "IT Security Policy v3.2", "PendingCount": "12", "DaysPublished": "14", "Deadline": "15 days" },
    notes: [],
    isRead: false,
    isArchived: false,
  },
  {
    id: "alert-009",
    ruleId: "rule-compliance-01",
    ruleName: "Audit Deadline Monitor",
    title: "Compliance Audit Reminder: SOC2 audit due in 14 days",
    description: "The annual SOC2 Type II audit is scheduled for December 2nd. 3 of 8 control evidence documents have not been updated for the current period.",
    severity: "medium",
    state: "acknowledged",
    source: "Compliance Calendar List",
    category: "Audits",
    triggeredAt: "2025-11-18T06:00:00Z",
    acknowledgedAt: "2025-11-18T09:00:00Z",
    acknowledgedBy: "compliance@contoso.com",
    resolvedAt: "",
    resolvedBy: "",
    snoozedUntil: "",
    escalatedTo: "primary",
    escalatedAt: "",
    triggerCount: 1,
    fingerprint: "audit-soc2-14days",
    groupedAlertIds: [],
    tags: ["compliance", "audit", "soc2"],
    triggerData: { "AuditType": "SOC2 Type II", "DueDate": "2025-12-02", "DaysRemaining": "14", "EvidenceGaps": "3 of 8" },
    notes: ["Working with IT to gather remaining evidence"],
    isRead: true,
    isArchived: false,
  },
  {
    id: "alert-010",
    ruleId: "rule-hr-02",
    ruleName: "Onboarding Task Monitor",
    title: "Onboarding Task Incomplete: 3 new hires have overdue Day-1 tasks",
    description: "Three new hires who started this week still have incomplete Day-1 onboarding tasks: equipment setup, badge activation, and system access requests.",
    severity: "low",
    state: "triggered",
    source: "Onboarding Tasks List",
    category: "Tasks",
    triggeredAt: "2025-11-18T12:00:00Z",
    acknowledgedAt: "",
    acknowledgedBy: "",
    resolvedAt: "",
    resolvedBy: "",
    snoozedUntil: "",
    escalatedTo: "primary",
    escalatedAt: "",
    triggerCount: 1,
    fingerprint: "onboarding-day1-3newhires",
    groupedAlertIds: [],
    tags: ["hr", "onboarding", "tasks"],
    triggerData: { "NewHires": "3", "OverdueTasks": "Equipment, Badge, System Access", "StartDate": "2025-11-17" },
    notes: [],
    isRead: false,
    isArchived: false,
  },
  {
    id: "alert-011",
    ruleId: "rule-security-02",
    ruleName: "Permission Change Monitor",
    title: "Permission Change Detected: Site Collection Admin added to HR Portal",
    description: "User sarah.wilson@contoso.com was added as a Site Collection Administrator to the HR Portal site collection. This change was made by global.admin@contoso.com.",
    severity: "high",
    state: "triggered",
    source: "Audit Log",
    category: "Permissions",
    triggeredAt: "2025-11-18T10:15:00Z",
    acknowledgedAt: "",
    acknowledgedBy: "",
    resolvedAt: "",
    resolvedBy: "",
    snoozedUntil: "",
    escalatedTo: "primary",
    escalatedAt: "",
    triggerCount: 1,
    fingerprint: "perm-scadmin-hrportal-sarah",
    groupedAlertIds: [],
    tags: ["security", "permissions", "admin"],
    triggerData: { "User": "sarah.wilson@contoso.com", "Role": "Site Collection Admin", "Site": "HR Portal", "ChangedBy": "global.admin@contoso.com" },
    notes: [],
    isRead: false,
    isArchived: false,
  },
  {
    id: "alert-012",
    ruleId: "rule-content-02",
    ruleName: "Document Retention Monitor",
    title: "Document Retention: 5 documents in Legal hold approaching deletion",
    description: "Five documents currently under Legal Hold in the Contracts library have retention labels expiring within 30 days. Review required before auto-deletion.",
    severity: "critical",
    state: "escalated",
    source: "Contracts Library",
    category: "Compliance",
    triggeredAt: "2025-11-17T08:00:00Z",
    acknowledgedAt: "",
    acknowledgedBy: "",
    resolvedAt: "",
    resolvedBy: "",
    snoozedUntil: "",
    escalatedTo: "manager",
    escalatedAt: "2025-11-18T08:00:00Z",
    triggerCount: 4,
    fingerprint: "retention-legal-5docs",
    groupedAlertIds: [],
    tags: ["compliance", "retention", "legal-hold"],
    triggerData: { "Documents": "5", "HoldType": "Legal Hold", "Library": "Contracts", "ExpiryWindow": "30 days" },
    notes: ["Escalated to Legal department manager"],
    isRead: true,
    isArchived: false,
  },
  {
    id: "alert-013",
    ruleId: "rule-it-02",
    ruleName: "Calendar Conflict Monitor",
    title: "Calendar Conflict: 4 meeting room double-bookings this week",
    description: "Four meeting rooms have overlapping reservations this week. Conference Room A has 2 conflicts on Tuesday, and Conference Room C has 2 conflicts on Thursday.",
    severity: "info",
    state: "resolved",
    source: "Room Calendars",
    category: "Availability",
    triggeredAt: "2025-11-18T07:00:00Z",
    acknowledgedAt: "2025-11-18T07:30:00Z",
    acknowledgedBy: "facilities@contoso.com",
    resolvedAt: "2025-11-18T08:15:00Z",
    resolvedBy: "facilities@contoso.com",
    snoozedUntil: "",
    escalatedTo: "primary",
    escalatedAt: "",
    triggerCount: 1,
    fingerprint: "calendar-rooms-4conflicts",
    groupedAlertIds: [],
    tags: ["facilities", "calendar", "meetings"],
    triggerData: { "Conflicts": "4", "Rooms": "Conference Room A, Conference Room C", "Days": "Tuesday, Thursday" },
    notes: ["Resolved - conflicting bookings rescheduled"],
    isRead: true,
    isArchived: false,
  },
  {
    id: "alert-014",
    ruleId: "rule-it-03",
    ruleName: "Storage Quota Monitor",
    title: "SharePoint Storage: Site collection at 87% of 25GB quota",
    description: "The Intranet site collection storage is at 21.75GB of its 25GB quota. At current growth rate, the quota will be reached in approximately 3 weeks.",
    severity: "medium",
    state: "triggered",
    source: "Site Collection Admin",
    category: "Infrastructure",
    triggeredAt: "2025-11-18T05:00:00Z",
    acknowledgedAt: "",
    acknowledgedBy: "",
    resolvedAt: "",
    resolvedBy: "",
    snoozedUntil: "",
    escalatedTo: "primary",
    escalatedAt: "",
    triggerCount: 2,
    fingerprint: "storage-intranet-87pct",
    groupedAlertIds: [],
    tags: ["infrastructure", "storage", "quota"],
    triggerData: { "Site": "Intranet", "UsedGB": "21.75", "QuotaGB": "25", "Percentage": "87%", "WeeksRemaining": "3" },
    notes: [],
    isRead: false,
    isArchived: false,
  },
  {
    id: "alert-015",
    ruleId: "rule-sla-02",
    ruleName: "Helpdesk Queue Monitor",
    title: "Helpdesk Queue: 23 unassigned tickets older than 2 hours",
    description: "The helpdesk queue has 23 unassigned tickets that have been waiting for more than 2 hours. Average wait time for these tickets is 3h 45m.",
    severity: "high",
    state: "triggered",
    source: "Helpdesk Tickets List",
    category: "Resolution",
    triggeredAt: "2025-11-18T13:00:00Z",
    acknowledgedAt: "",
    acknowledgedBy: "",
    resolvedAt: "",
    resolvedBy: "",
    snoozedUntil: "",
    escalatedTo: "primary",
    escalatedAt: "",
    triggerCount: 1,
    fingerprint: "helpdesk-unassigned-23",
    groupedAlertIds: [],
    tags: ["helpdesk", "queue", "unassigned"],
    triggerData: { "UnassignedTickets": "23", "OldestAge": "4h 12m", "AverageWait": "3h 45m", "Threshold": "2h" },
    notes: [],
    isRead: false,
    isArchived: false,
  },
];

// ---------------------------------------------------------------------------
// Sample Rules (5 pre-built rules)
// ---------------------------------------------------------------------------

/** 5 sample alert rules with realistic configurations */
export var SAMPLE_RULES: IAlertRule[] = [
  {
    id: "rule-budget-01",
    name: "Budget Threshold Monitor",
    description: "Triggers when any department budget usage exceeds 85% of the allocated limit",
    severity: "critical",
    status: "active",
    dataSource: JSON.stringify({
      type: "spList",
      listName: "Budget Tracker",
      siteUrl: "",
      selectFields: ["Title", "Department", "BudgetUsed", "BudgetLimit", "Percentage"],
      filterExpression: "",
      top: 100,
    }),
    conditions: JSON.stringify([
      { id: "cond-b1", field: "Percentage", operator: "greaterOrEqual", value: "85", value2: "", logicalOperator: "AND" },
    ]),
    actions: JSON.stringify([
      { channel: "email", enabled: true, recipients: "finance@contoso.com", subject: "Budget Alert: {{Department}} at {{Percentage}}%", bodyTemplate: "<h2>Budget Threshold Exceeded</h2><p>Department <strong>{{Department}}</strong> has used {{BudgetUsed}} of {{BudgetLimit}} ({{Percentage}}%).</p>", teamsRecipients: "", bannerMessage: "", bannerDuration: 0 },
      { channel: "banner", enabled: true, recipients: "", subject: "", bodyTemplate: "", teamsRecipients: "", bannerMessage: "Budget Alert: {{Department}} at {{Percentage}}% of limit", bannerDuration: 60 },
    ]),
    checkIntervalSeconds: 300,
    cooldownMinutes: 120,
    maxNotificationsPerDay: 5,
    activeHoursStart: "08:00",
    activeHoursEnd: "18:00",
    lastTriggered: "2025-11-18T09:15:00Z",
    lastChecked: "2025-11-18T13:15:00Z",
    triggerCount: 3,
    enabled: true,
  },
  {
    id: "rule-sla-01",
    name: "SLA Response Time Monitor",
    description: "Monitors helpdesk tickets approaching the 4-hour first response SLA deadline",
    severity: "warning",
    status: "active",
    dataSource: JSON.stringify({
      type: "spList",
      listName: "Helpdesk Tickets",
      siteUrl: "",
      selectFields: ["Title", "TicketId", "Status", "Created", "FirstResponseTime", "Priority"],
      filterExpression: "Status eq 'Open'",
      top: 500,
    }),
    conditions: JSON.stringify([
      { id: "cond-s1", field: "FirstResponseTime", operator: "isEmpty", value: "", value2: "", logicalOperator: "AND" },
      { id: "cond-s2", field: "Created", operator: "lessThan", value: "{{3HoursAgo}}", value2: "", logicalOperator: "AND" },
    ]),
    actions: JSON.stringify([
      { channel: "teams", enabled: true, recipients: "", subject: "", bodyTemplate: "", teamsRecipients: "helpdesk-leads@contoso.com", bannerMessage: "", bannerDuration: 0 },
      { channel: "email", enabled: true, recipients: "helpdesk-leads@contoso.com", subject: "SLA Warning: {{TicketId}} approaching 4h deadline", bodyTemplate: "<p>Ticket <strong>{{TicketId}}</strong> ({{Title}}) has been open for over 3 hours without a response.</p>", teamsRecipients: "", bannerMessage: "", bannerDuration: 0 },
    ]),
    checkIntervalSeconds: 180,
    cooldownMinutes: 30,
    maxNotificationsPerDay: 20,
    activeHoursStart: "",
    activeHoursEnd: "",
    lastTriggered: "2025-11-18T10:30:00Z",
    lastChecked: "2025-11-18T13:12:00Z",
    triggerCount: 8,
    enabled: true,
  },
  {
    id: "rule-security-01",
    name: "Failed Login Monitor",
    description: "Detects excessive failed login attempts that may indicate brute force attacks",
    severity: "critical",
    status: "active",
    dataSource: JSON.stringify({
      type: "graphApi",
      endpoint: "/auditLogs/signIns",
      selectFields: ["userPrincipalName", "status", "createdDateTime", "ipAddress"],
    }),
    conditions: JSON.stringify([
      { id: "cond-sec1", field: "status.errorCode", operator: "notEquals", value: "0", value2: "", logicalOperator: "AND" },
      { id: "cond-sec2", field: "__count", operator: "greaterOrEqual", value: "10", value2: "", logicalOperator: "AND" },
    ]),
    actions: JSON.stringify([
      { channel: "email", enabled: true, recipients: "security@contoso.com", subject: "SECURITY: {{FailedAttempts}} failed logins for {{User}}", bodyTemplate: "<h2 style='color:#c50f1f'>Security Alert</h2><p><strong>{{FailedAttempts}}</strong> failed login attempts detected for <strong>{{User}}</strong> within {{TimeWindow}}.</p><p>Source IPs: {{SourceIPs}}</p>", teamsRecipients: "", bannerMessage: "", bannerDuration: 0 },
      { channel: "teams", enabled: true, recipients: "", subject: "", bodyTemplate: "", teamsRecipients: "security@contoso.com", bannerMessage: "", bannerDuration: 0 },
      { channel: "banner", enabled: true, recipients: "", subject: "", bodyTemplate: "", teamsRecipients: "", bannerMessage: "Security Alert: Multiple failed logins detected for {{User}}", bannerDuration: 0 },
    ]),
    checkIntervalSeconds: 60,
    cooldownMinutes: 15,
    maxNotificationsPerDay: 50,
    activeHoursStart: "",
    activeHoursEnd: "",
    lastTriggered: "2025-11-18T08:45:00Z",
    lastChecked: "2025-11-18T13:14:00Z",
    triggerCount: 2,
    enabled: true,
  },
  {
    id: "rule-content-01",
    name: "Content Expiry Monitor",
    description: "Alerts when published pages have expiration dates approaching within 7 days",
    severity: "warning",
    status: "active",
    dataSource: JSON.stringify({
      type: "spList",
      listName: "Pages",
      siteUrl: "",
      selectFields: ["Title", "FileRef", "ExpirationDate", "Author/Title", "Modified"],
      filterExpression: "",
      top: 200,
    }),
    conditions: JSON.stringify([
      { id: "cond-c1", field: "ExpirationDate", operator: "lessOrEqual", value: "{{7DaysFromNow}}", value2: "", logicalOperator: "AND" },
      { id: "cond-c2", field: "ExpirationDate", operator: "greaterThan", value: "{{Today}}", value2: "", logicalOperator: "AND" },
    ]),
    actions: JSON.stringify([
      { channel: "email", enabled: true, recipients: "content-owners@contoso.com", subject: "Content Expiry: {{__matchCount}} pages expiring soon", bodyTemplate: "<h2>Content Expiry Notice</h2><p><strong>{{__matchCount}}</strong> pages are expiring within 7 days. Please review and either extend or archive.</p>", teamsRecipients: "", bannerMessage: "", bannerDuration: 0 },
    ]),
    checkIntervalSeconds: 3600,
    cooldownMinutes: 1440,
    maxNotificationsPerDay: 1,
    activeHoursStart: "06:00",
    activeHoursEnd: "08:00",
    lastTriggered: "2025-11-18T06:00:00Z",
    lastChecked: "2025-11-18T13:00:00Z",
    triggerCount: 5,
    enabled: true,
  },
  {
    id: "rule-it-01",
    name: "Server CPU Monitor",
    description: "Monitors server CPU usage and alerts when sustained above 90% for more than 10 minutes",
    severity: "warning",
    status: "active",
    dataSource: JSON.stringify({
      type: "spList",
      listName: "Server Health",
      siteUrl: "",
      selectFields: ["Title", "ServerName", "CPUPercent", "MemoryPercent", "DiskPercent", "LastUpdated"],
      filterExpression: "",
      top: 50,
    }),
    conditions: JSON.stringify([
      { id: "cond-it1", field: "CPUPercent", operator: "greaterOrEqual", value: "90", value2: "", logicalOperator: "AND" },
    ]),
    actions: JSON.stringify([
      { channel: "email", enabled: true, recipients: "it-ops@contoso.com", subject: "Server Alert: {{ServerName}} CPU at {{CPUPercent}}%", bodyTemplate: "<h2>High CPU Alert</h2><p>Server <strong>{{ServerName}}</strong> has CPU usage at <strong>{{CPUPercent}}%</strong>.</p><p>Memory: {{MemoryPercent}}% | Disk: {{DiskPercent}}%</p>", teamsRecipients: "", bannerMessage: "", bannerDuration: 0 },
      { channel: "teams", enabled: true, recipients: "", subject: "", bodyTemplate: "", teamsRecipients: "it-ops@contoso.com", bannerMessage: "", bannerDuration: 0 },
    ]),
    checkIntervalSeconds: 120,
    cooldownMinutes: 30,
    maxNotificationsPerDay: 20,
    activeHoursStart: "",
    activeHoursEnd: "",
    lastTriggered: "2025-11-18T11:00:00Z",
    lastChecked: "2025-11-18T13:14:00Z",
    triggerCount: 5,
    enabled: true,
  },
];
