import type { ICelebration, CelebrationType } from "../models";

/**
 * Generate a dynamic MM-DD string offset from today by the given number of days.
 * This ensures sample data always includes "today", "this week", and "this month" items.
 */
function offsetDate(daysFromToday: number): string {
  var d = new Date();
  d.setDate(d.getDate() + daysFromToday);
  var mm = String(d.getMonth() + 1);
  if (mm.length === 1) mm = "0" + mm;
  var dd = String(d.getDate());
  if (dd.length === 1) dd = "0" + dd;
  return mm + "-" + dd;
}

/**
 * Build 20 rich South African sample celebrations.
 * Dates are dynamic so "today", "this week", and "this month" always have entries.
 */
function buildSampleCelebrations(): ICelebration[] {
  var celebrations: ICelebration[] = [
    // ── TODAY (3 celebrations) ──
    {
      id: "sa-001",
      userId: "u-thabo-mokoena",
      displayName: "Thabo Mokoena",
      email: "thabo.mokoena@digitworx.co.za",
      jobTitle: "Senior Solutions Architect",
      department: "Technology",
      photoUrl: "",
      celebrationType: "birthday" as CelebrationType,
      celebrationDate: offsetDate(0),
      celebrationYear: 1988,
      customLabel: "",
      message: "",
      isOptedOut: false,
      source: "entraId",
    },
    {
      id: "sa-002",
      userId: "u-naledi-khumalo",
      displayName: "Naledi Khumalo",
      email: "naledi.khumalo@fnb.co.za",
      jobTitle: "Head of Digital Banking",
      department: "Digital Channels",
      photoUrl: "",
      celebrationType: "workAnniversary" as CelebrationType,
      celebrationDate: offsetDate(0),
      celebrationYear: 2015,
      customLabel: "",
      message: "",
      isOptedOut: false,
      source: "entraId",
    },
    {
      id: "sa-003",
      userId: "u-pieter-van-wyk",
      displayName: "Pieter van Wyk",
      email: "pieter.vanwyk@discovery.co.za",
      jobTitle: "Actuarial Manager",
      department: "Vitality",
      photoUrl: "",
      celebrationType: "promotion" as CelebrationType,
      celebrationDate: offsetDate(0),
      celebrationYear: 2025,
      customLabel: "Promoted to Director",
      message: "",
      isOptedOut: false,
      source: "spList",
    },

    // ── THIS WEEK (5 celebrations) ──
    {
      id: "sa-004",
      userId: "u-zanele-ndlovu",
      displayName: "Zanele Ndlovu",
      email: "zanele.ndlovu@standardbank.co.za",
      jobTitle: "Investment Analyst",
      department: "Corporate & Investment Banking",
      photoUrl: "",
      celebrationType: "birthday" as CelebrationType,
      celebrationDate: offsetDate(1),
      celebrationYear: 1992,
      customLabel: "",
      message: "",
      isOptedOut: false,
      source: "entraId",
    },
    {
      id: "sa-005",
      userId: "u-sipho-dlamini",
      displayName: "Sipho Dlamini",
      email: "sipho.dlamini@multichoice.com",
      jobTitle: "Broadcast Engineer",
      department: "Engineering",
      photoUrl: "",
      celebrationType: "wedding" as CelebrationType,
      celebrationDate: offsetDate(2),
      celebrationYear: 2025,
      customLabel: "",
      message: "",
      isOptedOut: false,
      source: "spList",
    },
    {
      id: "sa-006",
      userId: "u-fatima-patel",
      displayName: "Fatima Patel",
      email: "fatima.patel@woolworths.co.za",
      jobTitle: "Supply Chain Director",
      department: "Operations",
      photoUrl: "",
      celebrationType: "workAnniversary" as CelebrationType,
      celebrationDate: offsetDate(3),
      celebrationYear: 2005,
      customLabel: "",
      message: "",
      isOptedOut: false,
      source: "entraId",
    },
    {
      id: "sa-007",
      userId: "u-andile-mthembu",
      displayName: "Andile Mthembu",
      email: "andile.mthembu@sasol.com",
      jobTitle: "Chemical Engineer",
      department: "Process Engineering",
      photoUrl: "",
      celebrationType: "birthday" as CelebrationType,
      celebrationDate: offsetDate(4),
      celebrationYear: 1985,
      customLabel: "",
      message: "",
      isOptedOut: false,
      source: "entraId",
    },
    {
      id: "sa-008",
      userId: "u-lindiwe-maseko",
      displayName: "Lindiwe Maseko",
      email: "lindiwe.maseko@absa.co.za",
      jobTitle: "Compliance Officer",
      department: "Risk & Compliance",
      photoUrl: "",
      celebrationType: "graduation" as CelebrationType,
      celebrationDate: offsetDate(5),
      celebrationYear: 2025,
      customLabel: "MBA from Wits Business School",
      message: "",
      isOptedOut: false,
      source: "spList",
    },

    // ── THIS MONTH (7 celebrations) ──
    {
      id: "sa-009",
      userId: "u-ruan-botha",
      displayName: "Ruan Botha",
      email: "ruan.botha@takealot.com",
      jobTitle: "Product Manager",
      department: "E-Commerce",
      photoUrl: "",
      celebrationType: "birthday" as CelebrationType,
      celebrationDate: offsetDate(8),
      celebrationYear: 1990,
      customLabel: "",
      message: "",
      isOptedOut: false,
      source: "entraId",
    },
    {
      id: "sa-010",
      userId: "u-nomsa-mabena",
      displayName: "Nomsa Mabena",
      email: "nomsa.mabena@vodacom.co.za",
      jobTitle: "Network Architect",
      department: "Infrastructure",
      photoUrl: "",
      celebrationType: "childBirth" as CelebrationType,
      celebrationDate: offsetDate(10),
      celebrationYear: 2025,
      customLabel: "Baby girl Amahle",
      message: "",
      isOptedOut: false,
      source: "spList",
    },
    {
      id: "sa-011",
      userId: "u-david-naidoo",
      displayName: "David Naidoo",
      email: "david.naidoo@shoprite.co.za",
      jobTitle: "Regional Manager",
      department: "Retail Operations",
      photoUrl: "",
      celebrationType: "workAnniversary" as CelebrationType,
      celebrationDate: offsetDate(12),
      celebrationYear: 2000,
      customLabel: "",
      message: "",
      isOptedOut: false,
      source: "entraId",
    },
    {
      id: "sa-012",
      userId: "u-priya-govender",
      displayName: "Priya Govender",
      email: "priya.govender@bidvest.co.za",
      jobTitle: "Financial Controller",
      department: "Finance",
      photoUrl: "",
      celebrationType: "birthday" as CelebrationType,
      celebrationDate: offsetDate(15),
      celebrationYear: 1987,
      customLabel: "",
      message: "",
      isOptedOut: false,
      source: "entraId",
    },
    {
      id: "sa-013",
      userId: "u-bongani-sithole",
      displayName: "Bongani Sithole",
      email: "bongani.sithole@sappi.com",
      jobTitle: "Environmental Sustainability Lead",
      department: "ESG",
      photoUrl: "",
      celebrationType: "retirement" as CelebrationType,
      celebrationDate: offsetDate(18),
      celebrationYear: 1990,
      customLabel: "35 years of service",
      message: "",
      isOptedOut: false,
      source: "spList",
    },
    {
      id: "sa-014",
      userId: "u-lerato-molefe",
      displayName: "Lerato Molefe",
      email: "lerato.molefe@mtn.co.za",
      jobTitle: "UX Design Lead",
      department: "Digital Experience",
      photoUrl: "",
      celebrationType: "promotion" as CelebrationType,
      celebrationDate: offsetDate(20),
      celebrationYear: 2025,
      customLabel: "Promoted to Design Director",
      message: "",
      isOptedOut: false,
      source: "spList",
    },
    {
      id: "sa-015",
      userId: "u-hennie-joubert",
      displayName: "Hennie Joubert",
      email: "hennie.joubert@sanlam.co.za",
      jobTitle: "Portfolio Manager",
      department: "Asset Management",
      photoUrl: "",
      celebrationType: "birthday" as CelebrationType,
      celebrationDate: offsetDate(22),
      celebrationYear: 1979,
      customLabel: "",
      message: "",
      isOptedOut: false,
      source: "entraId",
    },

    // ── NEXT MONTH / QUARTER (5 celebrations) ──
    {
      id: "sa-016",
      userId: "u-ayanda-zulu",
      displayName: "Ayanda Zulu",
      email: "ayanda.zulu@naspers.com",
      jobTitle: "Data Scientist",
      department: "AI & Analytics",
      photoUrl: "",
      celebrationType: "workAnniversary" as CelebrationType,
      celebrationDate: offsetDate(35),
      celebrationYear: 2020,
      customLabel: "",
      message: "",
      isOptedOut: false,
      source: "entraId",
    },
    {
      id: "sa-017",
      userId: "u-willem-pretorius",
      displayName: "Willem Pretorius",
      email: "willem.pretorius@anglogold.com",
      jobTitle: "Mine Operations Manager",
      department: "Mining Operations",
      photoUrl: "",
      celebrationType: "birthday" as CelebrationType,
      celebrationDate: offsetDate(42),
      celebrationYear: 1982,
      customLabel: "",
      message: "",
      isOptedOut: false,
      source: "entraId",
    },
    {
      id: "sa-018",
      userId: "u-thandiwe-ngcobo",
      displayName: "Thandiwe Ngcobo",
      email: "thandiwe.ngcobo@capitec.co.za",
      jobTitle: "Branch Manager",
      department: "Retail Banking",
      photoUrl: "",
      celebrationType: "wedding" as CelebrationType,
      celebrationDate: offsetDate(50),
      celebrationYear: 2025,
      customLabel: "",
      message: "",
      isOptedOut: false,
      source: "spList",
    },
    {
      id: "sa-019",
      userId: "u-mandla-mahlangu",
      displayName: "Mandla Mahlangu",
      email: "mandla.mahlangu@eskom.co.za",
      jobTitle: "Electrical Engineer",
      department: "Generation",
      photoUrl: "",
      celebrationType: "graduation" as CelebrationType,
      celebrationDate: offsetDate(60),
      celebrationYear: 2025,
      customLabel: "PhD from University of Pretoria",
      message: "",
      isOptedOut: false,
      source: "spList",
    },
    {
      id: "sa-020",
      userId: "u-sarah-van-der-merwe",
      displayName: "Sarah van der Merwe",
      email: "sarah.vandermerwe@netcare.co.za",
      jobTitle: "Chief Nursing Officer",
      department: "Clinical Services",
      photoUrl: "",
      celebrationType: "workAnniversary" as CelebrationType,
      celebrationDate: offsetDate(75),
      celebrationYear: 2010,
      customLabel: "",
      message: "",
      isOptedOut: false,
      source: "entraId",
    },
  ];

  return celebrations;
}

/** 20 South African sample celebrations with dynamic dates relative to today */
export var SAMPLE_CELEBRATIONS: ICelebration[] = buildSampleCelebrations();
