define([], function () {
  return {
    PropertyPaneDescription: "Configure HyperExplorer file and media explorer.",

    /* Page 1 — General */
    GeneralGroupName: "General Settings",
    TitleFieldLabel: "Web Part Title",
    LibraryNameFieldLabel: "Document Library Name",
    RootFolderFieldLabel: "Root Folder Path (optional)",
    ViewModeFieldLabel: "Default View Mode",
    SortModeFieldLabel: "Sort By",
    SortDirectionFieldLabel: "Sort Direction",
    ItemsPerPageFieldLabel: "Items Per Page",
    ShowFoldersFieldLabel: "Show Folders",

    /* Page 2 — Preview & Display */
    PreviewDisplayPageDescription: "Configure preview and display options.",
    PreviewGroupName: "Preview Settings",
    EnablePreviewFieldLabel: "Enable Preview",
    PreviewModeFieldLabel: "Preview Mode",
    EnableLightboxFieldLabel: "Enable Lightbox Gallery",
    EnableVideoPlaylistFieldLabel: "Enable Video Playlist",
    EnableMetadataOverlayFieldLabel: "Show Metadata Overlay",
    ShowThumbnailsFieldLabel: "Show Thumbnails",
    ThumbnailSizeFieldLabel: "Thumbnail Size (px)",

    /* Page 3 — Features */
    FeaturesPageDescription: "Configure features and actions.",
    FeaturesGroupName: "Features",
    EnableUploadFieldLabel: "Enable Drag & Drop Upload",
    EnableQuickActionsFieldLabel: "Enable Quick Actions Menu",
    EnableCompareFieldLabel: "Enable Side-by-Side Compare",
    EnableWatermarkFieldLabel: "Enable Watermark",
    WatermarkTextFieldLabel: "Watermark Text",
    FileTypeFilterFieldLabel: "File Type Filter (JSON array, e.g. [\"pdf\",\"docx\"])",
    EnableRecentFilesFieldLabel: "Show Recent Files (Graph API)",
    MaxRecentFilesFieldLabel: "Max Recent Files",
    EnableFolderTreeFieldLabel: "Show Folder Tree",
    EnableBreadcrumbsFieldLabel: "Show Breadcrumbs",
    CacheEnabledFieldLabel: "Enable Caching",

    /* Component strings */
    NoFilesTitle: "No Files Found",
    NoFilesDescription: "There are no files to display in this folder.",
    LoadingLabel: "Loading files...",
    UploadFilesLabel: "Upload Files",
    DropFilesHereLabel: "Drop files here to upload",
    SearchPlaceholder: "Search files...",
    SelectAllLabel: "Select All",
    ClearSelectionLabel: "Clear Selection",
    DownloadSelectedLabel: "Download Selected",
    CompareLabel: "Compare",
    PreviewLabel: "Preview",
    CloseLabel: "Close",
    NextLabel: "Next",
    PreviousLabel: "Previous",
    ZoomInLabel: "Zoom In",
    ZoomOutLabel: "Zoom Out",
    ResetZoomLabel: "Reset Zoom",
    ShareLabel: "Share",
    CopyLinkLabel: "Copy Link",
    DownloadLabel: "Download",
    RenameLabel: "Rename",
    MoveLabel: "Move",
    DeleteLabel: "Delete",
    PropertiesLabel: "Properties",
    WatermarkLabel: "Confidential",
    RecentFilesLabel: "Recent Files",
    LoadMoreLabel: "Load More",
    EditModeLabel: "Configure HyperExplorer in the property pane.",
  };
});
