define([], function () {
  return {
    PropertyPaneDescription: "Configure HyperExplorer file and media explorer.",

    /* Page 1 — General */
    GeneralGroupName: "General Settings",
    TitleFieldLabel: "Web Part Title",
    LibraryNameFieldLabel: "Document Library Name",
    RootFolderFieldLabel: "Root Folder Path (optional)",
    ViewModeFieldLabel: "Default View Mode",
    SortModeFieldLabel: "Sort By",
    SortDirectionFieldLabel: "Sort Direction",
    ItemsPerPageFieldLabel: "Items Per Page",
    ShowFoldersFieldLabel: "Show Folders",
    UseSampleDataFieldLabel: "Use Sample Data (demo mode)",
    WizardCompletedFieldLabel: "Wizard Completed",

    /* Page 2 — Preview & Display */
    PreviewDisplayPageDescription: "Configure preview and display options.",
    PreviewGroupName: "Preview Settings",
    EnablePreviewFieldLabel: "Enable Preview",
    PreviewModeFieldLabel: "Preview Mode",
    EnableLightboxFieldLabel: "Enable Lightbox Gallery",
    EnableVideoPlaylistFieldLabel: "Enable Video Playlist",
    EnableMetadataOverlayFieldLabel: "Show Metadata Overlay",
    ShowThumbnailsFieldLabel: "Show Thumbnails",
    ThumbnailSizeFieldLabel: "Thumbnail Size (px)",

    /* Page 3 — Features */
    FeaturesPageDescription: "Configure features and actions.",
    FeaturesGroupName: "Features",
    EnableUploadFieldLabel: "Enable Drag & Drop Upload",
    EnableQuickActionsFieldLabel: "Enable Quick Actions Menu",
    EnableCompareFieldLabel: "Enable Side-by-Side Compare",
    EnableWatermarkFieldLabel: "Enable Watermark",
    WatermarkTextFieldLabel: "Watermark Text",
    FileTypeFilterFieldLabel: "File Type Filter (JSON array, e.g. [\"pdf\",\"docx\"])",
    EnableRecentFilesFieldLabel: "Show Recent Files (Graph API)",
    MaxRecentFilesFieldLabel: "Max Recent Files",
    EnableFolderTreeFieldLabel: "Show Folder Tree",
    EnableBreadcrumbsFieldLabel: "Show Breadcrumbs",
    CacheEnabledFieldLabel: "Enable Caching",

    /* Page 3 — File Plan & Compliance */
    FilePlanGroupName: "File Plan & Compliance",
    EnableFilePlanFieldLabel: "Enable File Plan (MS Purview)",
    ShowComplianceBadgesFieldLabel: "Show Compliance Badges on Files",
    RequireRetentionLabelFieldLabel: "Require Retention Label on Upload",

    /* Component strings */
    NoFilesTitle: "No Files Found",
    NoFilesDescription: "There are no files to display in this folder.",
    LoadingLabel: "Loading files...",
    UploadFilesLabel: "Upload Files",
    DropFilesHereLabel: "Drop files here to upload",
    SearchPlaceholder: "Search files...",
    SelectAllLabel: "Select All",
    ClearSelectionLabel: "Clear Selection",
    DownloadSelectedLabel: "Download Selected",
    CompareLabel: "Compare",
    PreviewLabel: "Preview",
    CloseLabel: "Close",
    NextLabel: "Next",
    PreviousLabel: "Previous",
    ZoomInLabel: "Zoom In",
    ZoomOutLabel: "Zoom Out",
    ResetZoomLabel: "Reset Zoom",
    ShareLabel: "Share",
    CopyLinkLabel: "Copy Link",
    DownloadLabel: "Download",
    RenameLabel: "Rename",
    MoveLabel: "Move",
    DeleteLabel: "Delete",
    PropertiesLabel: "Properties",
    WatermarkLabel: "Confidential",
    RecentFilesLabel: "Recent Files",
    LoadMoreLabel: "Load More",
    EditModeLabel: "Configure HyperExplorer in the property pane.",

    /* File Plan component strings */
    FilePlanDashboardTitle: "File Plan Dashboard",
    FilePlanWizardTitle: "File Plan Setup Wizard",
    ApplyRetentionLabelTitle: "Apply Retention Label",
    ApplyRetentionLabelAction: "Apply Retention Label",
    RetentionLabelLabel: "Retention Label",
    FilePlanDescriptorsLabel: "File Plan Descriptors",
    LabeledLabel: "Labeled",
    UnlabeledLabel: "Unlabeled",
    CoverageLabel: "Coverage",
    LabelsInUseLabel: "Labels in Use",
    RecentActivityLabel: "Recent Activity",
    ConfigureFilePlanLabel: "Configure File Plan",
    NoLabelsAppliedLabel: "No retention labels have been applied yet.",
    SelectRetentionLabelLabel: "Select a retention label",
    ApplyLabelButton: "Apply Label",
    CancelButton: "Cancel",
    FilePlanButton: "File Plan",
    ComplianceBadgeNoLabel: "No Label",
    ComplianceBadgeExpired: "Expired",
    ComplianceBadgeLocked: "Locked",
    ComplianceBadgeRecord: "Record",
    ComplianceBadgeLabeled: "Labeled",
    WizardScopeStepTitle: "Scope",
    WizardLabelsStepTitle: "Retention Labels",
    WizardDescriptorsStepTitle: "File Plan Descriptors",
    WizardRulesStepTitle: "Auto-Classification Rules",
    PurviewPermissionHint: "Ensure the RecordsManagement.Read.All permission is granted.",

    /* Metadata Profiles & Naming */
    MetadataProfilesGroupName: "Metadata Profiles & Naming",
    EnableMetadataProfilesFieldLabel: "Enable Metadata Upload Profiles",
    EnableNamingConventionFieldLabel: "Enable File Naming Convention",
    EnableZipDownloadFieldLabel: "Enable ZIP Download Collection",
    MetadataUploadTitle: "Upload with Metadata Profile",
    NamingConventionTitle: "File Naming & Numbering Convention",
    KeyboardShortcutsTitle: "Keyboard Shortcuts",
    DemoModeLabel: "Demo Mode",
    SampleDataBannerText: "Sample data is active. Connect a document library in the property pane to use real files.",
    ProfiledUploadLabel: "Profiled Upload",
    NamingLabel: "Naming",
    UploadWithProfileAction: "Upload with Profile",
    AddToZipAction: "Add to ZIP Download",
  };
});
