define([], function () {
  return {
    PropertyPaneDescription: "Configure the HyperRollup content aggregation web part.",
    BasicGroupName: "Layout & Display",
    FeaturesGroupName: "Features",
    DataGroupName: "Data Sources",
    TitleFieldLabel: "Title",
    ViewModeFieldLabel: "View Mode",
    CardColumnsFieldLabel: "Card Columns",
    TableCompactFieldLabel: "Compact Table Rows",
    KanbanGroupFieldLabel: "Kanban Group Field",
    PageSizeFieldLabel: "Items Per Page",
    PaginationModeFieldLabel: "Pagination Mode",
    EnableFiltersLabel: "Enable Faceted Filters",
    EnableGroupingLabel: "Enable Grouping",
    GroupByFieldLabel: "Group By Field",
    EnableAggregationLabel: "Enable Aggregation Bar",
    AggregationFieldsLabel: "Aggregation Fields (JSON)",
    EnableInlineEditLabel: "Enable Inline Editing",
    EnableExportLabel: "Enable CSV Export",
    EnableDocPreviewLabel: "Enable Document Preview",
    EnableSearchLabel: "Enable Search Bar",
    SearchScopeLabel: "Search Scope (KQL)",
    EnableCustomActionsLabel: "Enable Custom Actions",
    CustomActionsLabel: "Custom Actions (JSON)",
    EnableSavedViewsLabel: "Enable Saved Views",
    SourcesFieldLabel: "Data Sources (JSON)",
    QueryFieldLabel: "Query Rules (JSON)",
    ColumnsFieldLabel: "Column Configuration (JSON)",
    EnableTemplatesLabel: "Enable Handlebars Templates",
    SelectedTemplateLabel: "Built-in Template",
    CustomTemplateLabel: "Custom Handlebars Template",
    CacheEnabledLabel: "Enable Caching",
    CacheDurationLabel: "Cache Duration (seconds)"
  };
});
