import type { IExplorerFile, IExplorerFolder, IRetentionLabel, IComplianceStatus } from "../models";

/** Sample files for demo/getting-started mode */
export function getSampleFiles(): IExplorerFile[] {
  var now = new Date().toISOString();
  var yesterday = new Date(Date.now() - 86400000).toISOString();
  var lastWeek = new Date(Date.now() - 604800000).toISOString();
  var twoWeeksAgo = new Date(Date.now() - 1209600000).toISOString();

  return [
    // Root-level files
    {
      id: "sample-1",
      name: "Quarterly Report Q4.pdf",
      serverRelativeUrl: "/sites/demo/Documents/Quarterly Report Q4.pdf",
      fileType: "pdf",
      fileCategory: "document",
      size: 2457600,
      author: "Sarah Chen",
      authorEmail: "sarah.chen@contoso.com",
      editor: "Sarah Chen",
      editorEmail: "sarah.chen@contoso.com",
      created: lastWeek,
      modified: yesterday,
      version: "3.0",
      thumbnailUrl: undefined,
      parentFolder: "",
      isFolder: false,
      contentType: "Document",
      uniqueId: "sample-uid-1",
      tags: ["finance", "quarterly"],
      description: "Q4 2024 financial results and projections",
      isImage: false,
      isVideo: false,
      isPreviewable: true,
    },
    {
      id: "sample-2",
      name: "Team Photo 2024.jpg",
      serverRelativeUrl: "/sites/demo/Documents/Team Photo 2024.jpg",
      fileType: "jpg",
      fileCategory: "image",
      size: 4915200,
      author: "Marcus Rivera",
      authorEmail: "marcus.rivera@contoso.com",
      editor: undefined,
      editorEmail: undefined,
      created: twoWeeksAgo,
      modified: twoWeeksAgo,
      version: "1.0",
      thumbnailUrl: undefined,
      parentFolder: "",
      isFolder: false,
      contentType: "Image",
      uniqueId: "sample-uid-2",
      tags: ["team", "photo"],
      description: "Annual team photo at the offsite",
      isImage: true,
      isVideo: false,
      isPreviewable: true,
    },
    {
      id: "sample-3",
      name: "Budget 2025.xlsx",
      serverRelativeUrl: "/sites/demo/Documents/Budget 2025.xlsx",
      fileType: "xlsx",
      fileCategory: "document",
      size: 1048576,
      author: "Emily Park",
      authorEmail: "emily.park@contoso.com",
      editor: "Emily Park",
      editorEmail: "emily.park@contoso.com",
      created: lastWeek,
      modified: now,
      version: "5.0",
      thumbnailUrl: undefined,
      parentFolder: "",
      isFolder: false,
      contentType: "Document",
      uniqueId: "sample-uid-3",
      tags: ["budget", "finance"],
      description: "FY2025 department budget spreadsheet",
      isImage: false,
      isVideo: false,
      isPreviewable: true,
    },
    {
      id: "sample-4",
      name: "Product Launch Deck.pptx",
      serverRelativeUrl: "/sites/demo/Documents/Product Launch Deck.pptx",
      fileType: "pptx",
      fileCategory: "document",
      size: 8388608,
      author: "David Kim",
      authorEmail: "david.kim@contoso.com",
      editor: "Sarah Chen",
      editorEmail: "sarah.chen@contoso.com",
      created: twoWeeksAgo,
      modified: lastWeek,
      version: "2.0",
      thumbnailUrl: undefined,
      parentFolder: "",
      isFolder: false,
      contentType: "Document",
      uniqueId: "sample-uid-4",
      tags: ["product", "launch"],
      description: "New product launch presentation",
      isImage: false,
      isVideo: false,
      isPreviewable: true,
    },
    {
      id: "sample-5",
      name: "Company Overview Video.mp4",
      serverRelativeUrl: "/sites/demo/Documents/Company Overview Video.mp4",
      fileType: "mp4",
      fileCategory: "video",
      size: 52428800,
      author: "Marcus Rivera",
      authorEmail: "marcus.rivera@contoso.com",
      editor: undefined,
      editorEmail: undefined,
      created: twoWeeksAgo,
      modified: twoWeeksAgo,
      version: "1.0",
      thumbnailUrl: undefined,
      parentFolder: "",
      isFolder: false,
      contentType: "Video",
      uniqueId: "sample-uid-5",
      tags: ["video", "company"],
      description: "Corporate overview video for partners",
      isImage: false,
      isVideo: true,
      isPreviewable: true,
    },
    {
      id: "sample-6",
      name: "Meeting Notes.docx",
      serverRelativeUrl: "/sites/demo/Documents/Meeting Notes.docx",
      fileType: "docx",
      fileCategory: "document",
      size: 245760,
      author: "Alex Johnson",
      authorEmail: "alex.johnson@contoso.com",
      editor: "Alex Johnson",
      editorEmail: "alex.johnson@contoso.com",
      created: yesterday,
      modified: now,
      version: "1.0",
      thumbnailUrl: undefined,
      parentFolder: "",
      isFolder: false,
      contentType: "Document",
      uniqueId: "sample-uid-6",
      tags: ["meeting", "notes"],
      description: "Weekly standup meeting notes",
      isImage: false,
      isVideo: false,
      isPreviewable: true,
    },
    // Design Assets folder files
    {
      id: "sample-7",
      name: "Logo Full Color.png",
      serverRelativeUrl: "/sites/demo/Documents/Design Assets/Logo Full Color.png",
      fileType: "png",
      fileCategory: "image",
      size: 512000,
      author: "Lisa Wang",
      authorEmail: "lisa.wang@contoso.com",
      editor: undefined,
      editorEmail: undefined,
      created: twoWeeksAgo,
      modified: lastWeek,
      version: "2.0",
      thumbnailUrl: undefined,
      parentFolder: "Design Assets",
      isFolder: false,
      contentType: "Image",
      uniqueId: "sample-uid-7",
      tags: ["design", "logo", "branding"],
      description: "Full color company logo",
      isImage: true,
      isVideo: false,
      isPreviewable: true,
    },
    {
      id: "sample-8",
      name: "Brand Guidelines.pdf",
      serverRelativeUrl: "/sites/demo/Documents/Design Assets/Brand Guidelines.pdf",
      fileType: "pdf",
      fileCategory: "document",
      size: 3145728,
      author: "Lisa Wang",
      authorEmail: "lisa.wang@contoso.com",
      editor: undefined,
      editorEmail: undefined,
      created: twoWeeksAgo,
      modified: twoWeeksAgo,
      version: "1.0",
      thumbnailUrl: undefined,
      parentFolder: "Design Assets",
      isFolder: false,
      contentType: "Document",
      uniqueId: "sample-uid-8",
      tags: ["design", "branding"],
      description: "Corporate brand guidelines and usage rules",
      isImage: false,
      isVideo: false,
      isPreviewable: true,
    },
    {
      id: "sample-9",
      name: "Hero Banner.jpg",
      serverRelativeUrl: "/sites/demo/Documents/Design Assets/Hero Banner.jpg",
      fileType: "jpg",
      fileCategory: "image",
      size: 2097152,
      author: "Lisa Wang",
      authorEmail: "lisa.wang@contoso.com",
      editor: undefined,
      editorEmail: undefined,
      created: lastWeek,
      modified: lastWeek,
      version: "1.0",
      thumbnailUrl: undefined,
      parentFolder: "Design Assets",
      isFolder: false,
      contentType: "Image",
      uniqueId: "sample-uid-9",
      tags: ["design", "banner"],
      description: "Homepage hero banner image",
      isImage: true,
      isVideo: false,
      isPreviewable: true,
    },
    // Reports folder files
    {
      id: "sample-10",
      name: "Sales Dashboard.xlsx",
      serverRelativeUrl: "/sites/demo/Documents/Reports/Sales Dashboard.xlsx",
      fileType: "xlsx",
      fileCategory: "document",
      size: 1572864,
      author: "Emily Park",
      authorEmail: "emily.park@contoso.com",
      editor: "Emily Park",
      editorEmail: "emily.park@contoso.com",
      created: lastWeek,
      modified: yesterday,
      version: "4.0",
      thumbnailUrl: undefined,
      parentFolder: "Reports",
      isFolder: false,
      contentType: "Document",
      uniqueId: "sample-uid-10",
      tags: ["sales", "dashboard"],
      description: "Monthly sales dashboard with charts",
      isImage: false,
      isVideo: false,
      isPreviewable: true,
    },
    {
      id: "sample-11",
      name: "Annual Review 2024.pdf",
      serverRelativeUrl: "/sites/demo/Documents/Reports/Annual Review 2024.pdf",
      fileType: "pdf",
      fileCategory: "document",
      size: 5242880,
      author: "Sarah Chen",
      authorEmail: "sarah.chen@contoso.com",
      editor: undefined,
      editorEmail: undefined,
      created: twoWeeksAgo,
      modified: twoWeeksAgo,
      version: "1.0",
      thumbnailUrl: undefined,
      parentFolder: "Reports",
      isFolder: false,
      contentType: "Document",
      uniqueId: "sample-uid-11",
      tags: ["annual", "review"],
      description: "2024 annual company review and performance summary",
      isImage: false,
      isVideo: false,
      isPreviewable: true,
    },
    // Videos folder
    {
      id: "sample-12",
      name: "Training Session 1.mp4",
      serverRelativeUrl: "/sites/demo/Documents/Videos/Training Session 1.mp4",
      fileType: "mp4",
      fileCategory: "video",
      size: 104857600,
      author: "David Kim",
      authorEmail: "david.kim@contoso.com",
      editor: undefined,
      editorEmail: undefined,
      created: lastWeek,
      modified: lastWeek,
      version: "1.0",
      thumbnailUrl: undefined,
      parentFolder: "Videos",
      isFolder: false,
      contentType: "Video",
      uniqueId: "sample-uid-12",
      tags: ["training", "video"],
      description: "Onboarding training session recording",
      isImage: false,
      isVideo: true,
      isPreviewable: true,
    },
    // Archive
    {
      id: "sample-13",
      name: "Project Assets.zip",
      serverRelativeUrl: "/sites/demo/Documents/Project Assets.zip",
      fileType: "zip",
      fileCategory: "archive",
      size: 15728640,
      author: "Alex Johnson",
      authorEmail: "alex.johnson@contoso.com",
      editor: undefined,
      editorEmail: undefined,
      created: lastWeek,
      modified: lastWeek,
      version: "1.0",
      thumbnailUrl: undefined,
      parentFolder: "",
      isFolder: false,
      contentType: "Document",
      uniqueId: "sample-uid-13",
      tags: ["project", "assets"],
      description: "Bundled project deliverables",
      isImage: false,
      isVideo: false,
      isPreviewable: false,
    },
    // OneNote
    {
      id: "sample-14",
      name: "Brainstorm Ideas.one",
      serverRelativeUrl: "/sites/demo/Documents/Brainstorm Ideas.one",
      fileType: "one",
      fileCategory: "document",
      size: 327680,
      author: "Marcus Rivera",
      authorEmail: "marcus.rivera@contoso.com",
      editor: "Marcus Rivera",
      editorEmail: "marcus.rivera@contoso.com",
      created: yesterday,
      modified: now,
      version: "1.0",
      thumbnailUrl: undefined,
      parentFolder: "",
      isFolder: false,
      contentType: "Document",
      uniqueId: "sample-uid-14",
      tags: ["brainstorm", "ideas"],
      description: "Team brainstorming notes from ideation session",
      isImage: false,
      isVideo: false,
      isPreviewable: true,
    },
    // SVG
    {
      id: "sample-15",
      name: "Org Chart.svg",
      serverRelativeUrl: "/sites/demo/Documents/Design Assets/Org Chart.svg",
      fileType: "svg",
      fileCategory: "image",
      size: 65536,
      author: "Lisa Wang",
      authorEmail: "lisa.wang@contoso.com",
      editor: undefined,
      editorEmail: undefined,
      created: lastWeek,
      modified: lastWeek,
      version: "1.0",
      thumbnailUrl: undefined,
      parentFolder: "Design Assets",
      isFolder: false,
      contentType: "Image",
      uniqueId: "sample-uid-15",
      tags: ["org", "chart", "design"],
      description: "Organization chart graphic",
      isImage: true,
      isVideo: false,
      isPreviewable: true,
    },
  ];
}

/** Sample folders */
export function getSampleFolders(): IExplorerFolder[] {
  return [
    { path: "Design Assets", name: "Design Assets", itemCount: 4, parent: "", level: 0, isExpanded: false },
    { path: "Reports", name: "Reports", itemCount: 2, parent: "", level: 0, isExpanded: false },
    { path: "Videos", name: "Videos", itemCount: 1, parent: "", level: 0, isExpanded: false },
  ];
}

/** Get sample files filtered to a given folder (empty string = root) */
export function getSampleFilesForFolder(folder: string): IExplorerFile[] {
  return getSampleFiles().filter(function (f) {
    return f.parentFolder === folder;
  });
}

// ── File Plan Sample Data ──

/** Sample MS Purview retention labels for demo mode */
export function getSampleRetentionLabels(): IRetentionLabel[] {
  return [
    {
      id: "label-finance",
      displayName: "Finance Records",
      descriptionForAdmins: "Financial documents - 7 year retention per SOX compliance",
      descriptionForUsers: "Apply to financial reports, invoices, and budgets",
      isInUse: true,
      retentionDuration: 2555,
      actionAfterRetentionPeriod: "startDispositionReview",
      behaviorDuringRetentionPeriod: "retainAsRecord",
      defaultRecordBehavior: "startLocked",
    },
    {
      id: "label-legal",
      displayName: "Legal Hold",
      descriptionForAdmins: "Legal hold - indefinite retention for active litigation",
      descriptionForUsers: "Apply to documents under legal investigation or litigation hold",
      isInUse: true,
      retentionDuration: 0,
      actionAfterRetentionPeriod: "none",
      behaviorDuringRetentionPeriod: "retainAsRegulatoryRecord",
      defaultRecordBehavior: "startLocked",
    },
    {
      id: "label-temp",
      displayName: "Temporary Storage",
      descriptionForAdmins: "Temporary files - 90 day retention then auto-delete",
      descriptionForUsers: "Apply to draft documents and temporary files",
      isInUse: true,
      retentionDuration: 90,
      actionAfterRetentionPeriod: "delete",
      behaviorDuringRetentionPeriod: "retain",
      defaultRecordBehavior: "startUnlocked",
    },
    {
      id: "label-hr",
      displayName: "HR Personnel Files",
      descriptionForAdmins: "Employee records - 10 year retention per labor law",
      descriptionForUsers: "Apply to employment contracts, reviews, and personnel documents",
      isInUse: true,
      retentionDuration: 3650,
      actionAfterRetentionPeriod: "startDispositionReview",
      behaviorDuringRetentionPeriod: "retainAsRecord",
      defaultRecordBehavior: "startLocked",
    },
    {
      id: "label-marketing",
      displayName: "Marketing Materials",
      descriptionForAdmins: "Marketing content - 3 year retention then auto-delete",
      descriptionForUsers: "Apply to marketing campaigns, collateral, and creative assets",
      isInUse: true,
      retentionDuration: 1095,
      actionAfterRetentionPeriod: "delete",
      behaviorDuringRetentionPeriod: "retain",
      defaultRecordBehavior: "startUnlocked",
    },
  ];
}

/** Sample compliance statuses mapped to sample file IDs */
export function getSampleComplianceStatuses(): Record<string, IComplianceStatus> {
  var now = Date.now();
  var DAY = 86400000;
  var thirtyDaysAgo = new Date(now - 30 * DAY).toISOString();
  var sixtyDaysAgo = new Date(now - 60 * DAY).toISOString();
  var sevenYears = new Date(now + 2555 * DAY).toISOString();
  var thirtyDays = new Date(now + 30 * DAY).toISOString();
  var tenYears = new Date(now + 3650 * DAY).toISOString();

  var statuses: Record<string, IComplianceStatus> = {};

  // sample-1: Quarterly Report Q4.pdf → Finance Records (locked record)
  statuses["sample-1"] = {
    fileId: "sample-1",
    labelId: "label-finance",
    labelName: "Finance Records",
    appliedDate: thirtyDaysAgo,
    appliedBy: "Sarah Chen",
    expirationDate: sevenYears,
    isRecord: true,
    isLocked: true,
    descriptors: {
      functionOrActivity: "Finance",
      department: "Accounting",
      category: "Financial Reports",
      authorityType: "Regulatory",
      provision: "SOX Section 802",
    },
  };

  // sample-3: Budget 2025.xlsx → Temporary Storage (expiring soon)
  statuses["sample-3"] = {
    fileId: "sample-3",
    labelId: "label-temp",
    labelName: "Temporary Storage",
    appliedDate: sixtyDaysAgo,
    appliedBy: "Emily Park",
    expirationDate: thirtyDays,
    isRecord: false,
    isLocked: false,
  };

  // sample-6: Meeting Notes.docx → Legal Hold (regulatory record, locked)
  statuses["sample-6"] = {
    fileId: "sample-6",
    labelId: "label-legal",
    labelName: "Legal Hold",
    appliedDate: thirtyDaysAgo,
    appliedBy: "Alex Johnson",
    expirationDate: undefined,
    isRecord: true,
    isLocked: true,
    descriptors: {
      functionOrActivity: "Legal",
      department: "Legal Affairs",
      category: "Litigation Hold",
    },
  };

  // sample-10: Sales Dashboard.xlsx → Finance Records
  statuses["sample-10"] = {
    fileId: "sample-10",
    labelId: "label-finance",
    labelName: "Finance Records",
    appliedDate: thirtyDaysAgo,
    appliedBy: "Emily Park",
    expirationDate: sevenYears,
    isRecord: true,
    isLocked: true,
    descriptors: {
      functionOrActivity: "Finance",
      department: "Sales",
      category: "Sales Reports",
    },
  };

  // sample-8: Brand Guidelines.pdf → Marketing Materials
  statuses["sample-8"] = {
    fileId: "sample-8",
    labelId: "label-marketing",
    labelName: "Marketing Materials",
    appliedDate: sixtyDaysAgo,
    appliedBy: "Lisa Wang",
    expirationDate: new Date(now + 1095 * DAY).toISOString(),
    isRecord: false,
    isLocked: false,
    descriptors: {
      functionOrActivity: "Marketing",
      department: "Creative",
      category: "Brand Assets",
    },
  };

  // sample-11: Annual Review 2024.pdf → HR Personnel Files
  statuses["sample-11"] = {
    fileId: "sample-11",
    labelId: "label-hr",
    labelName: "HR Personnel Files",
    appliedDate: thirtyDaysAgo,
    appliedBy: "Sarah Chen",
    expirationDate: tenYears,
    isRecord: true,
    isLocked: true,
    descriptors: {
      functionOrActivity: "Human Resources",
      department: "HR",
      category: "Annual Reviews",
      authorityType: "Labor Law",
    },
  };

  return statuses;
}
