import type { IHyperEvent } from "../models";

// ============================================================
// SAMPLE EVENTS — Rich calendar events for demo / preview
// ============================================================

/**
 * Returns a set of sample events distributed around the current date.
 * Events span from 2 weeks ago to 6 weeks in the future so the calendar
 * always looks populated regardless of the view mode.
 */
export function getSampleEvents(): IHyperEvent[] {
  var now = new Date();
  var year = now.getFullYear();
  var month = now.getMonth();
  var day = now.getDate();

  /** Helper: create a Date relative to today */
  function rel(dayOffset: number, hour: number, minute: number): string {
    var d = new Date(year, month, day + dayOffset, hour, minute, 0);
    return d.toISOString();
  }

  /** Helper: all-day event (midnight to midnight next day) */
  function allDay(dayOffset: number): { start: string; end: string } {
    var d1 = new Date(year, month, day + dayOffset, 0, 0, 0);
    var d2 = new Date(year, month, day + dayOffset + 1, 0, 0, 0);
    return { start: d1.toISOString(), end: d2.toISOString() };
  }

  var events: IHyperEvent[] = [
    // ── Today ──
    {
      id: "sample-1",
      title: "All-Hands Company Meeting",
      description: "Quarterly all-hands with the CEO. Topics include Q4 results, new product launches, and the company vision for 2026. All employees are expected to attend. Refreshments will be served in the lobby after the meeting.",
      startDate: rel(0, 10, 0),
      endDate: rel(0, 11, 30),
      isAllDay: false,
      location: "Main Auditorium, Building A",
      category: "Meeting",
      categoryColor: "#0078d4",
      organizer: "Sarah Chen",
      organizerEmail: "sarah.chen@contoso.com",
      attendees: [
        { name: "Sarah Chen", email: "sarah.chen@contoso.com", response: "accepted" },
        { name: "James Wilson", email: "james.wilson@contoso.com", response: "accepted" },
        { name: "Maria Lopez", email: "maria.lopez@contoso.com", response: "tentative" },
      ],
      recurrence: undefined,
      isRecurring: false,
      seriesMasterId: undefined,
      teamsJoinUrl: "https://teams.microsoft.com/l/meetup-join/sample1",
      webLink: undefined,
      sourceId: "sample-source-1",
      sourceColor: "#0078d4",
      imageUrl: undefined,
      registrationEnabled: false,
      rsvpEnabled: true,
      rsvpCounts: { going: 142, maybe: 23, declined: 5 },
    },
    {
      id: "sample-2",
      title: "Sprint Planning",
      description: "Plan the upcoming sprint backlog. Review velocity, capacity, and priority items from the product backlog.",
      startDate: rel(0, 14, 0),
      endDate: rel(0, 15, 0),
      isAllDay: false,
      location: undefined,
      category: "Meeting",
      categoryColor: "#0078d4",
      organizer: "Dev Team",
      organizerEmail: "devteam@contoso.com",
      attendees: [
        { name: "Alex Rivera", email: "alex.rivera@contoso.com", response: "accepted" },
        { name: "Kim Patel", email: "kim.patel@contoso.com", response: "accepted" },
      ],
      recurrence: { pattern: "weekly", interval: 2, daysOfWeek: ["monday"], dayOfMonth: undefined, month: undefined, index: undefined, startDate: rel(-14, 14, 0), endDate: undefined, numberOfOccurrences: undefined },
      isRecurring: true,
      seriesMasterId: "sample-2-master",
      teamsJoinUrl: "https://teams.microsoft.com/l/meetup-join/sample2",
      webLink: undefined,
      sourceId: "sample-source-1",
      sourceColor: "#0078d4",
      imageUrl: undefined,
      registrationEnabled: false,
      rsvpEnabled: false,
      rsvpCounts: undefined,
    },

    // ── Tomorrow ──
    {
      id: "sample-3",
      title: "New Employee Orientation",
      description: "Welcome session for new hires. Covers company culture, benefits overview, IT setup, and team introductions. Badge photos will be taken at 11 AM.",
      startDate: rel(1, 9, 0),
      endDate: rel(1, 12, 0),
      isAllDay: false,
      location: "HR Training Room, Floor 3",
      category: "Training",
      categoryColor: "#107c10",
      organizer: "HR Department",
      organizerEmail: "hr@contoso.com",
      attendees: [],
      recurrence: undefined,
      isRecurring: false,
      seriesMasterId: undefined,
      teamsJoinUrl: undefined,
      webLink: undefined,
      sourceId: "sample-source-2",
      sourceColor: "#107c10",
      imageUrl: undefined,
      registrationEnabled: true,
      rsvpEnabled: true,
      rsvpCounts: { going: 8, maybe: 2, declined: 0 },
    },
    {
      id: "sample-4",
      title: "Lunch & Learn: AI in the Workplace",
      description: "Join us for a casual session on how AI tools are transforming productivity. Pizza provided! Learn about Copilot integration, prompt engineering best practices, and ethical AI usage guidelines.",
      startDate: rel(1, 12, 0),
      endDate: rel(1, 13, 0),
      isAllDay: false,
      location: "Cafeteria, Building B",
      category: "Training",
      categoryColor: "#107c10",
      organizer: "Tech Council",
      organizerEmail: "techcouncil@contoso.com",
      attendees: [],
      recurrence: undefined,
      isRecurring: false,
      seriesMasterId: undefined,
      teamsJoinUrl: "https://teams.microsoft.com/l/meetup-join/sample4",
      webLink: undefined,
      sourceId: "sample-source-2",
      sourceColor: "#107c10",
      imageUrl: undefined,
      registrationEnabled: true,
      rsvpEnabled: true,
      rsvpCounts: { going: 45, maybe: 12, declined: 3 },
    },

    // ── This week ──
    {
      id: "sample-5",
      title: "Team Happy Hour",
      description: "Casual drinks and snacks at the rooftop lounge. Celebrate the successful product launch! Bring your team spirit.",
      startDate: rel(3, 17, 0),
      endDate: rel(3, 19, 0),
      isAllDay: false,
      location: "Rooftop Lounge, Building A",
      category: "Social",
      categoryColor: "#d83b01",
      organizer: "Culture Committee",
      organizerEmail: "culture@contoso.com",
      attendees: [],
      recurrence: undefined,
      isRecurring: false,
      seriesMasterId: undefined,
      teamsJoinUrl: undefined,
      webLink: undefined,
      sourceId: "sample-source-1",
      sourceColor: "#0078d4",
      imageUrl: undefined,
      registrationEnabled: false,
      rsvpEnabled: true,
      rsvpCounts: { going: 67, maybe: 15, declined: 8 },
    },
    {
      id: "sample-6",
      title: "Q4 Budget Review Deadline",
      description: "All department heads must submit their Q4 budget proposals by end of day. Use the Budget Portal on the Finance intranet site.",
      startDate: allDay(4).start,
      endDate: allDay(4).end,
      isAllDay: true,
      location: undefined,
      category: "Deadline",
      categoryColor: "#8764b8",
      organizer: "Finance",
      organizerEmail: "finance@contoso.com",
      attendees: [],
      recurrence: undefined,
      isRecurring: false,
      seriesMasterId: undefined,
      teamsJoinUrl: undefined,
      webLink: undefined,
      sourceId: "sample-source-1",
      sourceColor: "#0078d4",
      imageUrl: undefined,
      registrationEnabled: false,
      rsvpEnabled: false,
      rsvpCounts: undefined,
    },

    // ── Next week ──
    {
      id: "sample-7",
      title: "Cybersecurity Awareness Workshop",
      description: "Mandatory training on phishing prevention, password security, and data protection policies. Interactive exercises and a quiz at the end.",
      startDate: rel(7, 10, 0),
      endDate: rel(7, 12, 0),
      isAllDay: false,
      location: "Virtual (Teams)",
      category: "Training",
      categoryColor: "#107c10",
      organizer: "IT Security",
      organizerEmail: "itsec@contoso.com",
      attendees: [],
      recurrence: undefined,
      isRecurring: false,
      seriesMasterId: undefined,
      teamsJoinUrl: "https://teams.microsoft.com/l/meetup-join/sample7",
      webLink: undefined,
      sourceId: "sample-source-2",
      sourceColor: "#107c10",
      imageUrl: undefined,
      registrationEnabled: true,
      rsvpEnabled: true,
      rsvpCounts: { going: 89, maybe: 34, declined: 12 },
    },
    {
      id: "sample-8",
      title: "Product Demo Day",
      description: "Engineering teams showcase their latest features and prototypes. Live demos followed by Q&A. Vote for your favorite innovation!",
      startDate: rel(8, 14, 0),
      endDate: rel(8, 16, 30),
      isAllDay: false,
      location: "Innovation Lab, Floor 5",
      category: "Social",
      categoryColor: "#d83b01",
      organizer: "Engineering",
      organizerEmail: "engineering@contoso.com",
      attendees: [],
      recurrence: undefined,
      isRecurring: false,
      seriesMasterId: undefined,
      teamsJoinUrl: "https://teams.microsoft.com/l/meetup-join/sample8",
      webLink: undefined,
      sourceId: "sample-source-1",
      sourceColor: "#0078d4",
      imageUrl: undefined,
      registrationEnabled: false,
      rsvpEnabled: true,
      rsvpCounts: { going: 56, maybe: 18, declined: 2 },
    },
    {
      id: "sample-9",
      title: "Board of Directors Meeting",
      description: "Quarterly board meeting covering financial performance, strategic initiatives, and risk management updates.",
      startDate: rel(9, 9, 0),
      endDate: rel(9, 12, 0),
      isAllDay: false,
      location: "Executive Boardroom, Floor 10",
      category: "Meeting",
      categoryColor: "#0078d4",
      organizer: "Executive Office",
      organizerEmail: "exec@contoso.com",
      attendees: [
        { name: "CEO", email: "ceo@contoso.com", response: "accepted" },
        { name: "CFO", email: "cfo@contoso.com", response: "accepted" },
        { name: "CTO", email: "cto@contoso.com", response: "accepted" },
      ],
      recurrence: undefined,
      isRecurring: false,
      seriesMasterId: undefined,
      teamsJoinUrl: undefined,
      webLink: undefined,
      sourceId: "sample-source-3",
      sourceColor: "#8764b8",
      imageUrl: undefined,
      registrationEnabled: false,
      rsvpEnabled: false,
      rsvpCounts: undefined,
    },

    // ── 2 weeks out ──
    {
      id: "sample-10",
      title: "Summer Company Picnic",
      description: "Annual outdoor event with BBQ, games, live music, and activities for the whole family. Shuttle buses available from all office locations.",
      startDate: rel(14, 11, 0),
      endDate: rel(14, 17, 0),
      isAllDay: false,
      location: "Riverside Park Pavilion",
      category: "Social",
      categoryColor: "#d83b01",
      organizer: "Events Team",
      organizerEmail: "events@contoso.com",
      attendees: [],
      recurrence: undefined,
      isRecurring: false,
      seriesMasterId: undefined,
      teamsJoinUrl: undefined,
      webLink: undefined,
      sourceId: "sample-source-1",
      sourceColor: "#0078d4",
      imageUrl: undefined,
      registrationEnabled: true,
      rsvpEnabled: true,
      rsvpCounts: { going: 234, maybe: 56, declined: 12 },
    },
    {
      id: "sample-11",
      title: "Martin Luther King Jr. Day",
      description: "Office closed for Martin Luther King Jr. Day. Enjoy the holiday!",
      startDate: allDay(15).start,
      endDate: allDay(15).end,
      isAllDay: true,
      location: undefined,
      category: "Holiday",
      categoryColor: "#ff8c00",
      organizer: "HR Department",
      organizerEmail: "hr@contoso.com",
      attendees: [],
      recurrence: undefined,
      isRecurring: false,
      seriesMasterId: undefined,
      teamsJoinUrl: undefined,
      webLink: undefined,
      sourceId: "sample-source-1",
      sourceColor: "#0078d4",
      imageUrl: undefined,
      registrationEnabled: false,
      rsvpEnabled: false,
      rsvpCounts: undefined,
    },

    // ── 3-4 weeks out ──
    {
      id: "sample-12",
      title: "Leadership Development Program Kickoff",
      description: "6-month program for emerging leaders. Covers strategic thinking, team management, executive communication, and change management. Applications close next Friday.",
      startDate: rel(21, 9, 0),
      endDate: rel(21, 17, 0),
      isAllDay: false,
      location: "Conference Center, Campus West",
      category: "Training",
      categoryColor: "#107c10",
      organizer: "L&D Team",
      organizerEmail: "learning@contoso.com",
      attendees: [],
      recurrence: undefined,
      isRecurring: false,
      seriesMasterId: undefined,
      teamsJoinUrl: undefined,
      webLink: undefined,
      sourceId: "sample-source-2",
      sourceColor: "#107c10",
      imageUrl: undefined,
      registrationEnabled: true,
      rsvpEnabled: true,
      rsvpCounts: { going: 24, maybe: 8, declined: 1 },
    },
    {
      id: "sample-13",
      title: "Annual Charity Fundraiser Gala",
      description: "Black-tie event supporting local education initiatives. Silent auction, dinner, and keynote speaker from the United Way. Tables available for department sponsorship.",
      startDate: rel(28, 18, 0),
      endDate: rel(28, 22, 0),
      isAllDay: false,
      location: "Grand Ballroom, Marriott Downtown",
      category: "Social",
      categoryColor: "#d83b01",
      organizer: "CSR Committee",
      organizerEmail: "csr@contoso.com",
      attendees: [],
      recurrence: undefined,
      isRecurring: false,
      seriesMasterId: undefined,
      teamsJoinUrl: undefined,
      webLink: undefined,
      sourceId: "sample-source-1",
      sourceColor: "#0078d4",
      imageUrl: undefined,
      registrationEnabled: true,
      rsvpEnabled: true,
      rsvpCounts: { going: 178, maybe: 45, declined: 22 },
    },

    // ── Past events (last week) ──
    {
      id: "sample-14",
      title: "Weekly Standup",
      description: "Regular team standup to review progress, blockers, and upcoming priorities.",
      startDate: rel(-2, 9, 30),
      endDate: rel(-2, 9, 45),
      isAllDay: false,
      location: undefined,
      category: "Meeting",
      categoryColor: "#0078d4",
      organizer: "Team Lead",
      organizerEmail: "lead@contoso.com",
      attendees: [],
      recurrence: { pattern: "weekly", interval: 1, daysOfWeek: ["monday", "wednesday", "friday"], dayOfMonth: undefined, month: undefined, index: undefined, startDate: rel(-30, 9, 30), endDate: undefined, numberOfOccurrences: undefined },
      isRecurring: true,
      seriesMasterId: "sample-14-master",
      teamsJoinUrl: "https://teams.microsoft.com/l/meetup-join/sample14",
      webLink: undefined,
      sourceId: "sample-source-1",
      sourceColor: "#0078d4",
      imageUrl: undefined,
      registrationEnabled: false,
      rsvpEnabled: false,
      rsvpCounts: undefined,
    },
    {
      id: "sample-15",
      title: "Fire Safety Drill",
      description: "Mandatory fire drill for all floors. Please proceed to your designated assembly point when the alarm sounds.",
      startDate: rel(-5, 14, 0),
      endDate: rel(-5, 14, 30),
      isAllDay: false,
      location: "All Buildings",
      category: "Other",
      categoryColor: "#00b7c3",
      organizer: "Facilities",
      organizerEmail: "facilities@contoso.com",
      attendees: [],
      recurrence: undefined,
      isRecurring: false,
      seriesMasterId: undefined,
      teamsJoinUrl: undefined,
      webLink: undefined,
      sourceId: "sample-source-1",
      sourceColor: "#0078d4",
      imageUrl: undefined,
      registrationEnabled: false,
      rsvpEnabled: false,
      rsvpCounts: undefined,
    },

    // ── Recurring weekly ──
    {
      id: "sample-16",
      title: "Yoga & Wellness Session",
      description: "Weekly yoga session open to all employees. Mats and water provided. Beginner-friendly!",
      startDate: rel(2, 7, 30),
      endDate: rel(2, 8, 15),
      isAllDay: false,
      location: "Wellness Studio, Floor 1",
      category: "Social",
      categoryColor: "#d83b01",
      organizer: "Wellness Program",
      organizerEmail: "wellness@contoso.com",
      attendees: [],
      recurrence: { pattern: "weekly", interval: 1, daysOfWeek: ["wednesday"], dayOfMonth: undefined, month: undefined, index: undefined, startDate: rel(-60, 7, 30), endDate: undefined, numberOfOccurrences: undefined },
      isRecurring: true,
      seriesMasterId: "sample-16-master",
      teamsJoinUrl: undefined,
      webLink: undefined,
      sourceId: "sample-source-3",
      sourceColor: "#8764b8",
      imageUrl: undefined,
      registrationEnabled: false,
      rsvpEnabled: true,
      rsvpCounts: { going: 18, maybe: 5, declined: 0 },
    },

    // ── Project deadline ──
    {
      id: "sample-17",
      title: "Project Aurora Go-Live",
      description: "Production deployment of Project Aurora. All hands on deck for monitoring. War room setup in Conference Room A from 6 AM.",
      startDate: allDay(10).start,
      endDate: allDay(10).end,
      isAllDay: true,
      location: undefined,
      category: "Deadline",
      categoryColor: "#8764b8",
      organizer: "Project Aurora Team",
      organizerEmail: "aurora@contoso.com",
      attendees: [],
      recurrence: undefined,
      isRecurring: false,
      seriesMasterId: undefined,
      teamsJoinUrl: "https://teams.microsoft.com/l/meetup-join/sample17",
      webLink: undefined,
      sourceId: "sample-source-1",
      sourceColor: "#0078d4",
      imageUrl: undefined,
      registrationEnabled: false,
      rsvpEnabled: false,
      rsvpCounts: undefined,
    },

    // ── Multi-day conference ──
    {
      id: "sample-18",
      title: "Annual Sales Kickoff Conference",
      description: "3-day conference with keynotes, breakout sessions, partner showcases, and networking dinners. Travel and accommodation details sent separately.",
      startDate: rel(35, 8, 0),
      endDate: rel(37, 17, 0),
      isAllDay: false,
      location: "Hyatt Regency Convention Center",
      category: "Training",
      categoryColor: "#107c10",
      organizer: "Sales Operations",
      organizerEmail: "salesops@contoso.com",
      attendees: [],
      recurrence: undefined,
      isRecurring: false,
      seriesMasterId: undefined,
      teamsJoinUrl: undefined,
      webLink: undefined,
      sourceId: "sample-source-2",
      sourceColor: "#107c10",
      imageUrl: undefined,
      registrationEnabled: true,
      rsvpEnabled: true,
      rsvpCounts: { going: 312, maybe: 28, declined: 15 },
    },
  ];

  return events;
}

/** Returns sample source definitions matching the sample events */
export function getSampleSources(): Array<{ id: string; displayName: string; color: string }> {
  return [
    { id: "sample-source-1", displayName: "Company Calendar", color: "#0078d4" },
    { id: "sample-source-2", displayName: "Training & Development", color: "#107c10" },
    { id: "sample-source-3", displayName: "Wellness & Social", color: "#8764b8" },
  ];
}

/** Returns unique categories present in sample data */
export function getSampleCategories(): string[] {
  return ["Meeting", "Training", "Social", "Deadline", "Holiday", "Other"];
}
