define([], function () {
  return {
    PropertyPaneDescription: "Configure the HyperPoll in-page voting and polling web part.",
    GeneralGroupName: "General",
    FeaturesGroupName: "Features",
    PollManagementGroupName: "Poll Management",
    TitleFieldLabel: "Title",
    DisplayModeFieldLabel: "Display Mode",
    DefaultChartTypeFieldLabel: "Default Chart Type",
    ShowInlineResultsLabel: "Show Results Inline After Voting",
    ApplyTemplateLabel: "Apply Template",
    ApplyTemplateNone: "None (start blank)",
    EnableExportLabel: "Enable CSV/JSON Export",
    RefreshIntervalFieldLabel: "Auto-Refresh Interval (seconds, 0 = off)",
    CacheDurationFieldLabel: "Cache Duration (seconds)",
    ResponseListNameLabel: "Response List Name",
    FeaturesPageDescription: "Toggle polling features and capabilities.",
    DataPageDescription: "Manage polls, questions, and options.",
    DisplayModeCarousel: "Carousel",
    DisplayModeStacked: "Stacked",
    ChartTypeBar: "Bar",
    ChartTypePie: "Pie",
    ChartTypeDonut: "Donut",
    // Poll management
    PollHeaderPrefix: "Poll",
    PollTitleLabel: "Poll Title",
    PollDescriptionLabel: "Description",
    PollStatusLabel: "Status",
    PollAnonymousLabel: "Anonymous Voting",
    PollResultsVisibilityLabel: "Results Visibility",
    PollStartDateLabel: "Start Date (ISO 8601)",
    PollEndDateLabel: "End Date (ISO 8601)",
    AddPollLabel: "Add Poll",
    RemovePollLabel: "Remove",
    MoveUpLabel: "Move Up",
    MoveDownLabel: "Move Down",
    // Question management
    QuestionHeaderPrefix: "Question",
    QuestionTextLabel: "Question Text",
    QuestionTypeLabel: "Question Type",
    QuestionRequiredLabel: "Required",
    QuestionRatingMaxLabel: "Max Rating",
    AddQuestionLabel: "Add Question",
    RemoveQuestionLabel: "Remove",
    // Option management
    OptionHeaderPrefix: "Option",
    OptionTextLabel: "Option Text",
    OptionColorLabel: "Color",
    AddOptionLabel: "Add Option",
    RemoveOptionLabel: "Remove",
    // Status options
    StatusDraft: "Draft",
    StatusActive: "Active",
    StatusClosed: "Closed",
    StatusArchived: "Archived",
    // Results visibility options
    VisibilityAfterVote: "After Vote",
    VisibilityAfterClose: "After Close",
    VisibilityAdminOnly: "Admin Only",
    // Question type options
    TypeSingleChoice: "Single Choice",
    TypeMultipleChoice: "Multiple Choice",
    TypeRating: "Rating",
    TypeNps: "NPS (0-10)",
    TypeRanking: "Ranking",
    TypeOpenText: "Open Text",
    // Template names
    TemplateNpsSurvey: "NPS Survey",
    TemplateEventFeedback: "Event Feedback",
    TemplateQuickPulse: "Quick Pulse",
    // Wizard & Demo
    WizardGroupName: "Wizard & Demo",
    ShowWizardOnInitLabel: "Show Setup Wizard on First Load",
    UseSampleDataLabel: "Use Sample Data (Preview Mode)",
    EnableDemoModeLabel: "Enable Demo Control Bar"
  };
});
