import type { IOnboardTask, IOnboardMilestone, IOnboardResource } from "../models";

export var SAMPLE_TASKS: IOnboardTask[] = [
  // ── PREBOARDING (3 tasks) ──
  {
    id: "task-001",
    title: "Complete pre-employment forms",
    description: "Fill out tax forms, banking details, and emergency contacts via the HR portal.",
    phase: "preboarding",
    taskType: "document",
    priority: "critical",
    dueDaysOffset: -7,
    isLocked: false,
    isCompleted: true,
    completedDate: new Date(Date.now() - 8 * 86400000).toISOString(),
    order: 1,
  },
  {
    id: "task-002",
    title: "Watch welcome video from the CEO",
    description: "A 5-minute video from our MD Michael Botha welcoming you to First Digital.",
    phase: "preboarding",
    taskType: "learning",
    priority: "normal",
    dueDaysOffset: -5,
    isLocked: false,
    isCompleted: true,
    completedDate: new Date(Date.now() - 6 * 86400000).toISOString(),
    order: 2,
  },
  {
    id: "task-003",
    title: "Set up your Microsoft 365 account",
    description: "Follow the IT setup guide to configure Outlook, Teams, and OneDrive.",
    phase: "preboarding",
    taskType: "action",
    priority: "critical",
    dueDaysOffset: -3,
    isLocked: false,
    isCompleted: true,
    completedDate: new Date(Date.now() - 4 * 86400000).toISOString(),
    order: 3,
  },
  // ── WEEK 1 (4 tasks) ──
  {
    id: "task-004",
    title: "Meet your onboarding buddy",
    description: "Schedule a 30-minute coffee chat with your assigned buddy to learn the ropes.",
    phase: "week1",
    taskType: "meeting",
    priority: "high",
    dueDaysOffset: 1,
    isLocked: false,
    isCompleted: true,
    completedDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    order: 1,
  },
  {
    id: "task-005",
    title: "Complete IT security training",
    description: "Mandatory cybersecurity awareness course covering phishing, password hygiene, and data protection.",
    phase: "week1",
    taskType: "learning",
    priority: "critical",
    dueDaysOffset: 3,
    isLocked: false,
    isCompleted: false,
    order: 2,
  },
  {
    id: "task-006",
    title: "Attend team standup",
    description: "Join the daily team standup meeting to meet your colleagues and understand current projects.",
    phase: "week1",
    taskType: "meeting",
    priority: "normal",
    dueDaysOffset: 2,
    isLocked: false,
    isCompleted: false,
    order: 3,
  },
  {
    id: "task-007",
    title: "Complete HR orientation survey",
    description: "Share your first impressions and any concerns with the HR team.",
    phase: "week1",
    taskType: "survey",
    priority: "normal",
    dueDaysOffset: 5,
    dependsOnTaskId: "task-004",
    isLocked: false,
    isCompleted: false,
    order: 4,
  },
  // ── MONTH 1 (3 tasks) ──
  {
    id: "task-008",
    title: "Complete compliance training modules",
    description: "POPIA data protection, workplace health & safety, and code of conduct.",
    phase: "month1",
    taskType: "learning",
    priority: "high",
    dueDaysOffset: 14,
    isLocked: false,
    isCompleted: false,
    order: 1,
  },
  {
    id: "task-009",
    title: "Schedule 1:1 with your line manager",
    description: "Set up a weekly recurring 1:1 to discuss goals, expectations, and feedback.",
    phase: "month1",
    taskType: "meeting",
    priority: "high",
    dueDaysOffset: 10,
    isLocked: false,
    isCompleted: false,
    order: 2,
  },
  {
    id: "task-010",
    title: "Submit 30-day check-in form",
    description: "Reflect on your first month and share feedback with HR.",
    phase: "month1",
    taskType: "survey",
    priority: "normal",
    dueDaysOffset: 30,
    dependsOnTaskId: "task-008",
    isLocked: true,
    isCompleted: false,
    order: 3,
  },
  // ── MONTH 3 (3 tasks) ──
  {
    id: "task-011",
    title: "Complete role-specific certification",
    description: "Earn your first professional certification relevant to your role.",
    phase: "month3",
    taskType: "learning",
    priority: "high",
    dueDaysOffset: 60,
    isLocked: false,
    isCompleted: false,
    order: 1,
  },
  {
    id: "task-012",
    title: "Present at team knowledge share",
    description: "Prepare and deliver a 15-minute presentation on a topic of your expertise.",
    phase: "month3",
    taskType: "action",
    priority: "normal",
    dueDaysOffset: 75,
    isLocked: false,
    isCompleted: false,
    order: 2,
  },
  {
    id: "task-013",
    title: "Complete 90-day performance review",
    description: "Self-assessment and manager review of your first quarter performance.",
    phase: "month3",
    taskType: "survey",
    priority: "critical",
    dueDaysOffset: 90,
    isLocked: true,
    isCompleted: false,
    order: 3,
  },
  // ── MONTH 6 (2 tasks) ──
  {
    id: "task-014",
    title: "Mentor a new joiner",
    description: "Pay it forward by becoming an onboarding buddy for the next cohort.",
    phase: "month6",
    taskType: "action",
    priority: "normal",
    dueDaysOffset: 150,
    isLocked: false,
    isCompleted: false,
    order: 1,
  },
  {
    id: "task-015",
    title: "Complete 6-month career development plan",
    description: "Work with your manager to set goals for the next 12 months.",
    phase: "month6",
    taskType: "document",
    priority: "high",
    dueDaysOffset: 180,
    isLocked: false,
    isCompleted: false,
    order: 2,
  },
];

export var SAMPLE_MILESTONES: IOnboardMilestone[] = [
  {
    id: "milestone-001",
    title: "First Steps",
    description: "Complete all preboarding tasks",
    badgeEmoji: "\uD83D\uDC63",
    badgeColor: "#0078d4",
    unlockCriteria: { type: "phaseComplete", value: 1, phaseId: "preboarding" },
    isUnlocked: true,
  },
  {
    id: "milestone-002",
    title: "Quick Learner",
    description: "Complete 5 tasks in your first week",
    badgeEmoji: "\uD83C\uDF1F",
    badgeColor: "#107c10",
    unlockCriteria: { type: "taskCount", value: 5 },
    isUnlocked: false,
  },
  {
    id: "milestone-003",
    title: "Streak Master",
    description: "Check in for 7 consecutive days",
    badgeEmoji: "\uD83D\uDD25",
    badgeColor: "#ca5010",
    unlockCriteria: { type: "streakDays", value: 7 },
    isUnlocked: false,
  },
  {
    id: "milestone-004",
    title: "Team Player",
    description: "Attend all scheduled meetings in Week 1",
    badgeEmoji: "\uD83E\uDD1D",
    badgeColor: "#8764b8",
    unlockCriteria: { type: "taskCount", value: 8 },
    isUnlocked: false,
  },
  {
    id: "milestone-005",
    title: "Onboarding Champion",
    description: "Complete all onboarding tasks",
    badgeEmoji: "\uD83C\uDFC6",
    badgeColor: "#d4a017",
    unlockCriteria: { type: "allComplete", value: 15 },
    isUnlocked: false,
  },
];

export var SAMPLE_RESOURCES: IOnboardResource[] = [
  {
    id: "res-001",
    title: "Employee Handbook 2026",
    description: "Complete guide to company policies, benefits, and procedures.",
    resourceType: "document",
    url: "",
    phase: "preboarding",
  },
  {
    id: "res-002",
    title: "IT Setup Guide",
    description: "Step-by-step guide for configuring your laptop, VPN, and tools.",
    resourceType: "document",
    url: "",
    phase: "preboarding",
  },
  {
    id: "res-003",
    title: "Company Culture Video",
    description: "A 10-minute overview of our values, mission, and ways of working.",
    resourceType: "video",
    url: "",
    duration: "10 min",
    phase: "week1",
  },
  {
    id: "res-004",
    title: "POPIA Compliance Training",
    description: "Mandatory data protection training for all South African employees.",
    resourceType: "training",
    url: "",
    duration: "45 min",
    phase: "month1",
  },
  {
    id: "res-005",
    title: "Office Floor Plan",
    description: "Interactive map of the Sandton headquarters.",
    resourceType: "link",
    url: "",
    phase: "week1",
  },
  {
    id: "res-006",
    title: "Benefits Enrollment Guide",
    description: "Medical aid, retirement fund, and group risk benefit options.",
    resourceType: "document",
    url: "",
    phase: "week1",
  },
  {
    id: "res-007",
    title: "Leadership Meet & Greet Recordings",
    description: "Video introductions from each department head.",
    resourceType: "video",
    url: "",
    duration: "30 min",
    phase: "month1",
  },
  {
    id: "res-008",
    title: "Career Development Framework",
    description: "Understanding growth paths, promotions, and skill development at First Digital.",
    resourceType: "document",
    url: "",
    phase: "month3",
  },
];
